First draft for "Manage your CWS item"
GoogleChrome/developer.chrome.com pull request #1224
Opened 2021-08-17 22:25 UTC by AmySteam

This page is a draft

2021-08-18 03:17 UTC, samthor commented on site/en/docs/webstore/manage/index.md
> +To ensure a positive experience for your users follow the [developer program policies][dev-policies]. These policies may change, so keep up with [new announcements][whats-new].
nit: insert blank line above

2021-08-18 03:17 UTC, samthor commented on site/en/docs/webstore/manage/index.md
> + The status of your item appears in the [developer dashboard][dev-dashboard] next to each item. The status can be Published, Pending or Rejected.
nit: remove leading whitespace

2021-08-18 03:17 UTC, samthor commented on site/en/docs/webstore/manage/index.md
> +All extensions go through an automated review process. In some instances a manual review is required, specially when sensitive permissions are requested. For this reason review times and/or approval
This is totally bikeshedded, but could you put each new sentence on its own line? I don't want wrapping, but whole paragraphs makes restructuring still a bit tricky.

2021-08-23 19:29 UTC, jpmedley requested changes
Really clean. I just found a few typos.

2021-08-23 19:29 UTC, jpmedley commented on site/en/docs/webstore/manage/index.md
> +All Chrome Web Store items go through an automated review process. In some instances a manual review is required, specially when sensitive permissions are requested.
```suggestion
All Chrome Web Store items go through an automated review process. In some instances a manual review is required, especially when sensitive permissions are requested. 
```

2021-08-23 19:29 UTC, jpmedley commented on site/en/docs/webstore/manage/index.md
> +The status of your item appears in the [developer dashboard][dev-dashboard] next to each item. The status can be Published, Pending or Rejected.
```suggestion
The status of your item appears in the [developer dashboard][dev-dashboard] next to each item. The status can be Published, Pending, or Rejected.
```

2021-08-23 21:40 UTC, AmySteam commented
@jpmedley, applied your changes! Made a minor tweak, can you PTAL? Thanks! [Staged Preview](https://deploy-preview-1224--developer-chrome-com.netlify.app/docs/webstore/manage/)

2021-08-24 15:49 UTC, jpmedley approved these changes

2021-08-24 15:50 UTC, jpmedley commented
Within the Chrome DevRel team, authors merge their own PRs. Have you been doing that or do you need me to.

2021-08-24 15:53 UTC, AmySteam commented
@jpmedley I have been merging! Thanks 👍

2021-08-24 15:53 UTC, merged