devtools storage cleanups
GoogleChrome/developer.chrome.com pull request #1235
Opened 2021-08-19 05:26 UTC by samthor

Taken over from #958, which only removed the image from one page.

While I was here, I've:
- removed Application Cache (dropped in m85)
- made Web SQL disuse more clear

2021-08-20 16:38 UTC, jpmedley requested changes
Andy's OOO, so I picked this up.

2021-08-20 16:38 UTC, jpmedley commented on site/en/docs/devtools/storage/websql/index.md
> +1.  Click the **Sources** tab to open the **Application** panel.Expand the **Web SQL** section to view databases and tables. In **Figure 1** below
```suggestion
1.  Click the **Sources** tab to open the **Application** panel. Expand the **Web SQL** section to view databases and tables. In **Figure 1** below
```

2021-08-23 04:07 UTC, chybie approved these changes
LGTM with one minor typo

2021-08-23 04:07 UTC, chybie commented on site/en/docs/devtools/storage/cache/index.md
> +    **Figure 0**. The **Clear Site Data** button.
Figure 9

2021-08-23 04:12 UTC, merged