CUJ Tweaks for I can collaborate with other people to publish my extension
GoogleChrome/developer.chrome.com pull request #1326
Opened 2021-08-31 21:37 UTC by AmySteam

Fixes #1281 

Changes proposed in this pull request:

- Add links
- Consolidate instructions

2021-09-01 14:00 UTC, jpmedley requested changes

2021-09-01 18:33 UTC, AmySteam commented on site/en/docs/webstore/group-publishers/index.md
> +* If the group publisher account has reached its published item limit (20 items), you won't be able to transfer your published items to this group publisher.
@jpmedley, what do you think about including [this link](https://developer.chrome.com/docs/webstore/faq/#faq-gen-29)?

2021-09-02 13:41 UTC, jpmedley commented on site/en/docs/webstore/group-publishers/index.md
> +* If the group publisher account has reached its published item limit (20 items), you won't be able to transfer your published items to this group publisher.
That looks exactly right.

2021-09-02 13:41 UTC, jpmedley approved these changes

2021-09-02 13:41 UTC, merged