deps-rems-91: add followup note on deprecating third-party iframe `alert()` & Co.
GoogleChrome/developer.chrome.com pull request #1337
Opened 2021-09-01 19:38 UTC by myakura

Changes proposed in this pull request:

- change pubDate to the day it was actually published
- add notes that:
  - deprecation took effect for a while after M92 release
  - then put on hold due to large number of breakage
  - and postponed to until at least Jan 2022

2021-09-02 19:02 UTC, jpmedley requested changes

2021-09-02 19:02 UTC, jpmedley commented on site/en/blog/deps-rems-91/index.md
> +**Updated September, 1th 2021**: Chrome started gradual rollout in Chrome 92 but backed out due to unexpected amout of breakage. Chrome has rolled back the change and has decided to postopone the dep
```suggestion
**Updated September, 1th 2021**: Chrome started gradual rollout in Chrome 92 but backed out due to an unexpected amount of breakage. Chrome has rolled back the change and has postponed the deprecation until at least January 2022. Developers are still encouraged to migrate to non-system dialogs.
```

2021-09-07 14:22 UTC, jpmedley approved these changes

2021-09-07 15:25 UTC, jpmedley commented
@robdodson What is this asking me to fix?

2021-09-07 16:32 UTC, robdodson commented
It looks like the site build is broken because of Chrome Extensions API. This is something @samthor has been working on and should know how to fix.

2021-09-07 21:12 UTC, samthor commented
@jpmedley Sorry, I fixed this yesterday (although have plans to improve it with a cache); please rebase to the current head.

2021-09-08 17:15 UTC, jpmedley approved these changes

2021-09-16 22:33 UTC, myakura commented
> @jpmedley Sorry, I fixed this yesterday (although have plans to improve it with a cache); please rebase to the current head.

oops. looks like I've done it pretty badly :(

2021-09-16 22:40 UTC, myakura commented
@googlebot I fixed it.

2021-09-17 14:00 UTC, merged