Add Chrome Dev Tools 93 release notes Spanish translation
GoogleChrome/developer.chrome.com pull request #1339
Opened 2021-09-02 14:53 UTC by midudev

Fixes #1298.

Add Chrome Dev Tools 93 release notes Spanish translation

2021-09-02 14:56 UTC, chybie commented
Please help to review @Carlillo, @and-oli!

2021-09-02 15:08 UTC, chybie requested changes

2021-09-02 15:08 UTC, chybie commented on site/_includes/partials/devtools/es/whats-new.md
>  ## More DevTools features {: #whats-new }
Please help to translate these!

2021-09-02 15:08 UTC, chybie commented on site/es/blog/new-in-devtools-93/index.md
> +{% include 'partials/devtools/es/reach-out.md' %}
Please help to translate these files!

2021-09-02 15:46 UTC, midudev commented on site/_includes/partials/devtools/es/whats-new.md
>  ## More DevTools features {: #whats-new }
Done!

2021-09-02 15:46 UTC, midudev commented on site/es/blog/new-in-devtools-93/index.md
> +{% include 'partials/devtools/es/reach-out.md' %}
Done!

2021-09-03 01:24 UTC, and-oli commented on site/es/blog/new-in-devtools-93/index.md
> +Las consultadas de contenderos (*container queries*) ofrece una manera mucho más dinámica de realizar diseños adaptables. La regla `@container` funciona de una forma similar a las consultas de medios
```suggestion
Las consultas de contenderos (*container queries*) ofrece una manera mucho más dinámica de realizar diseños adaptables. La regla `@container` funciona de una forma similar a las consultas de medios (*media queries*). Sin embargo, en lugar de consultar el tamaño de la ventana y la información del agente del usuario, `@container` consulta el contenedor ascendiente que cumple cierto criterio.
```

2021-09-03 01:39 UTC, and-oli reviewed
Added some minor comments. Muchas gracias por la traducción Miguel! :)

2021-09-03 01:39 UTC, and-oli commented on site/es/blog/new-in-devtools-93/index.md
> +## Arreglados los selectors CSS coincidentes {: #matching-selectors }
Since this is a feature I suggest rephrasing it as
```suggestion
## Se arreglaron los selectores CSS coincidentes {: #matching-selectors }
```

2021-09-03 01:39 UTC, and-oli commented on site/_includes/partials/devtools/es/reach-out.md
> +- Reporta un problema con las DevTools usando **Más opciones** &nbsp; {% Img src="image/admin/4sdCQbpBaG4MpoHB1J08.png", alt="Más", width="4", height="20" %} &nbsp; > **Ayuda** > **Reportar un proble
```suggestion
- Reporta un problema con DevTools usando **Más opciones** &nbsp; {% Img src="image/admin/4sdCQbpBaG4MpoHB1J08.png", alt="Más", width="4", height="20" %} &nbsp; > **Ayuda** > **Reportar un problema con DevTools** in DevTools.
```

2021-09-04 10:26 UTC, midudev commented
Thanks @and-oli for the suggestions. I've merged them! 👍

2021-09-06 00:41 UTC, chybie commented
@caballerog Please help to review.

2021-09-06 10:00 UTC, Caballerog requested changes

2021-09-07 00:29 UTC, chybie commented
Let me know if the post is good to go @midudev! :D

2021-09-08 06:21 UTC, chybie approved these changes

2021-09-08 15:20 UTC, midudev commented
Fixed feedback. Thanks @Caballerog

2021-09-09 00:35 UTC, merged