[devtools-translate] Portuguese - What's New in DevTools (Chrome 94)
GoogleChrome/developer.chrome.com pull request #1343
Opened 2021-09-04 21:37 UTC by alvarocamillont

Fixes #1304

Changes proposed in this pull request:

    Add portuguese translations for What's New in DevTools M94

2021-09-07 00:24 UTC, chybie commented
Thanks @alvarocamillont , @khaosdoctor and @andreban, please help to review this.

2021-09-07 09:08 UTC, andreban reviewed
Thanks for writing this. Left some notes.

2021-09-07 09:08 UTC, andreban commented on site/pt/blog/new-in-devtools-94/index.md
> +O **Console** agora mostra acessores nativos como propriedades consistentemente.
```suggestion
O **Console** agora mostra métodos de acesso nativos como propriedades de forma consistente.
```

2021-09-07 09:08 UTC, andreban commented on site/pt/blog/new-in-devtools-94/index.md
> +Por exemplo, ao avaliar a expressão `new Int8Array ([1, 2, 3])` no **Console**, acessadores nativos como `length`,` byteOffset` não eram exibidos na visualização. Com esta atualização, os acessores n
```suggestion
Por exemplo, ao avaliar a expressão `new Int8Array ([1, 2, 3])` no **Console**, métodos de acesso nativos como `length`,` byteOffset` não eram exibidos na visualização. Com esta atualização, os métodos de acesso nativos aparecem na visualização e os valores são avaliados quando expandidos.
```

2021-09-07 09:08 UTC, andreban commented on site/pt/blog/new-in-devtools-94/index.md
> +Você agora pode alterar o formato da cor de qualquer elemento no painel Computed segurando a tecla <kbd>Shift</kbd> e clicando  na visualização da cor.
nit: remove double space.

```suggestion
Você agora pode alterar o formato da cor de qualquer elemento no painel Computed segurando a tecla <kbd>Shift</kbd> e clicando na visualização da cor.
```

2021-09-07 09:08 UTC, andreban commented on site/pt/blog/new-in-devtools-94/index.md
> +Infelizmente, manter uma implementação de tooltips customizado é complicado e encontramos regularmente bugs complicados.
- avoiding repetition of "complicado"
- "encontramos bugs complicados regularmente" seems to read a bit better.
```suggestion
Infelizmente, manter uma implementação de tooltips customizado é complexo e encontramos bugs complicados regularmente.
```

2021-09-08 02:34 UTC, chybie requested changes

2021-09-08 02:34 UTC, chybie commented on site/pt/blog/new-in-devtools-94/index.md
> +{% include 'partials/devtools/en/banner.md' %}
replace `/en` with `/pt`

2021-09-08 02:34 UTC, chybie commented on site/pt/blog/new-in-devtools-94/index.md
> +{% include 'partials/devtools/en/reach-out.md' %}
replace `/en` with `/pt`

2021-09-08 02:34 UTC, chybie commented on site/pt/blog/new-in-devtools-94/index.md
> +{% include 'partials/devtools/en/whats-new.md' %}
replace `/en` with `/pt`

2021-09-08 09:09 UTC, andreban approved these changes
Thanks for this! LGTM from a translation perspective.

2021-09-09 16:20 UTC, khaosdoctor requested changes
Small translation changes

2021-09-09 16:20 UTC, khaosdoctor commented on site/pt/blog/new-in-devtools-94/index.md
> +*Tradução realizada por [Alvaro Camillo Neto](https://www.linkedin.com/in/alvarocamillont/).*
```suggestion
*Tradução realizada por [Alvaro Camillo Neto](https://www.linkedin.com/in/alvarocamillont/). Revisão por [Lucas Santos](https://lsantos.dev)*
```

2021-09-09 16:20 UTC, khaosdoctor commented on site/pt/blog/new-in-devtools-94/index.md
> +## Obsolescência da barra lateral do Console {: #deprecated }
```suggestion
## Depreciação da barra lateral do Console {: #deprecated }
```

2021-09-09 16:20 UTC, khaosdoctor commented on site/pt/blog/new-in-devtools-94/index.md
> +Anteriormente, o DevTools não mostrava cookies malformados (cabeçalho `Set-Cookie` incorreto) no painel **Network**. Com o novo filtro `response-header-set-cookie` adicionado ao painel **Network**, o
```suggestion
Anteriormente, o DevTools não mostrava cookies malformados (cabeçalho `Set-Cookie` incorreto) no painel **Network**. Com o novo filtro `response-header-set-cookie` adicionado ao painel **Network**, os usuários podem filtrar a resposta do cabeçalho `Set-Cookie`. O DevTools vinculará os cabeçalhos `Set-Cookie` na guia **Issues** ao painel **Network**.
```

2021-09-09 16:20 UTC, khaosdoctor commented on site/pt/blog/new-in-devtools-94/index.md
> +Por exemplo, ao avaliar a expressão `new Int8Array ([1, 2, 3])` no **Console**, acessadores nativos como `length`,` byteOffset` não eram exibidos na visualização. Com esta atualização, os métodos de
```suggestion
Por exemplo, ao avaliar a expressão `new Int8Array ([1, 2, 3])` no **Console**, propriedades nativas como `length`,` byteOffset` não eram exibidas na visualização. Com esta atualização, os métodos de acesso nativos aparecem na visualização e os valores são avaliados quando expandidos.
```

2021-09-10 01:53 UTC, chybie commented
Thanks @khaosdoctor. Over to @alvarocamillont for final check. Let me know when it's good to go!

2021-09-10 02:16 UTC, alvarocamillont commented
Done!

2021-09-10 02:20 UTC, chybie approved these changes

2021-09-10 02:36 UTC, merged