Translate new-in-devtools-95 in Japanese
GoogleChrome/developer.chrome.com pull request #1484
Opened 2021-09-22 01:21 UTC by lacolaco

2021-09-22 01:31 UTC, lacolaco commented
@technohippy @yoichiro Ready to review. Could you check my translation?

2021-09-22 02:21 UTC, technohippy commented on site/ja/blog/new-in-devtools-95/index.md
> +  "新しいCSSの長さ編集ツール、 Issues タブでの課題の非表示、プロパティの表示の改善など"
DevToolsの表示を日本語にするとIssuesは課題じゃなくて「問題」になっているようです。揃えたほうが良いかも

2021-09-22 05:46 UTC, yoichiro requested changes
@lacolaco I posted some comments. Could you confirm them? Thanks!

2021-09-22 05:46 UTC, yoichiro commented on site/ja/blog/new-in-devtools-95/index.md
> +6つの言語 - [ロシア語](/ru/blog/new-in-devtools-95)、[中国語](/zh/blog/new-in-devtools-95)、[スペイン語](/es/blog/new-in-devtools-95)、[日本語](/ja/blog/new-in-devtools-95)です。[スペイン語](/es/blog/new-in-devtools-95)、[日本語](/ja
```suggestion
6つの言語で DevTools のリリースノートを What’s new タブからクリックしてご覧いただけるようになりました - [ロシア語](/ru/blog/new-in-devtools-95)、[中国語](/zh/blog/new-in-devtools-95)、[スペイン語](/es/blog/new-in-devtools-95)、[日本語](/ja/blog/new-in-devtools-95)、[ポルトガル語](/pt/blog/new-in-devtools-95)、[韓国語](/ko/blog/new-in-devtools-95)
```

@lacolaco 訳文がおかしいようです。上記でいかがでしょうか？

2021-09-22 05:46 UTC, yoichiro commented on site/ja/blog/new-in-devtools-95/index.md
> +Chrome 94以降、 DevTools で[優先言語の設定](/blog/new-in-devtools-94/#localized)ができるようになりました。翻訳に関する問題を発見された場合は、 **More options** > **Help** > **Report a translation bug** で[翻訳の課題を報告](https://goo.gle/devtools-tr
```suggestion
Chrome 94以降、 DevTools で[優先言語の設定](/blog/new-in-devtools-94/#localized)ができるようになりました。翻訳に関する問題を発見された場合は、 **More options** > **Help** > **Report a translation bug** で[翻訳の問題を報告](https://goo.gle/devtools-translate)して、改善にご協力ください。
```

@lacolaco Report a translation bug メニューでもありますので、「issue」は「問題」と訳したほうがここは適切かと思いますがいかがでしょうか？

2021-09-22 05:48 UTC, lacolaco commented on site/ja/blog/new-in-devtools-95/index.md
> +6つの言語 - [ロシア語](/ru/blog/new-in-devtools-95)、[中国語](/zh/blog/new-in-devtools-95)、[スペイン語](/es/blog/new-in-devtools-95)、[日本語](/ja/blog/new-in-devtools-95)です。[スペイン語](/es/blog/new-in-devtools-95)、[日本語](/ja
おっと、事故ってました。このまま取り入れようと思います！

2021-09-22 05:48 UTC, lacolaco commented on site/ja/blog/new-in-devtools-95/index.md
> +Chrome 94以降、 DevTools で[優先言語の設定](/blog/new-in-devtools-94/#localized)ができるようになりました。翻訳に関する問題を発見された場合は、 **More options** > **Help** > **Report a translation bug** で[翻訳の課題を報告](https://goo.gle/devtools-tr
そうですね、そうします！

2021-09-22 05:59 UTC, yoichiro commented
@googlebot I fixed it.

2021-09-22 06:00 UTC, lacolaco commented
@googlebot I fixed it.

2021-09-22 06:15 UTC, yoichiro approved these changes
@lacolaco LGTM! Thank you!

2021-09-22 06:21 UTC, yoichiro requested changes
@lacolaco You also need to add links for each section in the  https://github.com/GoogleChrome/developer.chrome.com/blob/main/site/_includes/partials/devtools/ja/whats-new.md file. Could you do this?

2021-09-22 07:09 UTC, yoichiro commented
@googlebot I fixed it.

2021-09-22 07:18 UTC, yoichiro requested changes

2021-09-22 07:18 UTC, yoichiro commented on site/_includes/partials/devtools/ja/whats-new.md
> +* [新しいCSSの長さ編集ツール](/ja//blog/new-in-devtools-95/#)
```suggestion
* [新しいCSSの長さ編集ツール](/ja//blog/new-in-devtools-95/#length)
```

2021-09-22 07:19 UTC, lacolaco commented on site/_includes/partials/devtools/ja/whats-new.md
> +* [新しいCSSの長さ編集ツール](/ja//blog/new-in-devtools-95/#)
en側のミスですね 気づかなかったですありがとうございます

2021-09-22 07:42 UTC, yoichiro approved these changes

2021-09-24 04:52 UTC, yoichiro commented
@lacolaco GitHub would detected the conflicting file. Could you resolve it? Then, you can ask @agektmr  for a final review.

2021-09-24 06:38 UTC, agektmr approved these changes
LGTM

2021-09-24 06:48 UTC, agektmr commented
@chybie This should be ready to be merged.

2021-09-24 07:14 UTC, merged