Add android:exported=true to TWA integration guide
GoogleChrome/developer.chrome.com pull request #1624
Opened 2021-10-26 12:50 UTC by devbridie

See [Android doc on Behavior Changes in Android 12](https://developer.android.com/about/versions/12/behavior-changes-12#exported). A value for `android:exported` is required when targeting Android 12; true is required for the `LAUNCHER` category.

2021-12-07 20:03 UTC, AndreasBoehm approved these changes

2022-10-11 15:15 UTC, andreban requested changes

2022-10-11 15:15 UTC, andreban commented on site/en/docs/android/trusted-web-activity/integration-guide/index.md
> +        android:exported="true"
Thanks for sending the PR.

My understanding from the docs is that `android:exported="true"` should be added to the `activity` tag, not the `application` tag (as in the example [here](https://github.com/GoogleChromeLabs/bubblewrap/blob/main/packages/core/template_project/app/src/main/AndroidManifest.xml#L104)). Would you mind moving it to the `activity` tag?

2023-10-31 07:15 UTC, rachelandrew commented
Closing as OP did not return to address comments.

2023-10-31 07:15 UTC, closed without merging