[devtools-translate] Russian - What's New in DevTools (Chrome 96)
GoogleChrome/developer.chrome.com pull request #1638
Opened 2021-10-28 12:01 UTC by solarrust

Fixes #1619 

@webmaxru @kateryna-prokopenko welcome to review! 🙌

2021-11-09 18:57 UTC, solarrust commented
Hi @webmaxru @kateryna-prokopenko !
How can I help you with review of my translation?

2021-11-10 09:16 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-96/index.md
> +Боковую колонку в Консоли (Console) решено оставить. В Chrome 94 мы анонсировали [упразднение боковой колонки в Консоли](/blog/new-in-devtools-94/#deprecated) и попросили разработчиков высказать свои
```suggestion
Боковая колонка в Консоли (Console) остается. В Chrome 94 мы анонсировали предстоящее [упразднение боковой колонки в Консоли](/blog/new-in-devtools-94/#deprecated) и попросили разработчиков высказать свои размышления и сомнения по этому поводу.
```

2021-11-10 09:16 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-96/index.md
> +Мы получили достаточное количество отзывов, и теперь мы будем работать над улучшением боковой панели, а не над её удалением.
```suggestion
Мы теперь получили достаточное количество отзывов, и будем работать над улучшением боковой панели, а не над её удалением.
```

2021-11-10 09:16 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-96/index.md
> +Панель [Кэш приложения](https://developer.chrome.com/docs/devtools/storage/applicationcache/) на вкладке Приложение удалена поскольку [AppCache](https://web.dev/appcache-removal/) больше не поддержив
```suggestion
Панель [Кэш приложения](https://developer.chrome.com/docs/devtools/storage/applicationcache/) (Application cache) на вкладке Приложение (Application) удалена, поскольку [AppCache](https://web.dev/appcache-removal/) больше не поддерживается в Chrome и других браузеров на основе Chromium.
```

2021-11-10 09:16 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-96/index.md
> +После включения этого эксперимента вы сможете просматривать отчёты в панели **Reporting API** во вкладке **Приложение** (Application).
```suggestion
С включенным экспериментом вы теперь можете просматривать статус отчётов в панели **Reporting API** во вкладке **Приложение** (Application). 
```

2021-11-10 11:10 UTC, solarrust reviewed
Thank you for your time, @kateryna-prokopenko 🙌

I add some comments and questions.

Can you, please, explain me when I should use «Панель» and when «Вкладка»? I have no clear understanding of this right now.

2021-11-10 11:10 UTC, solarrust commented on site/ru/blog/new-in-devtools-96/index.md
> +Откройте [Командное меню (Command Menu)](/docs/devtools/command-menu/), выполните команду **Показать "Отрисовка"** (Show Rendering) и выберите нужное значение в выпадающем меню **Эмулировать медиафун
I took translation from Canary DevTools

![CleanShot 2021-11-10 at 14 02 26](https://user-images.githubusercontent.com/13676514/141101725-e187e617-6dc2-48d8-8a48-82d3902f69b5.png)

And «медиафункция» in Russian shouldn't have a dash =)

2021-11-10 11:10 UTC, solarrust commented on site/ru/blog/new-in-devtools-96/index.md
> +Объекты [Intl](https://tc39.es/ecma402/#intl-object) теперь имеют удобный предварительный просмотр и их легко оценить в Консоли (Console). Ранее объекты `Intl` не отображались надлежащим образом.
What is «энергичные вычисления»? =)

2021-11-10 11:10 UTC, solarrust commented on site/ru/blog/new-in-devtools-96/index.md
> +Мы получили достаточное количество отзывов, и теперь мы будем работать над улучшением боковой панели, а не над её удалением.
It's strange sentence «Мы теперь получили» 🤔

2021-11-11 08:19 UTC, chybie requested changes

2021-11-11 08:19 UTC, chybie commented on site/_includes/partials/devtools/ru/whats-new.md
> +<!-- * [Restored and improved CSS length edit and copy experince](/ru/blog/new-in-devtools-966/#length) -->
Please update this

2021-11-11 08:19 UTC, chybie commented on site/ru/blog/new-in-devtools-96/index.md
> +<!-- ## Restored and improved CSS length edit and copy experince {: #length } -->
I added a new section here as we merged some fixes in M96 after my article is published. Please help to translate as well. Thanks!

2021-11-11 08:30 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-96/index.md
> +Мы получили достаточное количество отзывов, и теперь мы будем работать над улучшением боковой панели, а не над её удалением.
It's fine to leave it out altogether

2021-11-11 08:37 UTC, kateryna-prokopenko commented
https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%82%D0%B5%D0%B3%D0%B8%D1%8F_%D0%B2%D1%8B%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F
You can find энергичные вычисления used for eager evaluation here, if you search the article.

As for tab, panel and pane, the first two (tab and panel) should be translated as вкладка and pane as панель.

Thanks!

2021-11-11 08:51 UTC, solarrust commented
@kateryna-prokopenko cool, thank you for the link and for explanation about tabs and panels 🙌

2021-11-11 08:56 UTC, solarrust commented
@chybie I added translation of the new block ✅

2021-11-11 09:23 UTC, chybie commented
Thanks Alena! I've ping webmaxru for final review. :)

2021-11-11 22:27 UTC, webmaxru requested changes

2021-11-11 22:27 UTC, webmaxru commented on site/ru/blog/new-in-devtools-96/index.md
> +Вы можете скрыть ошибки CORS в **Консоли** (Console). Поскольку ошибки CORS теперь показываются в панели Проблемы (Issues), их скрытие в панели **Консоль** (Console) поможет уменьшить беспорядок.
```suggestion
Вы можете скрыть ошибки CORS в **Консоли** (Console). Поскольку ошибки CORS теперь показываются в панели Проблемы (Issues), панель **Консоль** (Console) выглядит менее загроможденной.
```

2021-11-11 22:27 UTC, webmaxru commented on site/ru/blog/new-in-devtools-96/index.md
> +{% Img src="image/dPDCek3EhZgLQPGtEG3y0fTn4v82/wuKo84nrDzbhwCnIVU2n.png", alt="стек трассировки async", width="800", height="427" %}
```suggestion
{% Img src="image/dPDCek3EhZgLQPGtEG3y0fTn4v82/wuKo84nrDzbhwCnIVU2n.png", alt="Стек трассировки async", width="800", height="427" %}
```

2021-11-11 22:27 UTC, webmaxru commented on site/ru/blog/new-in-devtools-96/index.md
> +Мы получили достаточное количество отзывов, и теперь будем работать над улучшением боковой панели, а не над её удалением.
```suggestion
Мы получили достаточное количество отзывов и теперь будем работать над улучшением боковой панели, а не над её удалением.
```

2021-11-11 22:27 UTC, webmaxru commented on site/ru/blog/new-in-devtools-96/index.md
> +Боковая колонка в Консоли (Console) остается. В Chrome 94 мы анонсировали предстоящее [упразднение боковой колонки в Консоли](/blog/new-in-devtools-94/#deprecated) и попросили разработчиков высказать
```suggestion
Боковая колонка в Консоли (Console) остается на своем месте. В Chrome 94 мы анонсировали предстоящее [упразднение боковой колонки в Консоли](/blog/new-in-devtools-94/#deprecated) и попросили разработчиков высказать свои размышления и сомнения по этому поводу.
```

2021-11-11 22:27 UTC, webmaxru commented on site/ru/blog/new-in-devtools-96/index.md
> +Панель [Кэш приложения](https://developer.chrome.com/docs/devtools/storage/applicationcache/) (Application cache) на вкладке Приложение (Application) удалена, поскольку [AppCache](https://web.dev/app
```suggestion
Панель [Кеш приложений](https://developer.chrome.com/docs/devtools/storage/applicationcache/) (Application cache) на вкладке Приложение (Application) удалена, поскольку [AppCache](https://web.dev/appcache-removal/) больше не поддерживается в Chrome и других браузерах на основе Chromium.
```
Кеш приложений - именно так это называется в DevTools на русском

2021-11-11 22:27 UTC, webmaxru commented on site/ru/blog/new-in-devtools-96/index.md
> +Чтобы включить эксперимент поставьте галочку в чекбоксе напротив пункта **Enable Reporting API panel in the Application panel** во вкладке **Настройки** (Settings) > **Экспериментальные функции** (Ex
```suggestion
Чтобы включить эксперимент, поставьте галочку в чекбоксе напротив пункта **Enable Reporting API panel in the Application panel** во вкладке **Настройки** (Settings) > **Экспериментальные функции** (Experiments).
```

2021-11-11 22:27 UTC, webmaxru commented on site/_includes/partials/devtools/ru/whats-new.md
> +* [Эмуляция CSS-медиафичи prefers-contrast](/ru/blog/new-in-devtools-96/#prefers-contrast)
```suggestion
* [Эмуляция CSS-медиафункции prefers-contrast](/ru/blog/new-in-devtools-96/#prefers-contrast)
```

2021-11-11 22:27 UTC, webmaxru commented on site/ru/blog/new-in-devtools-96/index.md
> +Кроме того, можно перетаскивать для настройки значения единицы измерения и обновлять тип единицы измерения с помощью выпадающего списка. Эта дополнительная функция редактирования длины не должна влия
```suggestion
Кроме того, значение можно изменять перетаскиванием, а единицы измерения задавать с помощью выпадающего списка. Эта дополнительная возможность редактирования не влияет на основное редактирование в виде текста.
```

2021-11-13 01:57 UTC, chybie approved these changes

2021-11-13 01:57 UTC, chybie commented
Спасибо вам всем!

2021-11-13 01:57 UTC, merged