[devtools-translate] Japanese - What's New in DevTools (Chrome 96)
GoogleChrome/developer.chrome.com pull request #1661
Opened 2021-11-01 15:09 UTC by technohippy

Fixes #1615 

Changes proposed in this pull request:

- janapese translation

2021-11-03 10:30 UTC, yoichiro requested changes
@technohippy いくつかコメントしました。ご確認お願いいたします！

2021-11-03 10:30 UTC, yoichiro commented on site/_includes/partials/devtools/ja/whats-new.md
> +* [プレビュー機能: 新しい CSS オーバービューパネル](/blog/new-in-devtools-96/#css-overview)
Canaryで試したところ、CSS Overview パネルは「CSSの概要」という名前で表記されていました。それを踏襲すべきかもしれませんが、「CSSの概要」とまでしなくても、「オーバービュー」は「概要」としたほうが良いかと思いますが、いかがでしょうか？もしくは、掲載される画面キャプチャとの整合性から、"CSS Overview" と英語表記のままで行くほうが良いかもです（laco さん担当分のレビュー時には英語表記に寄せてました）。

<img width="238" alt="スクリーンショット 2021-11-03 19 03 33" src="https://user-images.githubusercontent.com/261787/140041584-7a98595e-9649-49a4-9b93-2bd2a12293ac.png">

```suggestion
* [プレビュー機能: 新しい CSS Overview パネル](/blog/new-in-devtools-96/#css-overview)
```

2021-11-03 10:30 UTC, yoichiro commented on site/ja/blog/new-in-devtools-96/index.md
> +## プレビュー機能: 新しい CSS オーバービューパネル {: #css-overview }
```suggestion
## プレビュー機能: 新しい CSS Overview パネル {: #css-overview }
```

2021-11-03 10:30 UTC, yoichiro commented on site/ja/blog/new-in-devtools-96/index.md
> +**CSS Overview** パネルは機能プレビューです。私達のチームはまだ積極的にこの機能に取り組んでおり、さらなる改善のための[フィードバック](https://goo.gle/css-overview-feedback)を求めています。
`what-new.md` での表記と合わせたほうが良いかと思います。

```suggestion
**CSS Overview** パネルはプレビュー機能です。私達のチームはまだ積極的にこの機能に取り組んでおり、さらなる改善のための[フィードバック](https://goo.gle/css-overview-feedback)を求めています。
```

2021-11-03 10:30 UTC, yoichiro commented on site/ja/blog/new-in-devtools-96/index.md
> +## Styles ペイン JavaScript として宣言をコピー {: #copy-as-js }
```suggestion
## Styles ペインで JavaScript として宣言をコピー {: #copy-as-js }
```

2021-11-03 10:30 UTC, yoichiro commented on site/ja/blog/new-in-devtools-96/index.md
> +### コンソールで CORS エラーを隠すオプションe {: #hide-cors-errors }
```suggestion
### コンソールで CORS エラーを隠すオプション {: #hide-cors-errors }
```

2021-11-03 10:30 UTC, yoichiro commented on site/ja/blog/new-in-devtools-96/index.md
> +[Intl](https://tc39.es/ecma402/#intl-object) オブジェクトが Console で適切にプレビューされ、貪欲に評価されるようになりました。以前は、`Intl`オブジェクトは貪欲には評価されませんでした。
`eagerly evaluation = 先行評価` される、ということかなと思いますが、いかがでしょうか？

```suggestion
[Intl](https://tc39.es/ecma402/#intl-object) オブジェクトが Console で適切にプレビューされ、先行評価されるようになりました。以前は、`Intl`オブジェクトは先行評価されませんでした。
```

2021-11-03 13:24 UTC, lacolaco commented on site/ja/blog/new-in-devtools-96/index.md
> +## Rendering タブの更新
更新というとRendering タブのRefreshのような感じがするので、変更点やアップデートというほうがしっくりくる気がします

2021-11-03 13:27 UTC, lacolaco commented on site/_includes/partials/devtools/ja/whats-new.md
> +* [Chrome の Auto Dark Theme 機能をエミュレート](/blog/new-in-devtools-96/#auto-dark-mode)
ひとつ上は 「〜のエミュレート」でこっちが「〜をエミュレート」となっているのが引っかかりました。どちらかに寄せてみるとどうでしょう

2021-11-04 15:23 UTC, technohippy commented on site/_includes/partials/devtools/ja/whats-new.md
> +* [Chrome の Auto Dark Theme 機能をエミュレート](/blog/new-in-devtools-96/#auto-dark-mode)
done

2021-11-04 15:23 UTC, technohippy commented on site/ja/blog/new-in-devtools-96/index.md
> +## Rendering タブの更新
done

2021-11-09 07:00 UTC, lacolaco approved these changes
LGTM!

2021-11-09 07:14 UTC, chybie commented
Arigatou all!

2021-11-09 07:14 UTC, chybie approved these changes

2021-11-09 07:14 UTC, merged