Translate "What are third-party origin trials?" into Japanese
GoogleChrome/developer.chrome.com pull request #1680
Opened 2021-11-04 04:51 UTC by yoichiro

I have translated the [What are third-party origin trials? - Chrome Developers](https://developer.chrome.com/blog/third-party-origin-trials/) article into Japanese.

Post: [What are third-party origin trials? - Chrome Developers](https://developer.chrome.com/blog/third-party-origin-trials/)
Translator: @yoichiro
Reviewer: @agektmr

2021-11-04 04:55 UTC, yoichiro commented
@chybie @samdutton @agektmr I have just translated the [What are third-party origin trials? - Chrome Developers](https://developer.chrome.com/blog/third-party-origin-trials/) into Japanese on this pull request. Could you review this pull request? Thank you in advance!

2021-11-05 13:39 UTC, samdutton commented
@jpchase fyi

2021-11-09 10:32 UTC, lacolaco reviewed
@yoichiro レビューしました！

2021-11-09 10:32 UTC, lacolaco commented on site/ja/blog/third-party-origin-trials/index.md
> +サードパーティプロバイダとしてオリジントライアルに参加する場合、オリジントライアルに含める予定のサイトのパートナーまたは顧客に通知し、見込みを設定するのは、あなたの責任となります。実験的な機能により予期しない問題が発生する可能性があります。そして、ブラウザベンダは、トラブルシューティングサポートを提供できないかもしれません。
set expectationsの訳は難しいですね　対案は浮かばないですがしっくりこない感覚があります

2021-11-09 10:32 UTC, lacolaco commented on site/ja/blog/third-party-origin-trials/index.md
> +1. サードパーティトークンの使用を制限するための選択肢を 1 つを選択します:
```suggestion
1. サードパーティトークンの使用を制限するための選択肢の 1 つを選択します:
```

2021-11-09 11:33 UTC, agektmr commented on site/ja/blog/third-party-origin-trials/index.md
> +サードパーティプロバイダとしてオリジントライアルに参加する場合、オリジントライアルに含める予定のサイトのパートナーまたは顧客に通知し、見込みを設定するのは、あなたの責任となります。実験的な機能により予期しない問題が発生する可能性があります。そして、ブラウザベンダは、トラブルシューティングサポートを提供できないかもしれません。
「期待値を設定する」はどうですか？

2021-11-11 12:45 UTC, agektmr requested changes
Added some comments.

2021-11-11 12:45 UTC, agektmr commented on site/ja/blog/third-party-origin-trials/index.md
> +{% Img src="image/8WbTDNrhLsU0El80frMBGE4eMCD3/fCachIuiBjh3XPo10CrN.png", alt="Diagram showing how third-party origin trials enable a single registration token to be used across multiple origins", wi
Translate the `alt` content as well?

2021-11-11 12:45 UTC, agektmr commented on site/ja/blog/third-party-origin-trials/index.md
> +サードパーティオリジントライアルをサポートすることで、より幅広く参加してもらうことが可能となりますが、実験的な機能の過度の使用または誤用の可能性も高まるため、"trusted tester" アプローチの方が適切です。 サードパーティオリジントライアルの範囲を拡大するには、サードパーティプロバイダとして参加するウェブ開発者に対して、追加の精査と責任が求められます。複数のサイトに影響を与える問題の
```suggestion
サードパーティオリジントライアルをサポートすることで、より幅広い参加が期待できますが、実験的な機能の過度の使用または誤用の可能性も高まるため、"トラステッドテスター" アプローチの方が適切です。 サードパーティオリジントライアルによるより広い影響範囲では、サードパーティプロバイダとして参加するウェブ開発者の、さらなる監視と責任が求められます。問題のあるサードパーティのスクリプトが複数のサイトに影響を与えるのを回避するため、サードパーティオリジントライアルを有効にするリクエストは、レビューが必要となる場合があります。オリジントライアル開発者ガイドにて、 [承認プロセス](https://github.com/GoogleChrome/OriginTrials/blob/gh-pages/developer-guide.md#18-how-can-i-enable-an-experimental-feature-as-embedded-content-on-different-domains) が説明されています。
```

2021-11-11 12:45 UTC, agektmr commented on site/ja/blog/third-party-origin-trials/index.md
> +     {% Img src="image/8WbTDNrhLsU0El80frMBGE4eMCD3/r07Zb0QoHnlgiItETR6q.png", alt="Chrome origin trials registration page for the Conversion Measurement API, with third-party matching checkbox selec
Translate the `alt` part?

2021-11-11 12:45 UTC, agektmr commented on site/ja/blog/third-party-origin-trials/index.md
> +     <figcaption class="w-figcaption">Registration page for the Conversion Measurement trial.</figcaption>
Translate the content of `figcaption`?

2021-11-11 12:45 UTC, agektmr commented on site/ja/blog/third-party-origin-trials/index.md
> +-  [Getting started with Chrome's origin trials](/blog/origin-trials/)
```suggestion
-  [Chrome のオリジントライアル入門](/ja/blog/origin-trials/)
```

2021-11-12 03:01 UTC, yoichiro commented on site/ja/blog/third-party-origin-trials/index.md
> +サードパーティプロバイダとしてオリジントライアルに参加する場合、オリジントライアルに含める予定のサイトのパートナーまたは顧客に通知し、見込みを設定するのは、あなたの責任となります。実験的な機能により予期しない問題が発生する可能性があります。そして、ブラウザベンダは、トラブルシューティングサポートを提供できないかもしれません。
d341320 で「期待値」に変更しました。

2021-11-12 05:00 UTC, yoichiro commented on site/ja/blog/third-party-origin-trials/index.md
> +{% Img src="image/8WbTDNrhLsU0El80frMBGE4eMCD3/fCachIuiBjh3XPo10CrN.png", alt="Diagram showing how third-party origin trials enable a single registration token to be used across multiple origins", wi
It has been translated at c377e4c.

2021-11-12 05:00 UTC, yoichiro commented on site/ja/blog/third-party-origin-trials/index.md
> +     {% Img src="image/8WbTDNrhLsU0El80frMBGE4eMCD3/r07Zb0QoHnlgiItETR6q.png", alt="Chrome origin trials registration page for the Conversion Measurement API, with third-party matching checkbox selec
It has been translated at c377e4c.

2021-11-12 05:00 UTC, yoichiro commented on site/ja/blog/third-party-origin-trials/index.md
> +     <figcaption class="w-figcaption">Registration page for the Conversion Measurement trial.</figcaption>
It has been translated at c377e4c.

2021-11-12 05:11 UTC, yoichiro commented
@agektmr @lacolaco Thank you for the reviewing! I modified them according to your mentions. Could you review them again?

2021-11-12 05:29 UTC, agektmr approved these changes
LGTM

2021-11-12 05:30 UTC, merged