[devtools-translate] Portuguese - What's New in DevTools (Chrome 96) #1618
GoogleChrome/developer.chrome.com pull request #1708
Opened 2021-11-09 03:08 UTC by alvarocamillont

Fixes #1618

Changes proposed in this pull request:

    Add portuguese translations for What's New in DevTools M96

2021-11-09 10:17 UTC, andreban requested changes
Overall, looks good, thank. Requested a couple changes.

2021-11-09 10:17 UTC, andreban commented on site/pt/blog/new-in-devtools-96/index.md
> +Você pode detalhar ainda mais as informações. Por exemplo, clique em uma cor na seção **Cores** para visualizar a lista de elementos que aplicam a mesma cor. Clique em um elemento para abri-lo no pai
Wondering if "expandir" reads better as a translation for drill down than "detalhar".
```suggestion
Você pode expandir as informações. Por exemplo, clique em uma cor na seção **Cores** para visualizar a lista de elementos que aplicam a mesma cor. Clique em um elemento para abri-lo no painel **Elementos**.
```

2021-11-09 10:17 UTC, andreban commented on site/pt/blog/new-in-devtools-96/index.md
> +### Emule o recurso de contraste preferencial para mídia de CSS {: #prefers-contrast }
`prefers-contrast` is the name of the CSS media (https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-contrast), used in the stylesheet. I'm wondering we should not translate the term.

2021-11-11 07:37 UTC, chybie requested changes

2021-11-11 07:37 UTC, chybie commented on site/pt/blog/new-in-devtools-96/index.md
> +<!-- ## Restored and improved CSS length edit and copy experince {: #length } -->
Hi @alvarocamillont , I added a new section here (a fix we recently merged back to M96). Sorry for late inform!

2021-11-11 08:02 UTC, chybie commented
@googlebot I consent.

2021-11-12 07:40 UTC, chybie approved these changes

2021-11-12 09:40 UTC, andreban approved these changes
LGTM, Thank you!

2021-11-13 01:56 UTC, merged