Update index.md
GoogleChrome/developer.chrome.com pull request #1799
Opened 2021-12-01 10:23 UTC by antoinebisch

Added FAQ: Does `SameSite` become irrelevant after the third-party cookie deprecation?

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

2021-12-02 20:21 UTC, samdutton approved these changes
LGTM with minor tweak.

Assume this is OK with (or written by) @rowan-m.

2022-05-18 13:10 UTC, heyawhite commented
@samdutton @antoinebisch @rowan-m should this still be reviewed and published?

2022-05-18 15:04 UTC, samdutton commented
> @samdutton @antoinebisch @rowan-m should this still be reviewed and published?

Definitely one for @rowan-m 💵 🏈

2022-07-27 12:39 UTC, rowan-m requested changes
Minor changes to bring this up to date, otherwise LGTM.

2022-07-27 12:39 UTC, rowan-m commented on site/en/docs/privacy-sandbox/faq/index.md
> + - The exception to this is cookies that are modified by either the `Partitioned` or `SameParty` attributes, which allows for a subset of cross-site use cases. *Note:* both these attributes are only
```suggestion
 - The exception to this is cookies that are modified by either the [CHIPS](https://developer.chrome.com/docs/privacy-sandbox/chips/) or [First-Party Sets](https://developer.chrome.com/docs/privacy-sandbox/first-party-sets/) proposals, which allows for a subset of cross-site use cases. *Note:* these proposals are under active discussion, so final formats and functionality may change.
```

2022-07-27 12:39 UTC, rowan-m commented on site/en/docs/privacy-sandbox/faq/index.md
> + - `SameSite=None` should continue to be sent for cross-browser consistency. However, Chrome's proposed change to phase out third-party cookies would result in those cookies no longer being sent in c
```suggestion
 - `SameSite=None` should continue to be sent for cross-browser consistency. However, Chrome's proposed change to phase out third-party cookies would result in those cookies no longer being sent as is in cross-site contexts.
```

2022-07-27 13:21 UTC, mihajlija approved these changes

2022-07-27 15:12 UTC, heyawhite approved these changes
Will commit some small changes and merge

2022-07-27 15:12 UTC, heyawhite commented on site/en/docs/privacy-sandbox/faq/index.md
> +### Does `SameSite` become irrelevant after the third-party cookie deprecation?
```suggestion
### Will `SameSite` become irrelevant after third-party cookies are deprecated?
```

2022-07-27 15:12 UTC, heyawhite commented on site/en/docs/privacy-sandbox/faq/index.md
> + - The exception to this is cookies that are modified by either the [CHIPS](https://developer.chrome.com/docs/privacy-sandbox/chips/) or [First-Party Sets](https://developer.chrome.com/docs/privacy-s
```suggestion
 - `SameSite=Lax` is the current default. While it does not strictly *need* to be included, it's good practice to specify it for cross-browser consistency.
 - `SameSite=Strict` continues to be a more restrictive option, for cookies that must only be sent when the user is already on the site. This is and remains a good security practice for cookies that are part of managing particularly sensitive access.
 - `SameSite=None` should continue to be sent for cross-browser consistency. However, Chrome's proposed change to phase out third-party cookies would result in those cookies no longer being sent as is in cross-site contexts.

The exception is cookies that are modified by either the [CHIPS](https://developer.chrome.com/docs/privacy-sandbox/chips/) or [First-Party Sets](https://developer.chrome.com/docs/privacy-sandbox/first-party-sets/) proposal. These allow for a subset of cross-site use cases. As these proposals are under active discussion, the final formats and functionality may change.
```

2022-07-27 15:16 UTC, heyawhite commented on site/en/docs/privacy-sandbox/faq/index.md
> +The exception is cookies that are modified by either the [CHIPS](https://developer.chrome.com/docs/privacy-sandbox/chips/) or [First-Party Sets](https://developer.chrome.com/docs/privacy-sandbox/firs
```suggestion
The exception is cookies that are modified by either the
[CHIPS](/docs/privacy-sandbox/chips/) or
[First-Party Sets](/docs/privacy-sandbox/first-party-sets/) proposal.
These allow for a subset of cross-site use cases. As these proposals are
under active discussion, the final formats and functionality may change.
```

2022-07-27 18:17 UTC, merged