[devtools-translate] Portuguese - What's New in DevTools (Chrome 97) #1708
GoogleChrome/developer.chrome.com pull request #1814
Opened 2021-12-05 04:27 UTC by alvarocamillont

Fixes #1708

Changes proposed in this pull request:

    Add portuguese translations for What's New in DevTools M97

2021-12-05 11:40 UTC, khaosdoctor requested changes

2021-12-05 11:40 UTC, khaosdoctor commented on site/pt/blog/new-in-devtools-97/index.md
> +Por exemplo, você pode registrar o processo de checkout do café com este aplicativo [demonstração de pedido de café](https://coffee-cart.netlify.app/). Depois de adicionar um café e preencher os deta
```suggestion
Por exemplo, vamos usar o aplicativo [demonstração de pedido de café](https://coffee-cart.netlify.app/), você pode registrar o processo de checkout do café. Depois de adicionar um café e preencher os detalhes do pagamento, você pode encerrar a gravação, repetir o processo ou clicar no botão **Medir desempenho** para medir o fluxo do usuário no painel **Desempenho**.
```

2021-12-06 00:53 UTC, alvarocamillont commented on site/pt/blog/new-in-devtools-97/index.md
> +Por exemplo, você pode registrar o processo de checkout do café com este aplicativo [demonstração de pedido de café](https://coffee-cart.netlify.app/). Depois de adicionar um café e preencher os deta
Done

2021-12-06 02:48 UTC, chybie approved these changes

2021-12-06 02:48 UTC, merged