[devtools-translate] Russian - What's New in DevTools (Chrome 97)
GoogleChrome/developer.chrome.com pull request #1817
Opened 2021-12-06 09:10 UTC by solarrust

Fixes #1783 

Hi! 

@kateryna-prokopenko @webmaxru notes for you:
- Recorder panel don't have Russian translation right now in DevTools. So I didn't translate this name for now.
- Is «автокомплит» fairly self-explanatory term already? Or do we still have to use «автодополнение»?
- I use «панели инструментов устройства» as translation for Device Mode. This phrase is used in DevTools right now. May be you have more elegant shape =)

2021-12-12 22:14 UTC, webmaxru requested changes

2021-12-12 22:14 UTC, webmaxru commented on site/ru/blog/new-in-devtools-97/index.md
> +Эта настройка облегчает работу на разных устройствах. Например, следующие настройки внешнего вида
```suggestion
Эта функция облегчает работу на разных устройствах. Например, следующие настройки внешнего вида
```

2021-12-12 22:14 UTC, webmaxru commented on site/ru/blog/new-in-devtools-97/index.md
> +синхронизированы и ваш пользовательский опыт на разных устройствах будет консистентным, вам не нужно
```suggestion
могут быть синхронизированы, так что ваш пользовательский опыт на разных устройствах будет консистентным без необходимости
```

2021-12-12 22:14 UTC, webmaxru commented on site/ru/blog/new-in-devtools-97/index.md
> +заново настраивать те же настройки.
```suggestion
настраивать эти параметры заново.
```

2021-12-12 22:14 UTC, webmaxru commented on site/ru/blog/new-in-devtools-97/index.md
> +Пожалуйста, поделитесь с нами любым фидбэком [здесь](https://crbug.com/1245541).
```suggestion
Ждем ваши отзывы [здесь](https://crbug.com/1245541).
```

2021-12-13 08:38 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-97/index.md
> +закончить запись, проиграть её с начала или кликнуть на кнопку **Measure performance** для просмотра пользовательских данных в панели **Производительность** (Performance).
```suggestion
закончить запись, воспроизвести её сначала или кликнуть на кнопку **Measure performance** для просмотра пользовательских данных во вкладке **Производительность** (Performance).
```

2021-12-13 08:38 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-97/index.md
> +Обратитесь к [документации](/docs/devtools/recorder/) по панели **Recorder** чтобы узнать больше с пошаговыми туториалами.
```suggestion
Обратитесь к [документации](/docs/devtools/recorder/) по вкладке **Recorder**, чтобы узнать больше из пошагового руководства.
```

2021-12-13 08:38 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-97/index.md
> +Функция **Recorder** находится в раннем доступе. Наша команда все ещё активно работает над ней, и мы ждем [ваши отзывы](https://goo.gle/recorder-feedback) для дальнейших улучшений.
```suggestion
Вкладка **Recorder** находится в раннем доступе. Наша команда все ещё активно работает над ней, и мы ждем [ваши отзывы](https://goo.gle/recorder-feedback) для дальнейших улучшений.
```

2021-12-13 08:38 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-97/index.md
> +{% Img src="image/dPDCek3EhZgLQPGtEG3y0fTn4v82/3EpVa15PtbhFwwszqyWF.png", alt="Панель Recorder", width="800", height="540" %}
```suggestion
{% Img src="image/dPDCek3EhZgLQPGtEG3y0fTn4v82/3EpVa15PtbhFwwszqyWF.png", alt="Вкладка Recorder", width="800", height="540" %}
```

2021-12-13 08:38 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-97/index.md
> +Номера колонок добавлены в вывод ошибки в Консоли (Console). Простой доступ к номеру колонки
```suggestion
В вывод ошибки в Консоли (Console) теперь добавлены номера колонок. Простой доступ к номеру колонки
```

2021-12-13 08:38 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-97/index.md
> +Ваши настройки DevTools теперь синхронизируются между устройствами когда вы включаете синхронизацию
```suggestion
Ваши настройки DevTools теперь синхронизируются между устройствами, когда вы включаете синхронизацию
```

2021-12-13 08:46 UTC, kateryna-prokopenko commented
Hi Alena!
I guess it's fine not to translate the Recorder panel name for now.
Автодополнение still sounds better.
It's best to use the names that are used in DevTools even if these don't sound super elegant:)
Thanks!

2021-12-13 10:12 UTC, solarrust commented
@webmaxru @kateryna-prokopenko apply all your suggestions, thank you! 🙏

2021-12-13 12:44 UTC, kateryna-prokopenko reviewed
Sorry, several more comments. In general, panel/tab should be translated as вкладка and only pane as панель, thanks!

2021-12-13 12:44 UTC, kateryna-prokopenko commented on site/_includes/partials/devtools/ru/whats-new.md
> +* [Ранний доступ: новая панель Recorder](/ru/blog/new-in-devtools-97/#recorder)
```suggestion
* [Ранний доступ: новая вкладка Recorder](/ru/blog/new-in-devtools-97/#recorder)
```

2021-12-13 12:44 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-97/index.md
> +## Ранний доступ: новая панель Recorder  {: #recorder }
```suggestion
## Ранний доступ: новая вкладка Recorder  {: #recorder }
```

2021-12-13 12:44 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-97/index.md
> +Используйте новую панель **Recorder**, чтобы записать, воспроизвести или измерить
```suggestion
Используйте новую вкладку **Recorder**, чтобы записать, воспроизвести или измерить
```

2021-12-13 12:44 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-97/index.md
> +закончить запись, воспроизвести её сначала или кликнуть на кнопку **Measure performance** для просмотра пользовательских данных в панели **Производительность** (Performance).
```suggestion
закончить запись, воспроизвести её сначала или кликнуть на кнопку **Measure performance** для просмотра пользовательских данных во вкладке **Производительность** (Performance).
```

2021-12-13 12:44 UTC, kateryna-prokopenko commented on site/ru/blog/new-in-devtools-97/index.md
> +Обратитесь к [документации](/docs/devtools/recorder/) по панели **Recorder**, чтобы узнать больше из пошагового руководства.
```suggestion
Обратитесь к [документации](/docs/devtools/recorder/) по вкладке **Recorder**, чтобы узнать больше из пошагового руководства.
```

2021-12-13 12:45 UTC, solarrust commented
@kateryna-prokopenko done, thank you!

2021-12-14 12:58 UTC, kateryna-prokopenko approved these changes

2021-12-14 12:58 UTC, merged