Update the UA reduction origin trial blog post
GoogleChrome/developer.chrome.com pull request #1916
Opened 2022-01-07 14:36 UTC by abeyad

Includes a note that the origin trial does not apply to the WebView and iOS platforms.

2022-01-07 19:18 UTC, heyawhite requested changes

2022-01-07 19:18 UTC, heyawhite commented on site/en/blog/user-agent-reduction-origin-trial/index.md
> +Note that the User-Agent reduction plans do not currently include iOS and WebView;
```suggestion
The User-Agent reduction plans do not currently include iOS and WebView, therefore
```

2022-01-07 19:18 UTC, heyawhite commented on site/en/blog/user-agent-reduction-origin-trial/index.md
> +[client hints](https://wicg.github.io/client-hints-infrastructure/).
> These platforms have not yet implemented
> [User-Agent Client Hints](https://wicg.github.io/client-hints-infrastructure/).

2022-01-07 20:34 UTC, abeyad commented on site/en/blog/user-agent-reduction-origin-trial/index.md
> +[client hints](https://wicg.github.io/client-hints-infrastructure/).
Done

2022-01-07 20:34 UTC, abeyad commented
PTAL, thanks!

2022-01-10 14:24 UTC, heyawhite approved these changes

2022-01-10 14:25 UTC, merged