Update index.md
GoogleChrome/developer.chrome.com pull request #1957
Opened 2022-01-14 13:57 UTC by Florian-COLLIN

Changes proposed in this pull request:

- Added storage permission for the Google Chrome extension options section.

2022-01-15 01:45 UTC, dotproto commented
@Florian-COLLIN, in order for us to accept this change you will need to sign the Contributor License Agreement (CLA). See [this build error](https://github.com/GoogleChrome/developer.chrome.com/pull/1957/checks?check_run_id=4817656009) for details.

2022-01-15 08:50 UTC, Florian-COLLIN commented
Normally it's good. 

Regards, 

Florian COLLIN

2022-01-26 17:20 UTC, dotproto requested changes
Tweak framing and code sample.

2022-01-26 17:20 UTC, dotproto commented on site/en/docs/extensions/mv3/options/index.md
> +```json/3
```suggestion
```json/4
```

Highlight the "storage" permission in the code block.

2022-01-26 17:20 UTC, dotproto commented on site/en/docs/extensions/mv3/options/index.md
> +For this to work, you must add in the `manifest.json`:
```suggestion
Finally, add the `"storage"` permission to the extension's `manifest.json`:
```

2022-01-27 00:40 UTC, dotproto approved these changes

2022-01-27 01:37 UTC, merged