Translate new-in-devtools-98 in Japanese
GoogleChrome/developer.chrome.com pull request #1966
Opened 2022-01-16 10:02 UTC by lacolaco

2022-01-16 10:06 UTC, lacolaco commented
@yoichiro @technohippy Could you review this translation?

2022-01-16 11:18 UTC, technohippy commented
I will👍

2022-01-16 21:09 UTC, yoichiro requested changes
@lacolaco I posted two comments. Could you confirm them?

2022-01-16 21:09 UTC, yoichiro commented on site/ja/blog/new-in-devtools-98/index.md
> +## Changesタブでより正確な変更点 {: #changes }
ここでの `precise` の意味は「正確な、正しい」よりも「詳細な、わかりやすい」というニュアンスかなと思います。複数行表示されて、ハイライトなどの書式が適用されることで「今までよりもわかりやすくなる」という変更かなと。

```suggestion
## Changesタブで変更点のよりわかりやすい表示 {: #changes } 
```

2022-01-16 21:09 UTC, yoichiro commented on site/_includes/partials/devtools/ja/whats-new.md
> +* [Changesタブでより正確な変更点](/ja/blog/new-in-devtools-98/#changes)
下のコメントを参照ください。

```suggestion
* [Changesタブで変更点のよりわかりやすい表示](/ja/blog/new-in-devtools-98/#changes)
```

2022-01-22 02:51 UTC, technohippy commented
英単語の前後に半角空白入れるって話はなくなったんでしたっけ？私は入れない派ですけど、入れるって話になっていたような。

2022-01-22 03:41 UTC, technohippy commented
余裕があれば画像のaltも訳したほうがいいと思います

2022-01-22 03:43 UTC, technohippy commented on site/ja/blog/new-in-devtools-98/index.md
> +[Recorder](/docs/devtools/recorder/)で、全ステップまたは特定のステップの**タイムアウト**の設定を調整できるようになりました。これは、特に遅いネットワークリクエストや長いアニメーションがあるページで便利です。
めちゃ細かいですけど
「特に遅いネットワークリクエストや長いアニメーションがあるページで便利です」
より
「遅いネットワークリクエストや長いアニメーションがあるページで特に便利です」
の方が「特に」のかかり先が明確になります。

2022-01-22 03:43 UTC, technohippy commented on site/ja/blog/new-in-devtools-98/index.md
> +例えば、この[デモページ](https://jec.fyi/demo/pup-slow-result)で、メニュー項目をロードしてクリックするまでの[ユーザーフローを記録](/docs/devtools/recorder/#record)してみました。しかし、メニュー項目の読み込みが遅いです(6秒かかる)。このユーザーフローの[リプレイ](/docs/devtools/recorder/#rep
こんな感じでどうでしょう。

しかし、メニュー項目の読み込みに時間がかかり(6秒)、このユーザーフローの[リプレイ](/docs/devtools/recorder/#replay)はデフォルトのタイムアウト（5秒）を超えるため失敗します。

- 遅いです：「－い + です」はちょっと話し言葉っぽいのでできれば避けたほうがよさそう
- うまく日本語にならないときに二文を一文にまとめたり、逆に分割するのおすすめです

2022-01-22 03:43 UTC, technohippy commented on site/ja/blog/new-in-devtools-98/index.md
> +特定のページをテストするには、Chromeでそのページに移動し、DevToolsで**Application** > **Back-forward Cache**に移動してください。次に、**Test back/forward cache** ボタンをクリックすると、DevToolsはページを離れて戻ろうと試み、bfcacheから復元できるかどうかを判断します。
「ページを離れて戻ろうと試み」
は
「ページをいったん離れた後で戻ろうと試み」
でどうでしょう

2022-01-22 03:43 UTC, technohippy commented on site/ja/blog/new-in-devtools-98/index.md
> +要素のidが一意でないことは一般的なアクセシビリティ上の問題です。例えば、`aria-labelledby`属性で参照されるidが[複数の要素](https://web.dev/duplicate-id-aria/)で使用されていることがあります。
一般的な → よくある
くらいでどうでしょう

2022-01-22 05:55 UTC, lacolaco commented
apply suggestions from reviews

2022-01-22 12:07 UTC, lacolaco commented
@technohippy @yoichiro コメントいただいた部分アップデートしたので再確認お願いします！

2022-01-22 12:12 UTC, technohippy commented
LGTM

2022-01-22 23:16 UTC, yoichiro commented
@lacolaco LGTM. Thanks!

2022-01-23 01:36 UTC, lacolaco commented
@chybie Ready to ship!

2022-01-24 02:02 UTC, chybie approved these changes

2022-01-24 02:03 UTC, chybie commented
どうもありがとう！

2022-01-24 02:03 UTC, merged