Japanese translation for DevTools 99
GoogleChrome/developer.chrome.com pull request #2186
Opened 2022-02-26 15:34 UTC by technohippy

https://developer.chrome.com/blog/new-in-devtools-99/

2022-02-28 10:14 UTC, chybie requested changes

2022-02-28 11:49 UTC, technohippy commented on site/ja/blog/new-in-devtools-99/index.md
>  draft: true
done

2022-02-28 12:04 UTC, chybie commented
Arigatou @technohippy! Tagging @yoichiro and @lacolaco for review.

2022-02-28 14:09 UTC, lacolaco commented on site/_includes/partials/devtools/ja/whats-new.md
> +* [その他のハイライト](/ja/blog/new-in-devtools-99/#misc) -->
```suggestion
* [その他のハイライト](/ja/blog/new-in-devtools-99/#misc)
```

2022-02-28 14:19 UTC, lacolaco reviewed
特に違和感なかったです LGTM 👍

2022-03-02 11:01 UTC, yoichiro commented on site/ja/blog/new-in-devtools-99/index.md
>  {% Img src="image/dPDCek3EhZgLQPGtEG3y0fTn4v82/6Lu7Js1rgSmjV0cnhDlH.png", alt="console styling", width="800", height="547" %}
```suggestion
{% Img src="image/dPDCek3EhZgLQPGtEG3y0fTn4v82/6Lu7Js1rgSmjV0cnhDlH.png", alt="コンソールスタイル設定", width="800", height="547" %}
```

2022-03-03 14:08 UTC, technohippy commented
@lacolaco @yoichiro レビューありがとうございました。全部取り込みました。

2022-03-04 01:55 UTC, chybie approved these changes

2022-03-04 01:57 UTC, chybie commented
みんなありがとう!

2022-03-04 01:57 UTC, merged