Clarify instructions for "Keeping a consistent key"
GoogleChrome/developer.chrome.com pull request #2274
Opened 2022-03-10 16:39 UTC by AmySteam

Changes proposed in this pull request:

- Clarify instructions for "Keeping a consistent ID" partial

2022-03-15 18:14 UTC, dotproto reviewed
Mostly nits. Once these are cleaned up I think we're ready to tag in Joe.

2022-03-15 18:14 UTC, dotproto commented on site/_includes/partials/extensions/reusing-prod-extension-id.md
> +2.  Click **Browse files**, select the extension `zip` file, and upload it.
```suggestion
2.  Click **Browse files**, select the extension's `zip` file, and upload it.
```

2022-03-15 18:14 UTC, dotproto commented on site/_includes/partials/extensions/reusing-prod-extension-id.md
> +alt="Developer Dashboard Package tab", width="296", height="121" %}
```suggestion
alt="Developer Dashboard Package tab", width="296", height="121", class="screenshot" %}
```

Add the "screenshot" class to surround the image with an outline.

2022-03-15 18:14 UTC, dotproto commented on site/_includes/partials/extensions/reusing-prod-extension-id.md
> +width="500", height="233" %}
```suggestion
width="500", height="233", class="screenshot" %}
```

Add the "screenshot" class to surround the image with an outline.

2022-03-15 18:14 UTC, dotproto commented on site/_includes/partials/extensions/reusing-prod-extension-id.md
>  extension match", width="356", height="352" %}
```suggestion
extension match", width="356", height="352", class="screenshot" %}

```

Add the "screenshot" class to surround the image with an outline. Also, the file should end with a blank line. See [this SO answer](https://stackoverflow.com/a/729795/4959520) for more info.

2022-03-15 20:03 UTC, AmySteam commented
@jpmedley This PR is ready for an editorial review, thanks!

2022-03-23 22:02 UTC, dotproto approved these changes
LGTM

2022-03-23 22:09 UTC, dotproto commented
@jpmedley, this is ready for you

2022-03-25 14:44 UTC, jpmedley requested changes

2022-03-25 14:44 UTC, jpmedley commented on site/_includes/partials/extensions/reusing-prod-extension-id.md
> +This way the extension will maintain the same ID.
```suggestion
This way the extension will use the same ID.
```

2022-03-28 15:52 UTC, jpmedley approved these changes

2022-03-28 15:52 UTC, merged