ContentMigrationBatch#S32
GoogleChrome/developer.chrome.com pull request #2340
Opened 2022-03-18 15:20 UTC by simgobb

https://developers.google.com/web/updates/2012/06/How-to-convert-ArrayBuffer-to-and-from-String
https://developers.google.com/web/updates/2012/07/Arrived-xhr-send-ArrayBufferView
https://developers.google.com/web/updates/2012/07/Drag-and-drop-a-folder-onto-Chrome-now-available
https://developers.google.com/web/updates/2012/07/How-to-measure-browser-graphics-performance
https://developers.google.com/web/updates/2012/07/Taking-advantage-of-GPU-acceleration-in-the-2D-canvas

@rachelandrew

2022-03-18 16:02 UTC, rachelandrew requested changes

2022-03-18 16:02 UTC, rachelandrew commented on site/en/blog/how-to-measure-browser-graphics-performance/index.md
> +Benchmarking browser graphics in a nutshell: draw as much as you can while maintaining a smooth frame rate. Once your framerate drops, you know how much you can draw per frame. End of post. ...No? Ok
```suggestion
Benchmarking browser graphics in a nutshell: draw as much as you can while maintaining a smooth frame rate. Once your framerate drops, you know how much you can draw per frame. End of post. No? Ok, I'll explain some more.
```

2022-03-18 16:02 UTC, rachelandrew commented on site/en/blog/how-to-measure-browser-graphics-performance/index.md
> +Different graphics applications have different needs, so you should write your benchmarks with that in mind. Measure the graphics features that you are using in your app. When you find a slow scenari
```suggestion
Different graphics applications have different needs, so you should write your benchmarks with that in mind. Measure the graphics features that you are using in your app. When you find a slow scenario, try to reduce it down to the smallest piece of code that reproduces it (and file a bug report at [new.crbug.com](https://new.crbug.com] if it should be faster.)
```

2022-03-18 17:28 UTC, simgobb commented
@rachelandrew I have noticed that the PR linting is failing on the URL that got changed on the last review. Not sure what's wrong though. Looks formatted correctly?

2022-03-21 07:25 UTC, rachelandrew commented on site/en/blog/how-to-measure-browser-graphics-performance/index.md
> +Different graphics applications have different needs, so you should write your benchmarks with that in mind. Measure the graphics features that you are using in your app. When you find a slow scenari
```suggestion
Different graphics applications have different needs, so you should write your benchmarks with that in mind. Measure the graphics features that you are using in your app. When you find a slow scenario, try to reduce it down to the smallest piece of code that reproduces it (and file a bug report at [new.crbug.com](https://new.crbug.com) if it should be faster.)
```

2022-03-21 07:25 UTC, rachelandrew requested changes
the problem was an incorrect bracket, I've changed it and I think that should now pass the linter if you commit that.

2022-03-21 07:39 UTC, rachelandrew approved these changes

2022-03-21 07:39 UTC, merged