Update devnook.md
GoogleChrome/developer.chrome.com pull request #2532
Opened 2022-04-04 18:27 UTC by devnook

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

2022-04-05 19:34 UTC, jpmedley commented
Do you need me to do something with this?

2022-04-07 07:48 UTC, tomayac requested changes
Getting there.

2022-04-07 07:48 UTC, tomayac commented on site/en/devnook.md
> -Devnook test 2
This should be 5.

2022-04-07 13:24 UTC, jeffposnick approved these changes
Tom doesn't know what he's talking about. This PR is ace.

2022-04-11 12:48 UTC, devnook commented
comment

2022-04-11 12:53 UTC, devnook commented
comment

2023-02-13 09:37 UTC, closed without merging