Switch to a Rust-based HTML & inline CSS/JS minifier
GoogleChrome/developer.chrome.com pull request #2555
Opened 2022-04-08 17:04 UTC by jeffposnick

Switching away from `html-minifier` and `csso` in favor of `@minify-html/js` leads to production builds that are around 33% faster on my M1 Macbook.

I'm not sure what the corresponding speedup will be in the production deployment, but if web.dev was any indication, it should be meaningfully faster.

That being said, we have run into a number of issues with this HTML minifier when used on web.dev because it treats invalid HTML differently than `html-minifier` did. We need to keep an eye out for any reports of issues with HTML rendering on the production site following this deployment.

2022-04-19 07:37 UTC, devnook requested changes
testing approvals

2022-04-19 07:42 UTC, devnook approved these changes

2022-04-25 18:01 UTC, jeffposnick commented on site/_includes/layouts/base.njk
> +    <link rel="preload" as="font" crossorigin="anonymous" href="/fonts/google-sans-v2003/regular/latin.woff2">
See https://github.com/GoogleChrome/web.dev/pull/7790

2022-05-25 11:19 UTC, devnook approved these changes

2022-05-25 11:20 UTC, devnook approved these changes

2022-06-15 16:05 UTC, jeffposnick commented
I'm going to do a one-off run of an HTML analyzer on the minifier output before we merge this, just to get a gauge for how broken things might be.

2022-07-20 20:30 UTC, jeffposnick commented
Actually, this is using an older version of the HTML minifier. See https://github.com/GoogleChrome/web.dev/issues/8381

2022-10-19 09:34 UTC, matthiasrohmer commented
Since the API of @minify-html/node changed quite a bit since this implementation, closing this and tracking further in #4048.

2022-10-19 09:34 UTC, closed without merging