DevTools: Rendering feature reference
GoogleChrome/developer.chrome.com pull request #2567
Opened 2022-04-11 14:58 UTC by sofiayem

Fixes #2544 
Fixed #2543 

Wanted to document the [Auto Dark theme](https://developer.chrome.com/blog/new-in-devtools-99/#auto-dark-mode) but the entire Rendering tab was undocumented.

So, documented the Rendering tab.

2022-04-12 05:27 UTC, jecfish requested changes

2022-04-12 05:27 UTC, jecfish commented on site/en/docs/devtools/rendering/index.md
> +To emulate a focused page:
Can improve on the example as the effect is not obvious.A dropdown example is better or a demo video. 

Refer to demo at 2:00. https://portal.gitnation.org/contents/debugging-with-chrome-devtools

2022-04-12 05:27 UTC, jecfish commented on site/en/docs/devtools/rendering/index.md
> +1.  Open the **Rendering** tab](#open-rendering) and under **Emulate CSS media type** select **print**.
broken link

2022-04-12 05:27 UTC, jecfish commented on site/en/docs/devtools/rendering/index.md
> +1. [Open the **Rendering** tab](#open-rendering) on the [demo page](https://prefers-reduced-motion.glitch.me/) and try scrolling to see various animations.
Probably can create an easier demo here right in the page:
- e,g. https://jec.fyi/demo/prefers-reduced-motion, or
- a box with hover effect (e.g. https://jec.fyi/demo/css-grid-cq-cascade-2): -
    - no preference: transform bigger
    - reduced: only highlight the border

2022-04-12 05:27 UTC, jecfish commented on site/en/docs/devtools/rendering/index.md
> +1. Under the **Emulate CSS media feature `color-gamut`**, select one of the following from the dropdown list:
incorrect media feature

2022-04-12 05:27 UTC, jecfish commented on site/en/docs/devtools/rendering/index.md
> +   - Protanopia—can't perceive red and green colors
Inconsistent options styles. Do we not bold / bold the options or use back tick?

2022-04-12 05:27 UTC, jecfish commented on site/en/docs/devtools/rendering/index.md
> +
Include resource to read further: https://developer.chrome.com/blog/cvd/

2022-04-12 05:27 UTC, jecfish commented on site/en/docs/devtools/rendering/index.md
> +## Disable AVIF image format
provide example and use case, e.g. https://twitter.com/jecfish/status/1504658919003615240

2022-04-12 10:42 UTC, sofiayem commented
> Performance related emulation
> CSS media features emulation
> Others

So, I assume the the "Emulate a focused page" should go into "Others" then. Then the reader is gonna have to guess that the focused-related checkbox is in Rendering > Others in table of contents. It's not easy to do so.

But let me think about it more.

2022-04-12 10:43 UTC, sofiayem commented on site/en/docs/devtools/css/print-preview/index.md
> -layout: "layouts/doc-post.njk"
Riiight. Forgot about it. Thank you for catching this.

2022-04-13 13:25 UTC, jecfish commented on site/en/docs/devtools/rendering/apply-effects/index.md
> +1. [Open the **Rendering** tab](/docs/devtools/rendering#open-rendering)  on this [demo ](https://heavy-ads.glitch.me/) and check **Highlight ad frames**.
```suggestion
1. [Open the **Rendering** tab](/docs/devtools/rendering#open-rendering) on this [demo](https://heavy-ads.glitch.me/) and check **Highlight ad frames**.
```

2022-04-20 10:47 UTC, jecfish approved these changes

2022-04-20 11:19 UTC, merged