Feat/translate chrome 101 changelog spanish
GoogleChrome/developer.chrome.com pull request #2599
Opened 2022-04-14 09:03 UTC by midudev

Fixes #2578

Changes proposed in this pull request:

- Add Spanish translation for Chrome 101 changes articles.

2022-04-14 09:19 UTC, midudev commented
Nothing I could do regarding linter problems as they're from the original content.

Sorry for the mess with the commit history. 😅

2022-04-20 22:38 UTC, jecfish commented
Thanks @midudev! Over to @Caballerog for review.

2022-04-20 22:38 UTC, jecfish requested changes

2022-04-20 22:38 UTC, jecfish commented on site/es/blog/new-in-devtools-101/index.md
>  draft: true
remove draft
```suggestion

```

2022-04-22 02:31 UTC, jecfish commented on site/es/blog/new-in-devtools-101/index.md
```suggestion

{% YouTube id='u9GRAliBrM8' %}
```

2022-04-24 20:21 UTC, Caballerog reviewed
I have only found two small errors. The rest of the translation is really good!

2022-04-24 20:21 UTC, Caballerog commented on site/es/blog/new-in-devtools-101/index.md
> +- **Exportar como un script de @puppeteer/replay**. Descargue la grabación como un script de [Puppeteer Replay](
The link is missing: 
[Puppeteer Replay](https://github.com/puppeteer/replay)

2022-04-24 20:21 UTC, Caballerog commented on site/es/blog/new-in-devtools-101/index.md
> +Cada mode tiene sus propios casos de uso, beneficios y limitaciones. Por favor, consulte la [documentación de Lighthouse](https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md) pa
mode => "modo"

2022-04-24 21:27 UTC, Caballerog commented on site/es/blog/new-in-devtools-101/index.md
> +- **Exportar como un script de @puppeteer/replay**. Descargue la grabación como un script de [Puppeteer Replay](
Perfect!

2022-04-24 21:27 UTC, Caballerog commented on site/es/blog/new-in-devtools-101/index.md
> +Cada mode tiene sus propios casos de uso, beneficios y limitaciones. Por favor, consulte la [documentación de Lighthouse](https://github.com/GoogleChrome/lighthouse/blob/master/docs/user-flows.md) pa
Perfect!

2022-04-24 21:28 UTC, Caballerog commented
LGTM!

2022-04-25 09:41 UTC, jecfish approved these changes

2022-04-25 09:42 UTC, jecfish commented
Gracias both!

2022-04-25 09:42 UTC, merged