JA-translation-proposal-lifecycle
GoogleChrome/developer.chrome.com pull request #2659
Opened 2022-04-21 09:08 UTC by mattletford

Convert .docx to Markdown for JA translation of proposal lifecycle @agektmr

2022-04-21 09:12 UTC, agektmr commented
@mattletford I've indicated the destination path of the file in the Google Doc file. Could you please move it to the right place?

2022-04-21 09:13 UTC, agektmr commented
Oh you pushed the change at the same time. Never mind my previous message :)

2022-04-21 11:43 UTC, agektmr requested changes
Lots of avif resources from nowhere. Where are they come from?

2022-04-21 11:43 UTC, agektmr commented on site/ja/docs/privacy-sandbox/proposal-lifecycle/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/GUccejeZiolwdTSzwW0z.avif", alt="2019 年に PIGIN が提案され、2020 年に TURTLEDOVE、2021 年に FLEDGE が提案されました。", width="800", height="169" %}
```suggestion
{% Img src="image/VbsHyyQopiec0718rMq2kTE1hke2/Rg4lEQVzb1v6CZTyzFTE.png", alt="2019 年に PIGIN が提案され、2020 年に TURTLEDOVE、2021 年に FLEDGE が提案されました。", width="800", height="169" %}
```

2022-04-21 11:43 UTC, agektmr commented on site/ja/docs/privacy-sandbox/proposal-lifecycle/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/s6gTNVydmZZmGyivBClC.avif", alt="ALT_TEXT_HERE", width="800", height="368" %}
```suggestion
{% Img src="image/VbsHyyQopiec0718rMq2kTE1hke2/vTqicAx2UauzkePJkM0A.png", alt="ALT_TEXT_HERE", width="800", height="368" %}
```

2022-04-21 11:43 UTC, agektmr commented on site/ja/docs/privacy-sandbox/proposal-lifecycle/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/mgc6Yud6cv4sosrObMKD.avif", alt="たとえば、「User-Agent: Mozilla/5.0 (Linux; Android 10; Pixel 3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4076.0 Mo
```suggestion
{% Img src="image/VbsHyyQopiec0718rMq2kTE1hke2/AVzbV9HF0T0bm3buFjV6.jpg", alt="たとえば、「User-Agent: Mozilla/5.0 (Linux; Android 10; Pixel 3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4076.0 Mobile Safari/537.36」は非常に長く、フィンガープリントに使用される特定の詳細情報（デバイスの正確な機種、プラットフォームのバージョン、Chrome のバージョン全体など）を提供しています。", width="800", height="464" %}
```

2022-04-21 11:43 UTC, agektmr commented on site/ja/docs/privacy-sandbox/proposal-lifecycle/index.md
> +{% Img src="image/C47gYyWYVMMhDmtYSLOWazuyePF2/UCXrDoPE25iNA5cIEJWX.avif", alt="ALT_TEXT_HERE", width="800", height="339" %}
```suggestion
{% Img src="image/VbsHyyQopiec0718rMq2kTE1hke2/ZsumGF9jzVb5yYL4QD3i.png", alt="ALT_TEXT_HERE", width="800", height="339" %}
```

2022-04-21 11:56 UTC, agektmr requested changes

2022-04-21 11:56 UTC, agektmr commented on site/ja/docs/privacy-sandbox/proposal-lifecycle/index.md
> +
Line 9 to 15 are not part of the article. Please remove.

2022-04-21 11:56 UTC, agektmr commented on site/ja/docs/privacy-sandbox/proposal-lifecycle/index.md
> +## [プライバシー サンドボックスの提案の目的](/docs/privacy-sandbox/proposal-lifecycle/#what-is-the-goal-of-the-privacy-sandbox-proposals)
This link is not necessary. Please try to replicate the English version as much as possible. Other headers as well.

2022-04-22 15:07 UTC, mattletford commented
I've applied the suggestions @agektmr

2022-04-25 10:27 UTC, agektmr commented on site/ja/docs/privacy-sandbox/proposal-lifecycle/index.md
> -## [プライバシー サンドボックスの提案の目的](/docs/privacy-sandbox/proposal-lifecycle/#what-is-the-goal-of-the-privacy-sandbox-proposals)
This shouldn't be removed.

2022-04-25 10:27 UTC, agektmr commented on site/ja/docs/privacy-sandbox/proposal-lifecycle/index.md
> +## [プライバシー サンドボックスの提案の目的](/docs/privacy-sandbox/proposal-lifecycle/#what-is-the-goal-of-the-privacy-sandbox-proposals)
This comment still stands. Please go over all headings, comparing with the English version and remove links where necessary.

2022-04-25 10:28 UTC, agektmr commented on site/ja/docs/privacy-sandbox/proposal-lifecycle/index.md
> +## [プライバシー サンドボックスの提案の目的](/docs/privacy-sandbox/proposal-lifecycle/#what-is-the-goal-of-the-privacy-sandbox-proposals)
What I meant is, to remove the link not to remove the heading itself.

2022-04-25 10:57 UTC, mattletford commented
@agektmr thanks, I've removed the links from the headings

2022-04-25 11:39 UTC, agektmr approved these changes
LGTM

2022-04-25 12:50 UTC, heyawhite approved these changes

2022-04-25 12:50 UTC, merged