JA-translation-fledge-experiment
GoogleChrome/developer.chrome.com pull request #2685
Opened 2022-04-25 10:29 UTC by mattletford

JA translation of fledge experiment

2022-04-25 13:29 UTC, mattletford commented
> This is wrong. Why did you copy / paste from older version of another article? Here's the source doc expected to be converted from: https://docs.google.com/document/d/13awsSXNqncHVoX4KD9-Bnbh3_qENlSveeFxAhXJFO54/edit?resourcekey=0-xMucu0lRrTA4Oe_uy3MqFw

Thank you, I've updated to the new doc

2022-04-26 02:38 UTC, agektmr requested changes

2022-04-26 02:38 UTC, agektmr commented on site/ja/docs/privacy-sandbox/fledge-experiment/index.md
> +
```suggestion

{% Aside %}
API のテストをうまく進められない場合はご連絡ください。
{% endAside %}

```

2022-04-26 02:38 UTC, agektmr commented on site/ja/docs/privacy-sandbox/fledge-experiment/index.md
> +subhead: リマーケティングに活用できるソリューションです。このソリューションは、第三者がサイト間のユーザーの閲覧行動を追跡できないように設計されています。
```suggestion
subhead: FLEDGE はプライバシー サンドボックスの提案で、リマーケティングとカスタム オーディエンスに利用することができますが、第三者がサイト間のユーザーの閲覧行動を追跡できないように設計されています。
```

2022-04-26 02:38 UTC, agektmr commented on site/ja/docs/privacy-sandbox/fledge-experiment/index.md
> +description: FLEDGE はリマーケティングに活用可能でありながら、第三者がサイト間のユーザーの閲覧行動を追跡できないように設計されています。この API を使用すると、ユーザーが以前にアクセスした Web サイトが提供する関連広告を選択するためのブラウザーによるデバイス上の「オークション」を実現できます。
```suggestion
description: FLEDGE はプライバシー サンドボックスの提案で、リマーケティングとカスタム オーディエンスに利用することができますが、第三者がサイト間のユーザーの閲覧行動を追跡できないように設計されています。この API は、ユーザーが以前にアクセスした Web サイトが提供する関連広告を選択するための、ブラウザーによるデバイス上の「オークション」を実現します。
```

2022-04-26 08:13 UTC, mattletford commented
@agektmr I've applied the suggested changes

2022-04-26 18:08 UTC, agektmr requested changes

2022-04-27 08:58 UTC, mattletford commented
@agektmr I've applied the suggested changes

2022-04-27 09:20 UTC, agektmr requested changes

2022-04-27 09:20 UTC, agektmr commented on site/ja/docs/privacy-sandbox/fledge-experiment/index.md
> +- この API に関する進行中のディスカッションすべてを常にチェックするには、[GitHub の提案ページ](https://github.com/WICG/turtledove/blob/main/FLEDGE.md)で ボタンをクリックしてください。なお、この操作を行うには GitHub > アカウントが必要です。お持ちでない場合は [GitHub アカウントを作成](https://do
```suggestion
- この API に関する進行中のディスカッションすべてを常にチェックするには、[GitHub の提案ページ](https://github.com/WICG/turtledove/blob/main/FLEDGE.md)で **Watch** ボタンをクリックしてください。なお、この操作を行うには GitHub > アカウントが必要です。お持ちでない場合は [GitHub アカウントを作成](https://docs.github.com/en/get-started/signing-up-for-github/signing-up-for-a-new-github-account)してください。
```

2022-04-27 09:24 UTC, mattletford commented
@agektmr I've applied the suggested changes

2022-04-27 09:40 UTC, merged