DevTools 98 > Accessibility > Full-page view
GoogleChrome/developer.chrome.com pull request #2695
Opened 2022-04-25 14:53 UTC by sofiayem

Documented https://developer.chrome.com/blog/new-in-devtools-98/#a11y-tree

2022-04-26 09:21 UTC, jecfish commented on site/en/docs/devtools/accessibility/reference/index.md
> +This view allows you to explore only a single node and its ancestors.
expand the description

2022-04-26 09:21 UTC, jecfish commented on site/en/docs/devtools/accessibility/reference/index.md
> +### (Preview) Explore the accessibility tree {: #explore-tree}
```suggestion
### (Preview) Explore the full-page accessibility tree {: #explore-tree}
```

2022-04-26 14:38 UTC, jeffposnick requested changes

2022-04-26 14:38 UTC, jeffposnick commented on site/en/docs/devtools/accessibility/reference/index.md
> +<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
Is the only icon used that `<span class="material-icons">accessibility</span>`?

My understanding is that icon fonts are generally not a great idea, as you end up making several network requests and downloading unused bytes for something that could be accomplished via alternative means.

I would recommend downloading and using an inline SVG from https://fonts.google.com/icons?selected=Material+Icons&icon.query=accessibility instead, if possible.

2022-04-27 13:09 UTC, sofiayem commented on site/en/docs/devtools/accessibility/reference/index.md
> +<link href="https://fonts.googleapis.com/icon?family=Material+Icons"
@jeffposnick Thank you for making me aware of that. (I was just following the [guide](https://developers.google.com/fonts/docs/material_icons#setup_method_1_using_via_google_fonts)). Will replace with an SVG shortly.

2022-04-27 13:48 UTC, jeffposnick approved these changes
Thanks for switching to SVGs!

2022-05-04 15:02 UTC, merged