[devtools-translate] Chinese - What's New in DevTools (Chrome 102)
GoogleChrome/developer.chrome.com pull request #2879
Opened 2022-05-23 22:58 UTC by hanselfmu

Fixes #[2804](https://github.com/GoogleChrome/developer.chrome.com/issues/2804)

2022-05-24 11:06 UTC, liuliangsir commented on site/zh/blog/new-in-devtools-102/index.md
> +[打开此面板](/docs/devtools/performance-insights/#open)并根据您的用例来开始一段新的录制。举个例子，让我们来测量这个[示例网页](https://coffee-cart.netlify.app/?ad=1)的页面加载。
> 让我们来测量这个[示例网页](https://coffee-cart.netlify.app/?ad=1)的页面加载

It might be a better addition when the sentence above is ending with `情况`

2022-05-24 11:09 UTC, liuliangsir commented on site/zh/blog/new-in-devtools-102/index.md
> +录制完成后，您会在 **Insights** 窗格中获得性能的深度分析。 单击每个深度分析项目（例如，阻止渲染的请求、布局偏移）以了解问题和潜在的修复。
> 录制完成后，您会在 **Insights** 窗格中获得性能的深度分析

It might a better choice with inserting `一份有关` followed by `性能`

2022-05-24 11:17 UTC, liuliangsir commented on site/zh/blog/new-in-devtools-102/index.md
> +前往 **Performance insights** 面板的[文档](/docs/devtools/performance-insights/)并通过逐步教程来了解更多。
> 并通过逐步教程来了解更多

`逐步教程` is rather rare and uncommon in daily work. Try `并通过教程来逐步了解更多有关内容`

2022-05-24 11:20 UTC, liuliangsir commented on site/zh/blog/new-in-devtools-102/index.md
> +利用 **Performance insights** 面板来获取关于您网站性能的可操作且由用例驱动的深度分析。
> 关于您网站性能的可操作且由用例驱动的深度分析

What is meaning of `可操作`

2022-05-24 11:25 UTC, liuliangsir commented on site/zh/blog/new-in-devtools-102/index.md
> +您现在可以在**样式**边栏中利用新的快捷方式更快速地模拟浅色和深色主题（CSS 媒体功能 [prefers-color-scheme](https://web.dev/prefers-color-scheme/#the-prefers-color-scheme-media-query)）。
Insert `来` followed by `更快速地`

2022-05-24 11:26 UTC, liuliangsir commented on site/zh/blog/new-in-devtools-102/index.md
> +DevTools 现在在**网络**面板中的**预览**标签页应用了内容安全政策（CSP）。
Remove `了`

2022-05-25 08:14 UTC, jecfish requested changes

2022-05-25 08:14 UTC, jecfish commented on site/zh/blog/new-in-devtools-102/index.md
> +利用 **Performance insights** 面板来获取关于您网站性能的可操作且由用例驱动的深度分析。
```suggestion
利用 **Performance insights** 面板来获取关于您网站性能的可行性深度分析。面板将按照您的用例提供可行性的建议和回馈。
```

2022-05-25 08:14 UTC, jecfish commented on site/zh/blog/new-in-devtools-102/index.md
> +[打开此面板](/docs/devtools/performance-insights/#open)并根据您的用例来开始一段新的录制。举个例子，让我们来测量这个[示例网页](https://coffee-cart.netlify.app/?ad=1)的页面加载。
```suggestion
[打开此面板](/docs/devtools/performance-insights/#open)并根据您的用例来开始一段新的录制。举个例子，让我们来测量这个[示例网页](https://coffee-cart.netlify.app/?ad=1)的页面加载情况。
```

2022-05-25 08:14 UTC, jecfish commented on site/zh/blog/new-in-devtools-102/index.md
> +录制完成后，您会在 **Insights** 窗格中获得性能的深度分析。 单击每个深度分析项目（例如，阻止渲染的请求、布局偏移）以了解问题和潜在的修复。
```suggestion
录制完成后，您会在 **Insights** 窗格中获得相关的性能深度分析。 单击每个深度分析项目（例如，阻止渲染的请求、布局偏移）以了解问题和潜在的修复。
```

2022-05-25 08:14 UTC, jecfish commented on site/zh/blog/new-in-devtools-102/index.md
> +前往 **Performance insights** 面板的[文档](/docs/devtools/performance-insights/)并通过逐步教程来了解更多。
```suggestion
前往 **Performance insights** 面板的[文档](/docs/devtools/performance-insights/)并通过教程来逐步了解更多内容。
```

2022-05-25 08:14 UTC, jecfish commented on site/zh/blog/new-in-devtools-102/index.md
> +您现在可以在**样式**边栏中利用新的快捷方式更快速地模拟浅色和深色主题（CSS 媒体功能 [prefers-color-scheme](https://web.dev/prefers-color-scheme/#the-prefers-color-scheme-media-query)）。
```suggestion
您现在可以在**样式**边栏中利用新的快捷方式来更快速地模拟浅色和深色主题（CSS 媒体功能 [prefers-color-scheme](https://web.dev/prefers-color-scheme/#the-prefers-color-scheme-media-query)）。
```

2022-05-25 08:14 UTC, jecfish commented on site/zh/blog/new-in-devtools-102/index.md
> +DevTools 现在在**网络**面板中的**预览**标签页应用了内容安全政策（CSP）。
```suggestion
**网络**面板中的**预览**标签页现在应用了内容安全政策（CSP）。
```

2022-05-25 08:14 UTC, jecfish commented on site/zh/blog/new-in-devtools-102/index.md
> +浏览器默认阻止了样式表请求。但是，当您通过**网络**面板中的**预览**标签页打开页面时，样式表此前并没有被阻止（因此背景变成了红色）。现在像您期望的那样，该样式表被阻止了（第二个屏幕截图）。
```suggestion
浏览器默认阻止样式表请求。但是，当您通过**网络**面板中的**预览**标签页打开页面时，样式表此前并没有被阻止（因此背景变成了红色）。现在像您期望的那样，该样式表被阻止了（第二个屏幕截图）。
```

2022-05-25 08:15 UTC, jecfish requested changes

2022-05-25 08:15 UTC, jecfish commented on site/zh/blog/new-in-devtools-102/index.md
> +## 其它亮点 {: #misc }
```suggestion
## 其它的更新 {: #misc }
```

2022-05-25 08:17 UTC, jecfish approved these changes

2022-05-25 08:29 UTC, merged