[JA] privacy-sandbox translations
GoogleChrome/developer.chrome.com pull request #3009
Opened 2022-06-14 08:53 UTC by ilyaspiridonov

Adds Japanese translations for
- [privacy-sandbox/feedback/report-2022-q1/](https://developer.chrome.com/docs/privacy-sandbox/feedback/report-2022-q1/)
- [docs/privacy-sandbox/fedcm/](https://developer.chrome.com/docs/privacy-sandbox/fedcm/)
Translated by Alconost

2022-06-14 08:56 UTC, ilyaspiridonov commented
CC: @agektmr

2022-06-16 05:40 UTC, agektmr requested changes
Some changes requested

2022-06-16 05:40 UTC, agektmr commented on site/ja/docs/privacy-sandbox/fedcm/index.md
> +以下の**すべて**の条件に該当する場合にのみ、FedCM が役立つことを期待しています。
```suggestion
以下の**すべて**の条件に該当する場合にのみ、FedCM が役立つと考えています。
```

2022-06-16 05:40 UTC, agektmr commented on site/ja/docs/privacy-sandbox/fedcm/index.md
> +*  承認プロンプト
```suggestion
*  認可プロンプト
```

2022-06-16 05:40 UTC, agektmr commented on site/ja/docs/privacy-sandbox/feedback/report-2022-q1.md
> +   <td>ブラウザはフェデレーション ID フローの一部をレンダリングするため、IdP がユーザーに提示したいと思うニュアンスをすべて把握するのは困難であるという懸念
```suggestion
   <td>ブラウザは ID 連携フローの一部をレンダリングするため、IdP がユーザーに提示したいと思うニュアンスをすべて把握するのは困難であるという懸念
```

2022-06-16 05:40 UTC, agektmr commented on site/ja/docs/privacy-sandbox/feedback/report-2022-q1.md
> +   <td>ブラウザが以前よりも ID フェデレーションフローに関与しているため、ユーザーがどのウェブサイトに（どの IDP を使って）ログインしているかをより明確に認識することが懸念されます。
```suggestion
   <td>ブラウザが以前よりも ID 連携フローに関与しているため、ユーザーがどのウェブサイトに（どの IDP を使って）ログインしているかをより明確に認識することが懸念されます。
```

2022-06-16 05:40 UTC, agektmr commented on site/ja/docs/privacy-sandbox/feedback/report-2022-q1.md
> +   <td>Chrome は、ブラウザがより積極的な役割を果たしていることを認識していますが、フェデレーションをサポートしながら、ブラウザがクロスサイトトラッキングを区別して防止するには、この追加レベルの関与が必要です。
```suggestion
   <td>Chrome は、ブラウザがより積極的な役割を果たしていることを認識していますが、ID 連携をサポートしながら、ブラウザがクロスサイトトラッキングを区別して防止するには、この追加レベルの関与が必要です。 
```

2022-06-16 05:40 UTC, agektmr commented on site/ja/docs/privacy-sandbox/feedback/report-2022-q1.md
> +   <td>Chrome は、FedID コミュニティグループでフェデレーションのための共通ソリューションを見つけるために、他のブラウザベンダーとの協力にも努めています。
```suggestion
   <td>Chrome は、FedID コミュニティグループで ID 連携のための共通ソリューションを見つけるために、他のブラウザベンダーとの協力にも努めています。 
```

2022-06-16 05:40 UTC, agektmr commented on site/ja/docs/privacy-sandbox/feedback/report-2022-q1.md
> +   <td>企業がフェデレーション ID の展開を変更せずに維持できるようにするコントロール（エンタープライズポリシーやユーザー設定など）が提供されるかどうかに関する懸念 再デプロイまたは変更が特別に困難であるフェデレーション ID のオンプレミスデプロイが多いため、IdP の再デプロイを必要とする新しいブラウザ API に対して多くの抵抗があります。
```suggestion
   <td>企業が ID 連携の展開を変更せずに維持できるようにするコントロール（エンタープライズポリシーやユーザー設定など）が提供されるかどうかに関する懸念 再デプロイまたは変更が特別に困難である ID 連携のオンプレミスデプロイが多いため、IdP の再デプロイを必要とする新しいブラウザ API に対して多くの抵抗があります。
```

2022-06-16 07:47 UTC, agektmr commented on site/ja/docs/privacy-sandbox/fedcm/index.md
> +  プライバシーを保護する ID フェデレーションのためのウェブ API。
@ilyaspiridonov please see the comment and address other similar cases.

2022-06-17 11:34 UTC, ilyaspiridonov commented
Hello @agektmr! My latest commit should accommodate all the requested changes - would you PTAL?

2022-06-18 03:34 UTC, agektmr requested changes
There are quite a few regressions. Please fix them.

2022-06-18 03:34 UTC, agektmr commented on site/ja/docs/privacy-sandbox/fedcm/index.md
> +_ID 連携_は、信頼できる外部パーティ（_ID プロバイダー_ または IdP）に個人（ユーザーまたはエンティティ）の認証または認可を委任します。 すると ID プロバイダーは、その個人のウェブサイト（_リライングパーティ_または RP）へのサインインを許可します。
```suggestion
_ID 連携_ は、信頼できる外部パーティ（_ID プロバイダー_ または IdP）に個人（ユーザーまたはエンティティ）の認証または認可を委任します。 すると ID プロバイダーは、その個人のウェブサイト（_リライングパーティ_ または RP）へのサインインを許可します。
```

2022-06-18 03:34 UTC, agektmr commented on site/ja/docs/privacy-sandbox/fedcm/index.md
> +*  承認プロンプト
This regressed.

2022-06-18 03:34 UTC, agektmr commented on site/ja/docs/privacy-sandbox/feedback/report-2022-q1.md
> +   <td>Chrome は、FedID コミュニティグループで連携のための共通ソリューションを見つけるために、他のブラウザベンダーとの協力にも努めています。
```suggestion
   <td>Chrome は、FedID コミュニティグループで ID 連携のための共通ソリューションを見つけるために、他のブラウザベンダーとの協力にも努めています。
```

2022-06-18 03:34 UTC, agektmr commented on site/ja/docs/privacy-sandbox/feedback/report-2022-q1.md
> +   <td>Chrome は、ブラウザがより積極的な役割を果たしていることを認識していますが、連携をサポートしながら、ブラウザがクロスサイトトラッキングを区別して防止するには、この追加レベルの関与が必要です。
```suggestion
   <td>Chrome は、ブラウザがより積極的な役割を果たしていることを認識していますが、ID 連携をサポートしながら、ブラウザがクロスサイトトラッキングを区別して防止するには、この追加レベルの関与が必要です。
```

2022-06-18 03:35 UTC, agektmr commented on site/ja/docs/privacy-sandbox/fedcm/index.md
> +*  承認プロンプト
「承認」 needs to be 「認可」

2022-06-20 13:18 UTC, ilyaspiridonov commented
@agektmr to make sure we're on the same page: apart from the requested changes that I committed, can you see other regressions)?

2022-06-20 13:23 UTC, agektmr commented
No, they are the only remaining change requests.

2022-06-20 15:28 UTC, agektmr approved these changes
LGTM

2022-06-20 15:29 UTC, merged