Announce wasm CSP change in MV3
GoogleChrome/developer.chrome.com pull request #3123
Opened 2022-06-30 20:32 UTC by dotproto

2022-07-01 14:44 UTC, jpmedley requested changes

2022-07-11 22:53 UTC, dotproto commented on site/en/docs/extensions/whatsnew/index.md
> +### Chrome 103: Wasm in Manifest V3 requires wasm-unsafe-eval {: #m103-wasm-csp }
We've been pretty consistent about using "Manifest V3". I think most of the matches you're seeing when searching for "v3" are coming from paths in URLs. I just searched for a few terms in the `site/en/docs/extensions/` directory of my local branch and gathered the results

Search | matches
--- | ---
`manifest v3` | 0
`Manifest v3` | 0
`manifest V3` | 0
`Manifest V3` | 143

2022-07-12 14:30 UTC, jpmedley approved these changes

2022-08-01 14:53 UTC, sofiayem commented
@dotproto @jpmedley Is this blocked or should we merge?

2022-08-01 15:50 UTC, jpmedley commented
It's @dotproto 's call.

2022-08-04 17:42 UTC, dotproto commented
Oops, accidentally overwrote this branch because I thought it was already merged. Nothing was blocking this, I just lost track of the PR 😅

2022-08-04 17:44 UTC, merged