DevTools > Network reference refresh
GoogleChrome/developer.chrome.com pull request #3145
Opened 2022-07-07 12:46 UTC by sofiayem

The Network reference is the most viewed page in the DevTools doc set. It had screenshots from M58.

- Recaptured all old screenshots.
- Added cosmetic changes to better comply with https://developers.google.com/style.
- Documented along the way:
   - https://developer.chrome.com/blog/new-in-devtools-96/#payload
   - https://developer.chrome.com/blog/new-in-devtools-94/#nvert-network-filter
   - https://developer.chrome.com/blog/new-in-devtools-92/#wasm

2022-07-11 06:33 UTC, rachelandrew approved these changes

2022-07-15 06:15 UTC, jecfish commented on site/en/docs/devtools/network/reference/index.md
> +### View query string parameters (request payload) {: #query-string }
There are two types of payload Query str params and Form Data. Probablt change the title to payload or add "and form data".

To debug, login Twitter, open network panel, refresh the page, filter request by fetch/xhr, and go through the list. There are both query str and form data example.

2022-07-15 06:30 UTC, jecfish requested changes
Such a big refresh! 👏

2022-07-15 06:30 UTC, jecfish commented on site/en/docs/devtools/network/reference/index.md
> +To disable URL-encoding for arguments, on the **Payload** tab, click **decoded**.
```suggestion
To disable URL-encoding for arguments, on the **Payload** tab, click **view decoded / view URL-encoded**.
```

Please confirm.

2022-07-15 13:30 UTC, sofiayem commented on site/en/docs/devtools/network/reference/index.md
>  To view the initiators and dependencies of a request, hold Shift and hover over the request in the
This is on my todo list for M80.

2022-07-28 11:37 UTC, merged