[JA] Translate Progress in the Privacy Sandbox 2022-06 into Japanese
GoogleChrome/developer.chrome.com pull request #3221
Opened 2022-07-14 07:44 UTC by ilyaspiridonov

Translate Progress in the Privacy Sandbox 2022-06 into Japanese

2022-07-14 07:56 UTC, ilyaspiridonov commented
@agektmr FYI:
I also wanted to report a small issue, which is specific to Japanese: 
- The English text extensively uses bold text formatting (**)
- In Japanese those asterisks will leak into the rendered document: 

<img width="721" alt="Screenshot 2022-07-14 at 10 33 14" src="https://user-images.githubusercontent.com/8548803/178930600-fa69eceb-5c5b-4af1-bd70-a6960f8d7dee.png">

- Reason: there are no spaces around the bold markup (**)
- I'm correcting this by adding extra spaces, but this may look un-natural in Japanese (as I understand, spaces should not be used there). 

<img width="702" alt="Screenshot 2022-07-14 at 10 54 49" src="https://user-images.githubusercontent.com/8548803/178931450-092da048-670c-432f-afae-cd9747a807c8.png">


Please confirm whether those extra spaces are OK. 
My understanding is this is the way the static site generator currently renders md->htlml.

2022-07-14 09:49 UTC, agektmr commented
@ilyaspiridonov adding extra spaces for these cases sounds good to me. Please do the same for `__` as well.

2022-07-14 10:18 UTC, agektmr requested changes

2022-07-15 04:14 UTC, agektmr approved these changes
LGTM

2022-07-15 04:14 UTC, merged