Update index.md
GoogleChrome/developer.chrome.com pull request #3287
Opened 2022-07-23 13:57 UTC by xyugroup

Fixes #SOME_ISSUE_NUMBER
Translated done. 

Changes proposed in this pull request:

-
-
-

2022-07-25 05:14 UTC, jecfish commented
Thanks Jim @xyugroup! Please help to translate this file as well `site/_includes/partials/devtools/pt/whats-new.md`. Example: https://github.com/GoogleChrome/developer.chrome.com/pull/3224/files

2022-07-25 05:14 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +draft: false
```suggestion
```

2022-07-25 05:15 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
>  *感谢 [流浪大法师 @liuliangsir](https://github.com/liuliangsir) 提供的翻译*。
@xyugroup Please replace it with you name and url (social media, github, linkedin, etc).

2022-07-25 05:16 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +<!-- **帧重启** 功能回归了! 你可以在函数中途从头开始重启当前代码行之前的代码。这个功能曾经因为稳定性问题在Chrome 92版本被弃用。  -->
```suggestion
**帧重启** 功能回归了! 你可以在函数中途从头开始重启当前代码行之前的代码。这个功能曾经因为稳定性问题在Chrome 92版本被弃用。
```

2022-07-25 05:16 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +<!-- 在这个 [例子](https://jec.fyi/), 调试器暂停在这个靠近`toggleColorScheme`函数尾端的断点（343 行) 。 在函数 `toggleColorScheme`开始处重启调试器, 扩展在**调试器**面板中的 **调用** 部分, 在`toggleColorScheme`上右点击并选取**帧重启**。  -->
```suggestion
在这个 [例子](https://jec.fyi/), 调试器暂停在这个靠近`toggleColorScheme`函数尾端的断点（343 行) 。 在函数 `toggleColorScheme`开始处重启调试器, 扩展在**调试器**面板中的 **调用** 部分, 在`toggleColorScheme`上右点击并选取**帧重启**。
```

2022-07-25 05:17 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +<!-- **帧重启** 功能回归了! 你可以在函数中途从头开始重启当前代码行之前的代码。这个功能曾经因为稳定性问题在Chrome 92版本被弃用。  -->
Hi @xyugroup , we can remove the comment syntax on Chinese translation. This apply to the whole article.

2022-07-25 05:17 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +<!-- ## 在调试时进行帧重启 {: #restart-frame  } -->
```suggestion
## 在调试时进行帧重启 {: #restart-frame  }
```

2022-07-25 05:20 UTC, jecfish requested changes

2022-07-25 05:20 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
>  Chromium issue: [1306756](https://crbug.com/1306756)
```suggestion
Chromium 议题: [1306756](https://crbug.com/1306756)
```

2022-07-25 05:20 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
>  Chromium issue: [1306756](https://crbug.com/1306756)
所有 Chromium issue 翻译为 Chromium 议题

2022-07-25 05:20 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +<!-- ## 录制面板中的慢速复盘选项 {: #recorder  } -->
```suggestion
## 录制面板中的慢速复盘选项 {: #recorder  }
```

2022-07-25 21:17 UTC, hanselfmu commented on site/zh/blog/new-in-devtools-104/index.md
> +description: "在调试时进行帧重启, 录制面板中的慢速复盘选项与更多。"
nit: I remember using `、` instead of commas here. Maybe change to "... 帧重启、录制面板 ..."?

2022-07-25 21:46 UTC, hanselfmu commented
Thanks very much @xyugroup ! It's pretty good for a first-time translator! There are mostly just some nits (e.g. formatting, sentence structure, etc.). I'll review the second half of the file later today.

2022-07-26 12:52 UTC, xyugroup commented on site/zh/blog/new-in-devtools-104/index.md
> +description: "在调试时进行帧重启, 录制面板中的慢速复盘选项与更多。"
Changed accordingly. Thank.

2022-07-28 02:31 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
```suggestion

{% YouTube id='4RXWfw7Xg_Y' %}
```

2022-07-28 02:32 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +*感谢 [Jim Lim @xyugroup](https://github.com/xyugroup, {# https://www.linkedin.com/in/jim-lim-539a5638" #}) 提供的翻译*。
```suggestion
*感谢 [Jim Lim @xyugroup](https://www.linkedin.com/in/jim-lim-539a5638) 提供的翻译*。
```

2022-07-28 03:37 UTC, liuliangsir commented on site/_includes/partials/devtools/zh/whats-new.md
> +* [源图改良](/zh/blog/new-in-devtools-104/#sourcemaps)
源图 might be replaced with the original word(Sourcemaps)

2022-07-29 01:41 UTC, liuliangsir commented on site/_includes/partials/devtools/zh/whats-new.md
> +* [改良JavaScript对象的自动填充建议](/zh/blog/new-in-devtools-104/#autocomplete)
```suggestion
* [优化 JavaScript 对象的自动填充建议功能](/zh/blog/new-in-devtools-104/#autocomplete)
```

2022-07-29 01:42 UTC, liuliangsir commented on site/_includes/partials/devtools/zh/whats-new.md
> +* [源图改良](/zh/blog/new-in-devtools-104/#sourcemaps)
```suggestion
* [优化 Sourcemaps 功能](/zh/blog/new-in-devtools-104/#sourcemaps)
```

2022-07-29 01:48 UTC, liuliangsir commented on site/_includes/partials/devtools/zh/whats-new.md
> +* [录制面板中的慢速复盘选项](/zh/blog/new-in-devtools-104/#recorder)
慢速复盘 seems to be wired. So do keep the original content.
```suggestion
* [录制面板新增  Slow replay  选项](/zh/blog/new-in-devtools-104/#recorder)
```

2022-07-29 01:50 UTC, liuliangsir commented on site/_includes/partials/devtools/zh/whats-new.md
> +
Here is a unnecessary blank line. So do remove it

```suggestion
```

2022-07-29 01:52 UTC, liuliangsir commented on site/_includes/partials/devtools/zh/whats-new.md
> +* [模拟性能录制的硬件并发](/zh/blog/new-in-devtools-104/#simulate)
```suggestion
* [模拟性能录制所需的硬件并发功能](/zh/blog/new-in-devtools-104/#simulate)
```

2022-07-29 01:59 UTC, liuliangsir commented on site/zh/blog/new-in-devtools-104/index.md
> +**帧重启** 功能回归了! 你可以在函数中途从头开始重启当前代码行之前的代码。这个功能曾经因为稳定性问题在Chrome 92版本被弃用。
The surrounding phrase(Chrome 92) need to be added both whitespaces.

```suggestion
**帧重启** 功能回归了! 你可以在函数中途从头开始重启当前代码行之前的代码。这个功能曾经因为稳定性问题在 Chrome 92 版本被弃用。  
```

2022-07-30 03:06 UTC, aquaMAX commented on site/zh/blog/new-in-devtools-104/index.md
> +[退后/前进缓存](/docs/devtools/application/back-forward-cache/) 面板中的**应用程序** 有新的 **帧** 分部来帮助你识别阻止页面符合bcache条件的阻塞帧 .
```suggestion
[退后/前进缓存](/docs/devtools/application/back-forward-cache/) 面板中的**应用程序** 有新的 **帧** 分部来帮助你识别阻止页面符合bfcache条件的阻塞帧 . 
```
bcache 应该是bfcache

2022-08-04 09:25 UTC, jecfish approved these changes

2022-08-04 09:25 UTC, jecfish commented on site/_includes/partials/devtools/zh/whats-new.md
> +* [模拟性能录制的硬件并发](/zh/blog/new-in-devtools-104/#css-var)
```suggestion
* [在自动填充层叠样式表（CSS）时预览非颜色数值的值](/zh/blog/new-in-devtools-104/#css-var)
```

2022-08-06 06:46 UTC, jecfish requested changes
Please also replace all 你 with 您

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +- **部署**. 浏览器读取的真正文件。 通常这些文件都会被缩小(minified)。
```suggestion
- **已部署（deployed）** - 浏览器读取的真正文件。 通常这些是已压缩的文件。 
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +- **撰写**. 类似你在集成开发环境(IDE)中的源文件。 DevTools 根据你的源图产生这些文件 (由你的构建工具DevTools所提供).
```suggestion
- **已编写**. 类似你在集成开发环境（IDE）中的源文件。 DevTools 根据您的源图产生这些文件 (由您的构建工具DevTools所提供).
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +你可以自己做一个尝试，用这个链接 [React demo](https://reactjs.org/)!
```suggestion
您可以利用这个 [React 范例](https://reactjs.org/) 来测试这项新功能。 
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +{% Img src="image/dPDCek3EhZgLQPGtEG3y0fTn4v82/5E1qbkl0Gx1REx7FdqEr.png", alt="使用源面板中的撰写/部署进行分组", width="800", height="521" %}
```suggestion
{% Img src="image/dPDCek3EhZgLQPGtEG3y0fTn4v82/5E1qbkl0Gx1REx7FdqEr.png", alt="使用源面板中的编写/部署进行分组", width="800", height="521" %}
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +## 性能洞察面板中的新功能 - 用户计时追踪 {: #performance }
```suggestion
## Performance insights 面板新增了用户计时轨道 {: #performance }
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +使用**性能洞察**面板中的新功能 - **用户计时**追踪进行录制以对 `performance.measure()` 的分数进行视觉化。
```suggestion
您现在可以透过 **Performance insights** 面板新增的**用户计时**轨道来查看您 performance recording 的 `performance.measure()` 标记。 
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +{% Img src="image/dPDCek3EhZgLQPGtEG3y0fTn4v82/nxPCp6UaiGWJCWWx4Laa.png", alt="性能洞察面板中的用户计时追踪", width="800", height="499" %}
```suggestion
{% Img src="image/dPDCek3EhZgLQPGtEG3y0fTn4v82/nxPCp6UaiGWJCWWx4Laa.png", alt="Performance insights 面板新增了用户计时轨道", width="800", height="499" %}
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +当你开始 [测量页面载入](/docs/devtools/performance-insights/#record), **用户计时** 追踪显示在录制中。在旁侧面板中点击计时物件检视计时细节.
```suggestion
当你开始 [测量页面载入](/docs/devtools/performance-insights/#record), **用户计时** 轨道显示在录制中。在旁侧面板中点击计时物件检视计时细节. 
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +## 显示元素的分配槽 {: #slot }
```suggestion
## 显示元素的分配槽（slot） {: #slot } 
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +## 源图改良 {: #sourcemaps }
```suggestion
## 源图优化 {: #sourcemaps }
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +这里对源图进行了一些改良以改进整体调试体验:
```suggestion
以下是列出了几个源图的修复，这些修复改进了整体调试体验: 
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +- 断点现在可以作用在带有sourceURL注释的内联的 `<script>`脚本中。
```suggestion
- 您现在可以在带有 sourceURL 注释的内联的 `<script>`脚本中设置断点。 
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +- 修复源面板中的**自动填充** 设置。之前, 这个功能的关闭设置是失效的。 ([1323286](https://crbug.com/1323286))
```suggestion
- 修复源面板中的**自动填充**设置。之前, 这个功能的关闭设置是失效的。 ([1323286](https://crbug.com/1323286))
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +- 更新**应用程序** 面板中的**清单文件（Manifest）**  来解析最新的配色方案的格式。 ([1318305](https://crbug.com/1318305))
```suggestion
- 更新**应用程序**面板中的**清单文件（Manifest）**来解析最新的配色方案的格式。 ([1318305](https://crbug.com/1318305))
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +- 改进了**性能洞见**中的 `<script async>` 渲染阻塞问题的建议。 以前，既使已经在脚本标注为异步， DevTools 也会建议用户`将异步属性添加到脚本标签`。 ([1334096](https://crbug.com/1334096))
```suggestion
- 改进了 **Performance insights** 中的 `<script async>` 渲染阻塞问题的建议。 之前，既使已经在脚本标注为异步， DevTools 也会建议用户`将异步属性添加到脚本标签`。 ([1334096](https://crbug.com/1334096))
```

2022-08-06 06:46 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +- 当**命令菜单**中 [打开文件](/docs/devtools/resources/#open) , 撰写文件 (源图产生的文件) 的排名会更加高，因此他们会出现在被相似命名的部署脚本之上。 ([1312929](https://crbug.com/1312929))
```suggestion
- 当**命令菜单**中 [打开文件](/docs/devtools/resources/#open) , 编写文件 (源图产生的文件) 的排名会更加高，因此他们会出现在被相似命名的部署脚本之上。 ([1312929](https://crbug.com/1312929)) 
```

2022-08-06 06:46 UTC, jecfish commented on site/_includes/partials/devtools/zh/whats-new.md
> +* [使用面板中的撰写/部署来进行分组](/zh/blog/new-in-devtools-104/#authored-deployed)
```suggestion
* [使用面板中的编写/部署来进行分组](/zh/blog/new-in-devtools-104/#authored-deployed)
```

2022-08-07 07:21 UTC, jecfish commented on site/_includes/partials/devtools/zh/whats-new.md
> +* [其他亮点](/zh/blog/new-in-devtools-104/#misc)
```suggestion
* [其他的更新](/zh/blog/new-in-devtools-104/#misc) 
```

2022-08-07 07:21 UTC, jecfish commented on site/zh/blog/new-in-devtools-104/index.md
> +- **已部署（deployed）** - 浏览器读取的真正文件。 通常这些是已压缩的文件。
```suggestion
- **已部署（Deployed）** - 浏览器读取的真正文件。 通常这些是已压缩的文件。 
```

2022-08-07 07:22 UTC, jecfish approved these changes

2022-08-10 07:09 UTC, jecfish commented
Thank you all!

2022-08-10 07:09 UTC, merged