Clarify Domain Verification
GoogleChrome/developer.chrome.com pull request #3315
Opened 2022-07-26 16:15 UTC by jonathansampson

Previous wording was terribly confusing; I spent a bit of time in the Search Console looking for a place to associate a domain name with an extension.

Changes proposed in this pull request:

- Slight rewording of _Verification_ explanation.

2022-08-01 17:11 UTC, dotproto requested changes
The content update looks good. We just need to wrap the text at 100 characters before merging.

2022-08-01 17:11 UTC, dotproto commented on site/en/docs/extensions/mv3/settings_override/index.md
> +Here is an example how [homepage][1], [search provider][2] and [startup pages][3] can be modified in the [extension manifest][4]. Any domain used in the settings API must be [verified][5] (via Google
Rewrap at 100 characters.

```suggestion
Here is an example how [homepage][1], [search provider][2] and [startup pages][3] can be modified in
the [extension manifest][4]. Any domain used in the settings API must be [verified][5] (via Google
Search Console) by the same developer account publishing the extension. Note that if you verify
ownership for a domain (for example, https://example.com) you can use any subdomain or page (for
example, https://app.example.com or https://example.com/page.html) within your extension.
```

2022-08-02 13:58 UTC, jonathansampson commented
Thank you, @dotproto. I went ahead and wrapped _on spaces_ at 100 characters, merged with previous commits, and force pushed the changes for further review. Kind regards!

2022-08-03 13:39 UTC, dotproto approved these changes
LGTM. Thanks, @jonathansampson 😄

2022-08-03 14:02 UTC, merged