Devtools 104 > Elements > Badges reference
GoogleChrome/developer.chrome.com pull request #3331
Opened 2022-07-28 11:55 UTC by sofiayem

Documented:
- https://developer.chrome.com/blog/new-in-devtools-104/#slot
- https://developer.chrome.com/blog/new-in-devtools-91/#css-croll-snap
- https://developer.chrome.com/blog/new-in-devtools-94/#container-queries
- https://developer.chrome.com/blog/new-in-devtools-91/#badge-settings
Also documented all other badges.

2022-07-28 12:32 UTC, rachelandrew approved these changes
Just a little nit.

2022-07-28 12:32 UTC, rachelandrew commented on site/en/docs/devtools/elements/badges/index.md
> +An HTML element is a [flexbox](https://developer.mozilla.org/docs/Web/CSS/CSS_Flexible_Box_Layout) if its `display` CSS property is set to `flex` or `inline-flex`. Such elements have `flex` badges ne
```suggestion
An HTML element is a [flex container](https://developer.mozilla.org/docs/Web/CSS/CSS_Flexible_Box_Layout) if its `display` CSS property is set to `flex` or `inline-flex`. Such elements have `flex` badges next to them that toggle the corresponding overlays.
```

2022-07-29 10:53 UTC, jecfish requested changes

2022-07-29 10:53 UTC, jecfish commented on site/en/docs/devtools/elements/badges/index.md
> +DevTools can detect most ad frames. Such frames have `ad` badges next to them.
expand explanation on how we know it's an ad frame. Tag you in a conversation and resource.

2022-07-29 10:53 UTC, jecfish commented on site/en/docs/devtools/elements/badges/index.md
> +{% Codepen {
set bigger height, not able to view the code clearly

2022-08-01 13:13 UTC, rachelandrew approved these changes
There's a note about a Codepen height to check.

2022-08-01 13:47 UTC, sofiayem commented
> There's a note about a Codepen height to check.

Done.

2022-08-02 12:27 UTC, merged