[JA] translation for Expanding Privacy Sandbox Testing
GoogleChrome/developer.chrome.com pull request #3345
Opened 2022-07-30 20:55 UTC by ilyaspiridonov

Japanese translation for the Expanding Privacy Sandbox Testing article. 
PEMT by Alconost

2022-07-30 21:02 UTC, ilyaspiridonov commented
CC: @agektmr

2022-07-31 02:05 UTC, agektmr requested changes

2022-07-31 02:05 UTC, agektmr commented on site/ja/blog/expanding-privacy-sandbox-testing/index.md
> +また、 **[GitHub に発者サポートリポジトリ](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support)** も用意されています。 イシューが発生した場合や、質問をどこに問題を提起すべきか分からない場合は、 イシューを投稿すると、当社が回答を行ったり、照会する適切な場所を見つけるお手伝いをしたりします。
```suggestion
また、 **[GitHub に開発者サポートリポジトリ](https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support)** も用意されています。 イシューが発生した場合や、質問をどこに問題を提起すべきか分からない場合は、 イシューを投稿すると、当社が回答を行ったり、照会する適切な場所を見つけるお手伝いをしたりします。
```

2022-07-31 02:05 UTC, agektmr commented on site/ja/blog/expanding-privacy-sandbox-testing/index.md
> +最終的に、Cookie の動作を変更することで、28 年間 Web の一部であった技術を変更しています。 Web は私たち全員に属しています。これらの変更に取り組み、よりプライベートな環境を可能にしながら、誰にとっても魅力的な豊かでオープンなエコシステムを可能にする理想的なミックスを追求するには、皆さんからの情報入力と指示が必要です。 この計画にご協力ください。
```suggestion
最終的に、Cookie の動作を変更することで、28 年間 Web の一部であった技術を変更します。 Web は私たち全員に属しています。これらの変更に取り組み、よりプライベートな環境を可能にしながら、誰にとっても魅力的な豊かでオープンなエコシステムを可能にする理想的なミックスを追求するには、皆さんからの情報と方向性の提供が必要です。 この計画にご協力ください。
```

2022-07-31 07:33 UTC, ilyaspiridonov commented
@agektmr requested changes integrated, thank you

2022-07-31 07:35 UTC, agektmr approved these changes
LGTM

2022-07-31 07:35 UTC, merged

2022-07-31 07:36 UTC, agektmr commented
@isalconost Thank you!