Depsrems
GoogleChrome/developer.chrome.com pull request #3362
Opened 2022-08-02 16:57 UTC by jpmedley

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

2022-08-03 07:09 UTC, rachelandrew requested changes
There's a missing link in this, you may know but thought I'd just flag it up.

2022-08-03 07:09 UTC, rachelandrew commented on site/en/blog/deps-rems-105/index.md
> +The CSS keyword ['default' is no longer allowed](https://chromestatus.com/feature/5096490737860608) within CSS custom identifiers, which are used for many types of user-defined names in CSS (for exam
```suggestion
The CSS keyword ['default' is no longer allowed](https://chromestatus.com/feature/5096490737860608) within CSS custom identifiers, which are used for many types of user-defined names in CSS (for example, names created by `@keyframes` rules, counters, `@container` names, custom layout or paint names). This adds `'default'` to the list of names that are restricted from use in custom identifiers, specifically `'inherit'`, `'initial'`, `'unset'`, `'revert'`, and `'revert-layer'`.
```

2022-08-03 07:09 UTC, rachelandrew commented on site/en/blog/deps-rems-105/index.md
> +The `transitionWhile()` and `restoreScroll()` methods are also deprecated in this release, and we expect to remove them in 108. Developers who need this functionality should use the new `intercept()`
Missing link

2022-08-03 07:09 UTC, rachelandrew commented on site/en/blog/deps-rems-105/index.md
> +To align with the latest spec ([RFC 6265bis](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis/#section-5.5)), [Chromium will soon reject](https://www.chromestatus.com/feature/55349
```suggestion
To align with the latest spec ([RFC 6265bis](https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-rfc6265bis/#section-5.5)), [Chromium will soon reject](https://www.chromestatus.com/feature/5534966262792192) cookies with a "Domain" attribute that contains a non-ASCII character (for example, Domain=éxample.com).
```

2022-08-03 18:37 UTC, jpmedley commented on site/en/blog/deps-rems-105/index.md
> +The `transitionWhile()` and `restoreScroll()` methods are also deprecated in this release, and we expect to remove them in 108. Developers who need this functionality should use the new `intercept()`
```suggestion
The `transitionWhile()` and `restoreScroll()` methods are also deprecated in this release, and we expect to remove them in 108. Developers who need this functionality should use the new `intercept()` and `scroll()` methods. For explanations of the problems with the existing methods and examples of using the new, see [Changes to NavigateEvent](https://developer.chrome.com/blog/navigateevent-intercept/).
```

2022-08-03 18:38 UTC, jpmedley commented
Issues addressed. PTAL

2022-08-04 04:06 UTC, rachelandrew approved these changes

2022-08-04 04:06 UTC, rachelandrew commented on site/en/blog/deps-rems-105/index.md
> +The `transitionWhile()` and `restoreScroll()` methods are also deprecated in this release, and we expect to remove them in 108. Developers who need this functionality should use the new `intercept()`
```suggestion
The `transitionWhile()` and `restoreScroll()` methods are also deprecated in this release, and we expect to remove them in 108. Developers who need this functionality should use the new `intercept()` and `scroll()` methods. For explanations of the problems with the existing methods and examples of using the new, see [Changes to NavigateEvent](/blog/navigateevent-intercept/).
```

2022-08-04 15:32 UTC, merged