Add deprecations and removals for Chrome 89
GoogleChrome/developer.chrome.com pull request #337
Opened 2021-01-28 14:47 UTC by jpmedley

2021-01-29 01:40 UTC, robdodson requested changes

2021-01-29 01:40 UTC, robdodson commented on site/en/blog/deps-rems-89/index.md
> +hero: './dep-rem_480.jpg'
Hey @jpmedley for the hero image would you mind uploading it to our image cdn ([guide](https://developer.chrome.com/docs/handbook/how-to/add-media/)) and copy the image into here.

Here's [an example](https://github.com/GoogleChrome/developer.chrome.com/blame/d0275dc7c05ffaad4680a5b52f95928a46b67aa4/site/en/blog/new-in-chrome-54/index.md#L13) of what it should look like from one of Pete's posts.

I have a PR that I'm working on which explains the process better but I don't think it'll be up until tomorrow.

2021-01-29 01:40 UTC, robdodson commented on site/en/blog/deps-rems-89/index.md
> +{% include 'see-all-dep-rem.md' %}
```suggestion
{% include 'partials/see-all-dep-rem.md' %}
```

2021-01-29 01:40 UTC, robdodson commented on site/en/blog/deps-rems-89/index.md
> +{% include 'deprecations-policy.md' %}
```suggestion
{% include 'partials/deprecations-policy.md' %}
```

2021-02-25 16:09 UTC, petele commented
@robdodson @jpmedley - is this good to go?

2021-02-25 18:17 UTC, robdodson approved these changes

2021-02-25 18:17 UTC, robdodson commented
It seems fine to me, did y'all decide not to use a hero image?

2021-02-26 14:40 UTC, jpmedley commented
No more hero images.

2021-02-26 14:40 UTC, merged