CRX What's New updates
GoogleChrome/developer.chrome.com pull request #3384
Opened 2022-08-04 17:55 UTC by dotproto

Add two new items to the extensions What's New page

* The recent CWS analytics revamp blog post
* Identity API promise support

2022-08-04 17:57 UTC, dotproto commented
Tagging in @rachelandrew rather than @jpmedley as I believe she indicated that she's handling extensions related changes until we have a dedicated tech writer. Please correct me if I'm wrong 😄

2022-08-04 21:45 UTC, jpmedley requested changes

2022-08-04 21:45 UTC, jpmedley commented on site/en/docs/extensions/whatsnew/index.md
> +### Chrome 105: Promises for the Identity API
```suggestion
### Chrome 105: promises for the Identity API
```

2022-08-04 21:45 UTC, jpmedley commented on site/en/docs/extensions/whatsnew/index.md
> +### Blog post: Chrome Web Store Analytics Revamp {: #cws-analytics-revamp }
```suggestion
### Blog post: Chrome Web Store analytics revamp {: #cws-analytics-revamp }
```

2022-08-04 21:45 UTC, jpmedley commented on site/en/docs/extensions/whatsnew/index.md
> +information upfront. [Read the blog post](/blog/cws-analytics-revamp/) for more information.
```suggestion
information up front. [Read the blog post](/blog/cws-analytics-revamp/) for more information.
```

2022-08-04 22:02 UTC, Duca1976 commented
???

Il gio 4 ago 2022, 23:45 Joe Medley ***@***.***> ha scritto:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In site/en/docs/extensions/whatsnew/index.md
> <https://github.com/GoogleChrome/developer.chrome.com/pull/3384#discussion_r938271120>
> :
>
> > @@ -15,6 +15,25 @@ updated: 2022-06-15
>
>  Check this page often to learn about changes to the Chrome extensions platform, its documentation,
>
>  and related policy or other changes.
>
>
>
> +### Chrome 105: Promises for the Identity API
>
>
> ⬇️ Suggested change
>
> -### Chrome 105: Promises for the Identity API
>
> +### Chrome 105: promises for the Identity API
>
>
> ------------------------------
>
> In site/en/docs/extensions/whatsnew/index.md
> <https://github.com/GoogleChrome/developer.chrome.com/pull/3384#discussion_r938271230>
> :
>
> > @@ -15,6 +15,25 @@ updated: 2022-06-15
>
>  Check this page often to learn about changes to the Chrome extensions platform, its documentation,
>
>  and related policy or other changes.
>
>
>
> +### Chrome 105: Promises for the Identity API
>
> +
>
> +July 15, 2022
>
> +
>
> +Functions on the [Identity API](/docs/extensions/reference/identity/#method-getAuthToken) now
>
> +support promise based calls. This comes with a slight change to the surface for
>
> +[`identity.getAuthToken()`](/docs/extensions/reference/identity/#method-getAuthToken), where the
>
> +asynchronous return set to a promise based call will have "token" and "grantedScopes" as parameters
>
> +on a single object (as opposed to the callback version receiving them as separate arguments to the
>
> +callback).
>
> +
>
> +### Blog post: Chrome Web Store Analytics Revamp {: #cws-analytics-revamp }
>
>
> ⬇️ Suggested change
>
> -### Blog post: Chrome Web Store Analytics Revamp {: #cws-analytics-revamp }
>
> +### Blog post: Chrome Web Store analytics revamp {: #cws-analytics-revamp }
>
>
> ------------------------------
>
> In site/en/docs/extensions/whatsnew/index.md
> <https://github.com/GoogleChrome/developer.chrome.com/pull/3384#discussion_r938271419>
> :
>
> > +July 15, 2022
>
> +
>
> +Functions on the [Identity API](/docs/extensions/reference/identity/#method-getAuthToken) now
>
> +support promise based calls. This comes with a slight change to the surface for
>
> +[`identity.getAuthToken()`](/docs/extensions/reference/identity/#method-getAuthToken), where the
>
> +asynchronous return set to a promise based call will have "token" and "grantedScopes" as parameters
>
> +on a single object (as opposed to the callback version receiving them as separate arguments to the
>
> +callback).
>
> +
>
> +### Blog post: Chrome Web Store Analytics Revamp {: #cws-analytics-revamp }
>
> +
>
> +July 28, 2022
>
> +
>
> +Chrome Web Store has a revamped item analytics experience for the Chrome Web Store Developer
>
> +Dashboard. The new dashboard is easier to understand at a glance and consolidates the most useful
>
> +information upfront. [Read the blog post](/blog/cws-analytics-revamp/) for more information.
>
>
> ⬇️ Suggested change
>
> -information upfront. [Read the blog post](/blog/cws-analytics-revamp/) for more information.
>
> +information up front. [Read the blog post](/blog/cws-analytics-revamp/) for more information.
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleChrome/developer.chrome.com/pull/3384#pullrequestreview-1062620970>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVDLOOXTZ2KQITHHHLPPTGLVXQ2YTANCNFSM55TM6H6Q>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***
> com>
>

2022-08-10 15:11 UTC, dotproto commented
@jpmedley, could you take another pass at this?

2022-08-10 17:44 UTC, jpmedley approved these changes

2022-08-10 17:50 UTC, merged