Improving Progressive Web App offline support detection
GoogleChrome/developer.chrome.com pull request #345
Opened 2021-01-29 22:03 UTC by petele

Changes proposed in this pull request:
- PWA offline detection changes post
- Adds tag for `progressive-web-apps`

cc: @b1tr0t

2021-02-01 17:37 UTC, petele commented
Have LGTM from @b1tr0t via email

2021-02-01 20:39 UTC, jpmedley requested changes

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +heuristic.
```suggestion
Verification of offline support has been part of PWA installability
criteria for several years; however, the check was a simplified
heuristic.
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +heuristic.
Also, should it be "Chrome's PWA installability criteria"?

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +installed that included a `fetch` event handler.  Chrome did not have the
```suggestion
that included a `fetch` event handler.  Chrome did not have the
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +capability to simulate requests through the service worker, so a full check of
```suggestion
ability to simulate requests through the service worker, so a full check of
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +Chrome only checked whether the service worker actually has a `fetch` handler.
```suggestion
Chrome only checked whether the service worker actually had a `fetch` handler.
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +through the service worker, allowing us to update the offline detection logic
```suggestion
through the service worker, allowing improved offline detection logic
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +   status code (indicating a successful fetch) in simulated offline mode.**
```suggestion
* That there is a service worker installed for the page.
* That the installed service worker has a `fetch` event.
* **That the installed service worker `fetch` event returns an HTTP 200
   status code (indicating a successful fetch) in simulated offline mode.**
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +   status code (indicating a successful fetch) in simulated offline mode.**
Web.dev restricts numbered lists to steps of a procedure.

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +not require any action on your part.
```suggestion
for your Progressive Web App, this change to offline detection requires no
action by you.
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +not require any action on your part.
Aside from following a best practice of omitting needless words, this makes a primary point of the article more direct, and hence easier to remember.

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +resources from the network every time. At the other end of the spectrum, a
```suggestion
resources from the network every time. At the other end of the spectrum is a
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +our team regularly monitors those tags and does our best to help.
```suggestion
tag it with [`service-worker`][so-sw] and [`progressive-web-apps`][so-pwa].
Our team regularly monitors those tags and does our best to help.
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +For most PWA developers who correctly implemented offline mode, this change
```suggestion
For most PWA developers, specifically those who correctly implemented offline mode, this change
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +for developers with apps that have broken offline modes to address the issue.
```suggestion
to address this issue for developers with apps that have broken offline modes.
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +Lighthouse v7 will also indicate that there's a problem with the
```suggestion
Lighthouse v7 and later will also indicate when there's a problem with the
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +  {% img src="image/0g2WvpbGRGdVs0aAPc6ObG7gkud2/PuyRpRfJnVs8o8aTdHlA.png", alt="Screen shot of DevTools showing warning message in Console", width="800", height="115" %}
```suggestion
  {% img src="image/0g2WvpbGRGdVs0aAPc6ObG7gkud2/PuyRpRfJnVs8o8aTdHlA.png", alt="Screen shot of DevTools showing warning message in Console.", width="800", height="115" %}
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +    Warning message in the Chrome DevTools Console
```suggestion
    Warning message in the Chrome DevTools Console.
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +  {% img src="image/0g2WvpbGRGdVs0aAPc6ObG7gkud2/TjqKPXYUF5Y3tjeZLSwT.png", alt="Screenshot of DevTools showing warning message in Application tab", width="800", height="175" %}
```suggestion
  {% img src="image/0g2WvpbGRGdVs0aAPc6ObG7gkud2/TjqKPXYUF5Y3tjeZLSwT.png", alt="Screenshot of DevTools showing warning message in Application tab.", width="800", height="175" %}
```

2021-02-01 20:39 UTC, jpmedley commented on site/en/blog/improved-pwa-offline-detection/index.md
> +    Warning message in Application tab &gt; Manifest &gt; Installability
```suggestion
    Warning message in Application tab &gt; Manifest &gt; Installability.
```

2021-02-01 20:51 UTC, petele commented
@jpmedley - I've integrated all of your feedback.

2021-02-01 22:14 UTC, jpmedley approved these changes

2021-02-01 22:18 UTC, petele commented
Please - **do not merge** - I'd like to personally merge this and push it out with some specific tweets and other announcements.

2021-02-01 22:24 UTC, jpmedley commented
The new rule for like the last month has been for authors to merge their own work.

2021-02-01 22:27 UTC, jpmedley commented
@robdodson Percy is indicating something needs to be reviewed. When I look at the details, I don't know what I'm supposed to be looking at or even if I'm the one supposed to be doing it. I'd appreciate a little guidance.

2021-02-02 00:51 UTC, robdodson commented
Should be fixed now. Currently percy is snapshotting live data so basically every new post will cause it to fail (because the page always changes). https://github.com/GoogleChrome/developer.chrome.com/issues/78

We'll fix the bug and write up a better explainer soon. For now feel free to tag me when percy fails and I can approve.

2021-02-02 16:39 UTC, robdodson approved these changes

2021-02-05 15:19 UTC, jpmedley approved these changes

2021-02-08 14:26 UTC, merged