DevTools 105 > Application > Manifest > Protocol Handlers
GoogleChrome/developer.chrome.com pull request #3525
Opened 2022-08-23 14:39 UTC by sofiayem

Documented https://developer.chrome.com/blog/new-in-devtools-105/#manifest

Also, replaced mentions of "Simulate Add to Homescreen events" with "Trigger installation" because [Chrome is streamlining PWA installation](https://developer.chrome.com/blog/a2hs-updates/) and the [absence of Home screen event link in DevTools confuses people](https://stackoverflow.com/questions/58128145/add-to-homescreen-link-missing-in-chrome-devtools).

Also, cosmetic changes.

Merge on Aug 30.

2022-08-25 06:53 UTC, rachelandrew approved these changes

2022-08-30 07:32 UTC, jecfish requested changes

2022-08-30 07:32 UTC, jecfish commented on site/en/docs/devtools/progressive-web-apps/index.md
> +The registration of such a handler lets installed PWAs handle links that use the URL protocol.
```suggestion
PWAs can handle links that use a specific protocol for a more integrated experience.
```

2022-08-30 07:39 UTC, jecfish requested changes

2022-08-30 07:39 UTC, jecfish commented on site/en/docs/devtools/progressive-web-apps/index.md
> +1. [Open DevTools](/docs/devtools/open/) on the landing page of your PWA. For example, check out this [demo page](https://protocol-handler.glitch.me/).
Missing a step. To test the protocol handler (on successful navigation), one need to first install the app and reload and register.

2022-08-30 11:17 UTC, jecfish commented on site/en/docs/devtools/progressive-web-apps/index.md
> +1. From the demo page, install the PWA and reload the app after the installation. The browser has now registered the PWA as a handler for the `web+coffee` protocol with the operating system.
```suggestion
1. From the demo page, install the PWA and reload the app after the installation. The browser has now registered the PWA as a handler for the `web+coffee` protocol.
```

2022-08-30 11:18 UTC, jecfish commented on site/en/docs/devtools/progressive-web-apps/index.md
> +1. [Open DevTools](/docs/devtools/open/) on the landing page of your PWA. For example, check out this [demo page](https://protocol-handler.glitch.me/).
```suggestion
1. [Open DevTools](/docs/devtools/open/) on the landing page of your PWA. For example, check out this [demo PWA](https://protocol-handler.glitch.me/).
```

2022-08-30 11:19 UTC, jecfish approved these changes
LGTM % minor comments.

2022-08-30 11:22 UTC, merged