[JA] Translations (Privacy Sandbox, Blog0
GoogleChrome/developer.chrome.com pull request #3641
Opened 2022-09-05 13:07 UTC by ilyaspiridonov

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

2022-09-05 13:16 UTC, ilyaspiridonov commented
CC: @agektmr 
Please note there's one last [article pending your review](https://gitlocalize.com/repo/7832/ja/review)

2022-09-06 02:27 UTC, agektmr commented
I left a comment in the remaining one article. Could you please check that? It might be a bug.

2022-09-06 05:13 UTC, ilyaspiridonov commented
> I left a comment in the remaining one article. Could you please check that? It might be a bug.

Yes, I did see it and fixed it. It's not a bug, the translator just removed one opening { by mistake

2022-09-06 05:16 UTC, agektmr commented
I just saw your comment at GitLocalize. Is it possible to receive an email when there's a reply?

2022-09-06 05:28 UTC, agektmr requested changes

2022-09-06 05:28 UTC, agektmr commented on site/ja/docs/privacy-sandbox/attribution-reporting/system-overview/index.md
> +*[アトリビューション ソース](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#heading=h.dmy7iuqnhvby)*は、広告関連のイベント（クリックまたはビュー）であり、アドテックは以下の種類の情報を添付できます。
```suggestion
*[アトリビューション ソース](https://docs.google.com/document/d/1BXchEk-UMgcr2fpjfXrQ3D8VhTR-COGYS1cwK_nyLfg/edit#heading=h.dmy7iuqnhvby)* は、広告関連のイベント（クリックまたはビュー）であり、アドテックは以下の種類の情報を添付できます。
```

2022-09-06 05:28 UTC, agektmr commented on site/ja/docs/privacy-sandbox/attribution-reporting/system-overview/index.md
> +*[集計可能なレポート](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md#aggregatable-reports)*は、要約レポートの生成に使用されます。集計可能なレポートは、（サイト運営者のサイトで）広告から収集されたデータと（広告主のサイトからの）コンバージョンデータを組み合わせたもので、ア
```suggestion
*[集計可能なレポート](https://github.com/WICG/conversion-measurement-api/blob/main/AGGREGATE.md#aggregatable-reports)* は、要約レポートの生成に使用されます。集計可能なレポートは、（サイト運営者のサイトで）広告から収集されたデータと（広告主のサイトからの）コンバージョンデータを組み合わせたもので、アドテックによって収集される前に、ユーザーのデバイスのブラウザによって生成され暗号化されます。
```

2022-09-06 05:28 UTC, agektmr commented on site/ja/docs/privacy-sandbox/attribution-reporting/system-overview/index.md
> +イベントレベルレポートには 2 ～ 30 日の遅延があります。集計可能なレポートは 1 時間以内にランダムな遅延で送信され、イベントは*[コントリビューション予算](https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#contribution-bounding-and-budgeting)*内に収まる必
```suggestion
イベントレベルレポートには 2 ～ 30 日の遅延があります。集計可能なレポートは 1 時間以内にランダムな遅延で送信され、イベントは *[コントリビューション予算](https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#contribution-bounding-and-budgeting)* 内に収まる必要があります。これらの選択により、プライバシーが保護され、個々のユーザーのアクションの悪用が防止されます。
```

2022-09-06 05:28 UTC, agektmr commented on site/ja/docs/privacy-sandbox/attribution-reporting/system-overview/index.md
> +*[アトリビューション トリガー](https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#attribution-trigger-registration)*は、コンバージョンを取得するよう API に指示するイベントです。
```suggestion
*[アトリビューション トリガー](https://github.com/WICG/attribution-reporting-api/blob/main/AGGREGATE.md#attribution-trigger-registration)* は、コンバージョンを取得するよう API に指示するイベントです。
```

2022-09-06 05:28 UTC, agektmr commented on site/ja/blog/privacy-sandbox-unified-origin-trial/index.md
> +`document` 内の `browsingTopics()` 関数と、「browsing-topics」のアクセス許可ポリシー（/docs/privacy-sandbox/permissions-policy/#featurepolicyallowsfeaturefeature）を確認してください。
This is a bug in the original article but I'd rather fix it in Japanese.

```suggestion
`document` 内の `browsingTopics()` 関数と、「browsing-topics」の[アクセス許可ポリシー](/docs/privacy-sandbox/permissions-policy/#featurepolicyallowsfeaturefeature)を確認してください。
```

2022-09-06 06:29 UTC, ilyaspiridonov commented
> I just saw your comment at GitLocalize. Is it possible to receive an email when there's a reply?
We do have this on our roadmap )

2022-09-06 06:41 UTC, ilyaspiridonov commented
@agektmr I have added [the latest file](https://gitlocalize.com/repo/7832/ja/review/49450) to this PR as well

2022-09-06 08:43 UTC, agektmr approved these changes
LGTM

2022-09-06 08:43 UTC, merged