[JA] Translate fledge-api and storage-partitioning
GoogleChrome/developer.chrome.com pull request #3750
Opened 2022-09-19 12:33 UTC by ilyaspiridonov

[See review request for index.md on GitLocalize](https://gitlocalize.com/repo/7832/ja/review/50919)
[See review request for index.md on GitLocalize](https://gitlocalize.com/repo/7832/ja/review/50920)
PEMT by Alconost

2022-09-19 12:46 UTC, ilyaspiridonov commented
CC: @agektmr

2022-09-20 03:23 UTC, agektmr requested changes

2022-09-20 03:30 UTC, agektmr requested changes

2022-09-20 03:30 UTC, agektmr commented on site/ja/docs/privacy-sandbox/storage-partitioning/index.md
> +[クォータ システム](https://web.dev/storage-for-the-web/#how-much): クォータ システムは、ストレージに割り当てられるディスク容量を決定するために使用されます。各パーティションはクォータ システムによって個別のバケットとして管理され、許可される容量と、クリアされる時期が決定されます。: `navigator.storage.estimate()`
```suggestion
[クォータ システム](https://web.dev/storage-for-the-web/#how-much)
:   クォータ システムは、ストレージに割り当てられるディスク容量を決定するために使用されます。各パーティションはクォータ システムによって個別のバケットとして管理され、許可される容量と、クリアされる時期が決定されます。
:   `navigator.storage.estimate()` はパーティションの情報を返します。`window.webkitStorageInfo` や `navigator.webkitTemporaryStorage` などの Chrome 専用 API は使用廃止になります。
:   [IndexedDB](https://developer.mozilla.org/docs/Web/API/IndexedDB_API) と [キャッシュ ストレージ](https://web.dev/cache-api-quick-guide)は、新しいパーティション クォータ システムを使用します。
```

2022-09-20 03:30 UTC, agektmr commented on site/ja/docs/privacy-sandbox/storage-partitioning/index.md
> +[Web Storage API](https://developer.mozilla.org/docs/Web/API/Web_Storage_API) : Web Storage API は、ブラウザがキーと値のペアを保存できる [Local Storage](https://developer.mozilla.org/docs/Web/API/Window/localStorage) と
```suggestion
[Web Storage API](https://developer.mozilla.org/docs/Web/API/Web_Storage_API)
:   Web Storage API は、ブラウザがキーと値のペアを保存できる [Local Storage](https://developer.mozilla.org/docs/Web/API/Window/localStorage) と [Session Storage](https://developer.mozilla.org/docs/Web/API/Window/sessionStorage) の 2 つの仕組みを提供します。これらは現在クォータで管理されていませんが、引き続きパーティション化されます。
```

2022-09-20 03:30 UTC, agektmr commented on site/ja/docs/privacy-sandbox/storage-partitioning/index.md
> +[Origin Private File System](https://web.dev/file-system-access/#accessing-the-origin-private-file-system) : [File System Access API](https://web.dev/file-system-access)を使用すると、ユーザーがアクセスを許可した後、サイトはデバイ
```suggestion
[Origin Private File System](https://web.dev/file-system-access/#accessing-the-origin-private-file-system)
:   [File System Access API](https://web.dev/file-system-access)を使用すると、ユーザーがアクセスを許可した後、サイトはデバイス上のファイルやフォルダの変更を直接読み取ったり保存したりできます。Origin Private File System を使用すると、オリジンは、ユーザーが簡単にアクセスできるディスクに非公開コンテンツを保存でき、パーティション化されます。
```

2022-09-20 03:30 UTC, agektmr commented on site/ja/docs/privacy-sandbox/storage-partitioning/index.md
> +[Storage Bucket API](https://wicg.github.io/storage-buckets/explainer.html) : Storage Bucket API は、バケットと呼ばれる新しい概念を使用して、IndexedDB や localStorage などのさまざまなストレージ API を統合する [Storage Standard](https://stor
```suggestion
[Storage Bucket API](https://wicg.github.io/storage-buckets/explainer.html)
:   Storage Bucket API は、バケットと呼ばれる新しい概念を使用して、IndexedDB や localStorage などのさまざまなストレージ API を統合する [Storage Standard](https://storage.spec.whatwg.org/) 用に開発されています。バケットに格納されたデータとバケットに関連付けられたメタデータはパーティションされます。
```

2022-09-20 03:30 UTC, agektmr commented on site/ja/docs/privacy-sandbox/storage-partitioning/index.md
> +[Clear-Site-Data ヘッダー](https://developer.mozilla.org/docs/Web/HTTP/Headers/Clear-Site-Data) : 応答に `Clear-Site-Data` ヘッダーを含めると、サーバーはユーザーのブラウザに保存されているデータを消去するように要求できます。キャッシュ、Cookie、および DOM ストレージをクリアできま
```suggestion
[Clear-Site-Data ヘッダー](https://developer.mozilla.org/docs/Web/HTTP/Headers/Clear-Site-Data)
:   応答に `Clear-Site-Data` ヘッダーを含めると、サーバーはユーザーのブラウザに保存されているデータを消去するように要求できます。キャッシュ、Cookie、および DOM ストレージをクリアできます。ヘッダーを使用すると、1 つのパーティション内のストレージのみがクリアされます。
```

2022-09-20 03:30 UTC, agektmr commented on site/ja/docs/privacy-sandbox/storage-partitioning/index.md
> +[Blob URL](https://developer.mozilla.org/docs/Web/API/URL/createObjectURL) ストア : [blob](https://developer.mozilla.org/docs/Web/API/Blob) は、処理される生データを含むオブジェクトであり、リソースにアクセスするために blob URL を生成できます。トップレベル
```suggestion
[Blob URL](https://developer.mozilla.org/docs/Web/API/URL/createObjectURL) ストア
:   [blob](https://developer.mozilla.org/docs/Web/API/Blob) は、処理される生データを含むオブジェクトであり、リソースにアクセスするために blob URL を生成できます。トップレベル コンテキストで任意の Blob URL に移動するユースケースをサポートするために（[ディスカッション](https://github.com/w3c/FileAPI/issues/153)）、Blob URL ストアはトップレベル サイトではなくエージェント クラスターによってパーティションされます。この機能はまだテストできません。また、パーティションの仕組みが今後変更される可能性があります。
```

2022-09-20 03:30 UTC, agektmr commented on site/ja/docs/privacy-sandbox/storage-partitioning/index.md
> +[Broadcast Channel](/blog/broadcastchannel/) : Broadcast Channel API を使用すると、[ブラウジング コンテキスト](https://developer.mozilla.org/docs/Glossary/Browsing_context)（ウィンドウ、タブ、または iframe）と同じオリジンのワーカー間の通信が可能になります。
```suggestion
[Broadcast Channel](/blog/broadcastchannel/)
:   Broadcast Channel API を使用すると、[ブラウジング コンテキスト](https://developer.mozilla.org/docs/Glossary/Browsing_context)（ウィンドウ、タブ、または iframe）と同じオリジンのワーカー間の通信が可能になります。
:   コンテキスト間の関係が明確に定義されているクロスサイト iframe の `postMessage()` は、変更が提案されていません。
```

2022-09-20 03:30 UTC, agektmr commented on site/ja/docs/privacy-sandbox/storage-partitioning/index.md
> +[SharedWorker](https://developer.mozilla.org/docs/Web/API/SharedWorker) : SharedWorker API は、同一オリジンのブラウジング コンテキスト間でアクセスできるワーカーを提供します。
```suggestion
[SharedWorker](https://developer.mozilla.org/docs/Web/API/SharedWorker)
:   SharedWorker API は、同一オリジンのブラウジング コンテキスト間でアクセスできるワーカーを提供します。
```

2022-09-20 03:30 UTC, agektmr commented on site/ja/docs/privacy-sandbox/storage-partitioning/index.md
> +[Web Locks](https://developer.mozilla.org/docs/Web/API/Web_Locks_API) : Web Locks API を使用すると、同一オリジンの 1 つのタブまたはワーカーで実行されているコードが、何らかの作業の実行中に共有リソースのロックを取得できます。
```suggestion
[Web Locks](https://developer.mozilla.org/docs/Web/API/Web_Locks_API)
:   Web Locks API を使用すると、同一オリジンの 1 つのタブまたはワーカーで実行されているコードが、何らかの作業の実行中に共有リソースのロックを取得できます。
```

2022-09-20 06:06 UTC, ilyaspiridonov commented
> It would be nice if GitLocalize support [definition lists](https://kramdown.gettalong.org/syntax.html#definition-lists)

Hmm, interesting. We'll take a look into this, thanks!

2022-09-20 06:58 UTC, agektmr approved these changes
LGTM

2022-09-20 06:58 UTC, merged