Create new upgrade section.
GoogleChrome/developer.chrome.com pull request #3859
Opened 2022-09-28 19:35 UTC by jpmedley

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

2022-10-06 14:51 UTC, AmySteam requested changes
This looks good! 👍 I think it's a great improvement.

Just a couple of edits, but otherwise LGTM 💯

2022-10-06 14:51 UTC, AmySteam commented on site/en/docs/extensions/mv3/mv3-migration-checklist/index.md
> +make to an Manifest V2 extension so that it works under Manifest V3. For
```suggestion
make to a Manifest V2 extension so that it works under Manifest V3. For
```

2022-10-06 14:51 UTC, AmySteam commented on site/en/docs/extensions/mv3/mv3-migration-checklist/index.md
> +This sectrion lists changes you may need to make based on changes to the API surface.
```suggestion
This section lists changes you may need to make based on changes to the API surface.
```

2022-10-06 14:51 UTC, AmySteam commented on redirects.yaml
> +
Good catch on adding a redirect! 👍

2022-10-07 18:45 UTC, jpmedley commented
@devnook, please help. I'm getting an eleventy error that seems to have nothing to do with my PR.

2022-10-07 18:53 UTC, devnook commented
Do you mean that the tests are broken, or that the build is not working for you? If tests - this is known issue and should be fixed here: https://github.com/GoogleChrome/developer.chrome.com/pull/3928. Once this PR gets merged and this PR is rebased to main, it should be fixed. does that help?

2022-10-07 19:54 UTC, jpmedley commented
The build is working fine. I just didn't want to merge anything that would break the site.

2022-10-10 14:51 UTC, AmySteam approved these changes

2022-10-12 22:31 UTC, merged