Partial Custom Tabs update
GoogleChrome/developer.chrome.com pull request #4082
Opened 2022-10-21 16:05 UTC by IanStanion-google

Added new content related to new Partial Custom Tabs documentation

Changes proposed in this pull request:

- Implemented proposed changes to the Overview page for Custom Tabs
- Implemented proposed changes to the Integration Guide page for Custom Tabs
- Implemented proposed changes to the Headers page for Custom Tabs

2022-10-22 00:35 UTC, ali-spivak approved these changes

2022-10-22 00:38 UTC, ali-spivak approved these changes

2022-10-24 15:06 UTC, jpmedley requested changes
This is a nice bit of writing. Most of my comments relate to norms and best practices of writing and technical writer that we need to start following. 

Let me know if you have any questions.

2022-10-24 15:06 UTC, jpmedley commented on site/en/docs/android/custom-tabs/integration-guide/index.md
> +Partial Custom Tabs will inherit the host app's color scheme for the UI components above. You will be responsible for ensuring visual consistency for these components before launching a Partial Custo
>UI components above

Which UI components are you talking about? The last thing I saw was a couple of properties. Please clarify this.

2022-10-24 15:06 UTC, jpmedley commented on site/en/docs/android/custom-tabs/integration-guide/index.md
> +These new APIs are available from Chrome M107 and onwards.
```suggestion
These new APIs are available from Chrome 107 and onwards.
```

2022-10-24 15:06 UTC, jpmedley commented on site/en/docs/android/custom-tabs/integration-guide/index.md
> +* Called when Custom Tab is resized in its height. This is applicable when users resize a
```suggestion
* Called when Custom Tab's height is resized. This applies when users resize a 
```

2022-10-24 17:02 UTC, jpmedley approved these changes

2022-10-24 17:03 UTC, merged