CWS Support Visibility Option UI change documented
GoogleChrome/developer.chrome.com pull request #4180
Opened 2022-11-02 14:50 UTC by IanStanion-google

Changes proposed in this pull request:

- Updated description and screenshots of the CWS dashboard UI regarding the new  changes to the Support Visibility option.

2022-11-02 15:52 UTC, jpmedley commented
@dasli Is this factually correct? The text needs to be right before I verify that the commas in the right place.

2022-11-07 18:04 UTC, dasli approved these changes
LGTM

2022-11-07 18:05 UTC, IanStanion-google commented
@jpmedley Okay content approved by David! Feel free to do any writing-polish critique, and I will implement asap!

2022-11-07 20:49 UTC, dotproto commented on site/en/docs/webstore/manage/index.md
> +The Support Visibility option switch is located in the Chrome Web Store Developer Dashboard, in the Support Tab section of Account Options.
ATM a single line break causes the text to render with a `<br>` inserted between the lines. We should either remove the line break to make this a single paragraph or add another line break to make "The Support Visibility option…" a distinct paragraph.

```suggestion
Having a Support section on your extension's Chrome Web Store page allows users to easily report issues and suggest new features separately from leaving a review. To enable user feedback on your extension, the Support Visibility option must be switched on.

The Support Visibility option switch is located in the Chrome Web Store Developer Dashboard, in the Support Tab section of Account Options.
```

**Current rendering**

![Screen Shot 2022-11-07 at 12 42 32 PM](https://user-images.githubusercontent.com/1047763/200412460-77e23778-b3b6-44cb-a4e0-e05e1a9ff7c2.png)

2022-11-07 20:50 UTC, dotproto approved these changes
Minor formatting issue to clean up, but other than that it looks good.

2022-11-07 21:24 UTC, jpmedley requested changes
The paragraph over all is an improvement. The suggestions I've made are best practices for documentation.

2022-11-07 21:24 UTC, jpmedley commented on site/en/docs/webstore/manage/index.md
> +Having a Support section on your extension's Chrome Web Store page allows users to easily report issues and suggest new features separately from leaving a review. To enable user feedback on your exte
```suggestion
Having a Support section on your extension's Chrome Web Store page allows users to easily report issues and suggest new features separately from leaving a review. To enable user feedback on your extension, the Visibility option (located in the Support tab area) must be switched on.   
```

2022-11-07 21:24 UTC, jpmedley commented on site/en/docs/webstore/manage/index.md
> +Having a Support section on your extension's Chrome Web Store page allows users to easily report issues and suggest new features separately from leaving a review. To enable user feedback on your exte
Please always be strict about referring to things exactly as they're named in the interface.

2022-11-07 21:24 UTC, jpmedley commented on site/en/docs/webstore/manage/index.md
> +{% Img src="image/6AZNJBRnkpQUWTKPzig99lQY8jT2/3h8A6IglCHjMN4uncopz.png", alt="Support Visibility option", width="800", height="239" %}
```suggestion
{% Img src="image/6AZNJBRnkpQUWTKPzig99lQY8jT2/3h8A6IglCHjMN4uncopz.png", alt="Visibility option", width="800", height="239" %}
```

2022-11-07 21:24 UTC, jpmedley commented on site/en/docs/webstore/manage/index.md
> +{% Img src="image/6AZNJBRnkpQUWTKPzig99lQY8jT2/3h8A6IglCHjMN4uncopz.png", alt="Support Visibility option", width="800", height="239" %}
Please don't use screen captures that are unreadable. Cutting off the help doesn't hurt at all. I'd suggest something like this. Feel free to use it. 

![SupportTab](https://user-images.githubusercontent.com/8204171/200418358-5086328c-4c35-4b17-8537-baf4097911ee.png)

2022-11-10 17:27 UTC, IanStanion-google commented
@jpmedley This is cleaned up now, please approve or let me know if you notice anything else!

2022-11-10 18:49 UTC, jpmedley approved these changes

2022-11-10 18:50 UTC, merged