Reduced friction for CUJ "I want to know about the supported manifest keys"
GoogleChrome/developer.chrome.com pull request #4255
Opened 2022-11-10 14:03 UTC by AmySteam

Fixes #4254

Changes proposed in this pull request:

- Remove keys for internal use only 
- Add links to missing docs (PR#TBD, PR#TBD)
- Add code samples to all manifest key pages
- Standardize format for all keys : "key name and link": "key type"
  - For example: "[action](https://developer.chrome.com/docs/extensions/reference/action/)": {...},

TODOS:
- [ ] Add missing pages
- [ ] Audit some pages for accuracy (waiting on SMEs response)

**Staged links**

2022-11-14 18:38 UTC, jpmedley commented
@AmySteam Did you find anything in here that should be mentioned in the upgrade materials?

2022-11-14 20:35 UTC, AmySteam commented
@jpmedley Not really. Mostly cleaned up broken links and removed mentions of Chrome apps.

2022-11-17 14:51 UTC, jpmedley commented
@AmySteam, if this is ready for fact checking, please assign it to @dotproto.

Thanks

2022-11-28 17:26 UTC, jpmedley requested changes

2022-11-28 17:26 UTC, jpmedley commented on site/en/docs/extensions/mv3/manifest/key/index.md
> +This value can be used to maintain the unique ID of an extension, or theme when it is loaded
```suggestion
This value maintains the unique ID of an extension, or theme when it is loaded
```

2022-11-28 17:26 UTC, jpmedley commented on site/en/docs/extensions/mv3/manifest/key/index.md
> +This value can be used to maintain the unique ID of an extension, or theme when it is loaded
Omit needless words.

Would 'stores' be a better verb?

2022-12-01 18:57 UTC, AmySteam commented
Hey @dotproto, this is ready for a technical review; I assigned it to you 🙂

2022-12-16 18:45 UTC, jpmedley approved these changes

2022-12-16 20:50 UTC, merged