DevTools 108 > CSS hints + new doc on CSS issues
GoogleChrome/developer.chrome.com pull request #4330
Opened 2022-11-17 18:10 UTC by sofiayem

Documented https://developer.chrome.com/blog/new-in-devtools-108/#css-hint

Also, created a new doc that explains how the Styles pane shows invalid, overridden, inactive, inherited, shorthand, and non-editable CSS.

Publish on Nov 29.

2022-11-18 14:15 UTC, jecfish commented on site/en/docs/devtools/css/issues/index.md
> +{% Video src="video/NJdAV9UgKuN8AhoaPBquL7giZQo1/BNlYQHj8tpojjxyMKNDv.mp4", autoplay=false, controls=true, loop=true, class="screenshot" %}
How about skip the navigation, or explain it with an image?

2022-11-18 14:24 UTC, jecfish commented on site/en/docs/devtools/css/issues/index.md
> +The **Styles** pane crosses out properties that are valid but have no effect because of other properties. Such properties have {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/2OyGRodvgk9neTIEAH4g.svg"
Which properties do `Such properties` referring to? Is that the cross-out prop or the pale prop? Suggest to make the sentence to call them out clearer.

Suggest to explain the example.

2022-11-18 15:00 UTC, jecfish requested changes
Thanks for this write-up! You gave me idea on the upcoming CSS tip.

2022-11-18 18:46 UTC, rachelandrew approved these changes

2022-11-21 22:19 UTC, jecfish approved these changes
LGTM overall % a few comments

2022-11-21 22:19 UTC, jecfish commented on site/en/docs/devtools/css/reference/index.md
> +### View invalid, overridden, inactive, and other CSS {: #css-issues }
Looking at the CSS class names, some classes are grey out as well. Should we explain it in this docs?

![ScreenFlow](https://user-images.githubusercontent.com/5917927/203169422-0040f9f4-57af-4607-98b8-9deacc99f8c7.gif)

2022-11-30 13:27 UTC, merged