Fix links for author detail pages and add Mastodon
GoogleChrome/developer.chrome.com pull request #4336
Opened 2022-11-18 11:31 UTC by matthiasrohmer

Currently author detail pages do not render links maintained in authorsData.json as they are not passed through to the collection that renders those pages.

**Before**
![image](https://user-images.githubusercontent.com/12857772/202695690-6473932a-eb7b-4587-b6e6-65a260429bed.png)

**After**
![image](https://user-images.githubusercontent.com/12857772/202695783-b19e0447-f9ec-482f-b2ed-504cc2d596d5.png)

Additionally this PR adds the possibility to add Mastodon links for authors.

2022-11-18 15:19 UTC, devnook approved these changes

2022-11-18 15:21 UTC, devnook requested changes
ah sorry - deleted twitter icon 24x24 made that the twitter link from homepage footer disappeared - ptal

2022-11-21 09:13 UTC, tunetheweb commented on site/_data/authorsData.json
> +    "mastodon": "https://mastodon.online/@tunetheweb",
I moved:

```suggestion
    "mastodon": "https://webperf.social/@tunetheweb",
```

2022-11-21 10:01 UTC, matthiasrohmer commented
@devnook, thanks for spotting! That was why it was so weirdly sized compared to the other social icons... fixed by adding the explicit width and height back in for Twitter.

2022-11-21 10:15 UTC, devnook approved these changes

2022-11-21 10:15 UTC, merged

2022-11-21 14:55 UTC, Aizmansor commented
Dihantar daripada telefon saya-------- Mesej asal --------Daripada: Matthias Rohmer ***@***.***>Tarikh: Isn, 21 Nov 2022, 6:16 PTGKepada: "GoogleChrome/developer.chrome.com" ***@***.***>Sk: Faizul mansor ***@***.***>, Manual ***@***.***>Tajuk: Re: [GoogleChrome/developer.chrome.com] Fix links for author detail pages and add Mastodon (PR #4336)
Merged #4336 into main.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>