updates to riui for desktop launch
GoogleChrome/developer.chrome.com pull request #4523
Opened 2022-12-05 22:36 UTC by tropicadri

With the launch of richer install ui this article needs updates.

2022-12-06 08:24 UTC, beaufortfrancois commented on site/en/blog/richer-pwa-installation/index.md
> +This UI works in M94 on Android, and M108 on desktop.
Shall we link to your upcoming article for the `M108 on desktop` part?

2023-04-18 07:28 UTC, rachelandrew requested changes

2023-04-18 07:28 UTC, rachelandrew commented on site/en/blog/richer-pwa-installation/index.md
> +This UI works in M94 on Android, and [M108 on desktop](/blog/richer-install-ui-desktop/).
```suggestion
This UI works from Chrome 94 on Android, and [Chrome 108 on desktop](/blog/richer-install-ui-desktop/).
```

2023-04-18 07:28 UTC, rachelandrew commented on site/en/blog/richer-pwa-installation/index.md
> +To display the richer install ui dialog developers need to add at least one screenshot for the corresponding form factor in the `screenshots` array. The `description` field is not required but it is
```suggestion
To display the richer install UI dialog developers need to add at least one screenshot for the corresponding form factor in the `screenshots` array. The `description` field is not required but it is recommended. The content dialog is built using the content of the `screenshots` and `description` fields to make the experience more similar to an app store install. This UI helps users identify they are adding an app to their device, and with more space available developers can provide specific context to their users at install time.
```

2023-04-18 07:28 UTC, rachelandrew commented on site/en/blog/richer-pwa-installation/index.md
>    {% Img src="image/xizoeLGxYNf3VLUHc5BsIoiE1Af1/RoQRxu3CPkKvAtkxYsAQ.jpeg", alt="Example of bottomsheet UI in Chrome", width="360", height="720" %}
```suggestion
  {% Img src="image/xizoeLGxYNf3VLUHc5BsIoiE1Af1/RoQRxu3CPkKvAtkxYsAQ.jpeg", alt="Example of bottomsheet UI in Chrome.", width="360", height="720" %}
```

2023-04-18 07:28 UTC, rachelandrew commented on site/en/blog/richer-pwa-installation/index.md
>  alt="Richer Install UI Expanded", width="342", height="722" %}
```suggestion
alt="Richer Install UI Expanded.", width="342", height="722" %}
```

2023-04-18 07:28 UTC, rachelandrew commented on site/en/blog/richer-pwa-installation/index.md
>  alt="Richer Install UI Collapsed", width="342", height="722" %}
```suggestion
alt="Richer Install UI Collapsed.", width="342", height="722" %}
```

2023-04-19 17:04 UTC, rachelandrew approved these changes

2023-04-19 19:33 UTC, merged