Manifest-key-declarativeNetRequest
GoogleChrome/developer.chrome.com pull request #4603
Opened 2022-12-12 14:16 UTC by IanStanion-google

Implements the manifest key documentation for  declarativeNetRequest

Changes proposed in this pull request:
Addresses the following issues
-https://github.com/GoogleChrome/developer.chrome.com/issues/4324
-https://github.com/GoogleChrome/developer.chrome.com/issues/4323
-https://github.com/GoogleChrome/developer.chrome.com/issues/639
-https://github.com/GoogleChrome/developer.chrome.com/issues/2113
-https://github.com/GoogleChrome/developer.chrome.com/issues/3470
-https://github.com/GoogleChrome/developer.chrome.com/issues/3748

2023-01-05 04:30 UTC, datvm commented
Is this the final version? The [current build](https://deploy-preview-4603--developer-chrome-com.netlify.app/docs/extensions/reference/declarativeNetRequest#interaction-with-cached-pages) I am seeing, the cached behavior is empty but #3748 is closed:

![image](https://user-images.githubusercontent.com/6388546/210701948-b8c2acf2-e1cc-4efc-8152-ee0ae8b1bdbb.png)

2023-01-13 17:08 UTC, oliverdunk requested changes
Left a few comments but overall these are some super helpful changes :)

2023-01-17 20:24 UTC, jpmedley commented
Guys,

Here's the best practice for how this should work. When Ian has addressed the items in your review pass, approve the PR using the GitHub mechanism (the green button on the Files changed tab). If you find additional problems as you're reviewing, open a ticket. I'll do the copy edit pass after that.

Thanks,
Joe

@IanStanion-google @oliverdunk

2023-01-18 02:11 UTC, dotproto requested changes
Ian and I did a verbal review over video chat. There were a handful of items that need to be double checked with the relevant Chromium engineer, a few items that need to be clarified, but by and large we're on a good path with this update. Thanks again for your work on this, @IanStanion-google!

2023-01-23 17:17 UTC, jpmedley commented on site/en/docs/extensions/mv3/manifest/declarativeNetRequest/index.md
> +It must be noted that extensions cannot clear the browser's Cache Storage or Service Worker registrations automatically. When enabling an extension using `declarativeNetRequest` rules to block certai
Is this talking about the web platform's [`Cache` API](https://developer.mozilla.org/en-US/docs/Web/API/Cache) and web service workers? That needs to be clarified.

2023-01-23 18:27 UTC, jpmedley commented on site/en/docs/extensions/reference/declarativeNetRequest/index.md
> +When rules are applied to browsers with pages in the service worker's cached storage, the browser may ignore the set rule for those specific pages until the cached storage is cleared. This is because
It's my understanding that there is only one service worker per extension.

2023-01-23 18:57 UTC, oliverdunk commented on site/en/docs/extensions/reference/declarativeNetRequest/index.md
> +When rules are applied to browsers with pages in the service worker's cached storage, the browser may ignore the set rule for those specific pages until the cached storage is cleared. This is because
I think this is talking about web service workers (which may cache responses in a way that it never reaches the extension) and not the single extension service worker 😅

2023-01-24 15:03 UTC, jpmedley commented on site/en/docs/extensions/reference/declarativeNetRequest/index.md
> +When rules are applied to browsers with pages in the service worker's cached storage, the browser may ignore the set rule for those specific pages until the cached storage is cleared. This is because
@IanStanion-google I wouldn't make a blanket statement such as 'avoid saying the service worker'. 'A service worker seems like a correct choice for this context. 

Can we move this forward now?

2023-01-24 15:06 UTC, IanStanion-google commented
@jpmedley 
All standing feedback has been addressed. Can you do a quick copy-review pass?

2023-01-24 15:55 UTC, jpmedley commented
@oliverdunk, If you are satisfied, please LGTM using GitHub.

2023-01-24 17:16 UTC, oliverdunk commented on site/en/docs/extensions/mv3/manifest/declarativeNetRequest/index.md
> +It must be noted that extensions cannot clear the browser's Cache Storage or Service Worker registrations automatically. When enabling an extension using `declarativeNetRequest` rules to block certai
I think there's value in giving developers more guidance here but I think the wording as it stands is ok for now.

@jpmedley - I think we're potentially talking about every kind of cache here. More testing is needed but I assume the HTTP cache, Cache API and any other type of caching could all cause extension developers trouble.

2023-01-24 17:16 UTC, oliverdunk approved these changes
LGTM 👍

2023-01-24 18:30 UTC, IanStanion-google commented on site/en/docs/extensions/mv3/manifest/declarativeNetRequest/index.md
> +It must be noted that extensions cannot clear the browser's Cache Storage or Service Worker registrations automatically. When enabling an extension using `declarativeNetRequest` rules to block certai
This is a question Simeon advised I wait on an answer from Kelvin for full accuracy. Working on getting an answer.

2023-01-24 19:11 UTC, jpmedley commented on site/en/docs/extensions/mv3/manifest/declarativeNetRequest/index.md
> +updated:
We comment `updated` or leave it out entirely. Leaving it in might throw a build error.

2023-01-24 19:15 UTC, jpmedley commented on site/en/docs/extensions/mv3/manifest/declarativeNetRequest/index.md
> +An optional manifest key and permission enabling the use of the [declarativeNetRequest API](/docs/extensions/reference/declarativeNetRequest/). Using `declarativeNetRequest`, you can block or modify
```suggestion
An optional manifest key and permission enabling the [declarativeNetRequest API](/docs/extensions/reference/declarativeNetRequest/). Using `declarativeNetRequest`, you can block or modify network requests by specifying declarative rules. This lets extensions modify network requests without intercepting them and viewing their content, providing more privacy. Runtime modification and registration of declarativeNetRequest rules can be done with only the permission requested, without the need for the full manifest key implementation.
```

2023-01-24 19:18 UTC, jpmedley commented on site/en/docs/extensions/mv3/manifest/requirements/index.md
> +updated: 2022-11-15
Changing the date back since nothing was updated in this file.

2023-01-24 19:23 UTC, jpmedley commented on site/en/docs/extensions/mv3/mv3-migration/index.md
> +  extensions.
This makes it sound like dNR can be used with MV2. That's because If I'm doing MV3, I can't use webRequest. What am I missing?

2023-01-24 19:27 UTC, jpmedley commented on site/en/docs/extensions/reference/declarativeNetRequest/index.md
> +When an extension uses declarativeNetRequest APIs to redirect a public resource request to a resource that is not web accessible, it is blocked and will result in a net::ERR_UNSAFE_REDIRECT error. Th
>net::ERR_UNSAFE_REDIRECT

This looks like C++ syntax, which means an extension developer will never see this string. This needs to be stated in terms of what an extension developer will see.

2023-01-24 19:30 UTC, jpmedley commented on site/en/docs/extensions/reference/declarativeNetRequest/index.md
> +When an extension uses declarativeNetRequest APIs to redirect a public resource request to a resource that is not web accessible, it is blocked and will result in a net::ERR_UNSAFE_REDIRECT error. Th
```suggestion
When an extension uses declarativeNetRequest APIs to redirect a public resource request to a resource that is not web accessible, it is blocked and will result in a net::ERR_UNSAFE_REDIRECT error. The above holds true even if the resource that is not web accessible is owned by the redirecting extension. To declare resources for use with declarativeNetRequest APIs, populate the [`"web_accessible_resources"`](/docs/extensions/mv3/manifest/web_accessible_resources/) array.
```

2023-01-24 19:31 UTC, jpmedley commented on site/en/docs/extensions/reference/declarativeNetRequest/index.md
> +When an extension uses declarativeNetRequest APIs to redirect a public resource request to a resource that is not web accessible, it is blocked and will result in a net::ERR_UNSAFE_REDIRECT error. Th
This does three things:
* Says it with fewer words.
* Changes it from active to passive voice.
* Makes the link sef-descriptive.

2023-01-24 19:32 UTC, jpmedley commented on site/en/docs/extensions/reference/webRequest/index.md
> +When an extension uses webRequest APIs to redirect a public resource request to a resource that is not web accessible, it is blocked and will result in a net::ERR_UNSAFE_REDIRECT error. The above hol
I have the same comments as listed above.

2023-02-08 16:05 UTC, jpmedley commented
@IanStanion-google This is getting a little old. Can you please respond to my comments so that we can get this out.

2023-02-09 22:03 UTC, jpmedley approved these changes

2023-02-09 23:25 UTC, merged