Document replay extensions for DevTools Recorder
GoogleChrome/developer.chrome.com pull request #5135
Opened 2023-02-03 06:47 UTC by OrKoN

Changes proposed in this pull request:

- Documents the latest additions to the Recorder extension API

2023-02-03 06:53 UTC, OrKoN commented
@jecfish PTAL https://pr-5135-static-dot-dcc-staging.uc.r.appspot.com/docs/extensions/reference/devtools_recorder

2023-02-03 08:59 UTC, jecfish requested changes

2023-02-03 09:08 UTC, jecfish approved these changes

2023-02-03 09:10 UTC, jecfish commented
Approve the content. Request a tech writer review, as sofia is OOO. @AaronForinton

2023-02-03 09:10 UTC, OrKoN commented on site/en/docs/extensions/reference/devtools_recorder/index.md
> +
Thanks a bunch!

2023-02-03 11:14 UTC, AaronForinton approved these changes

2023-02-03 11:15 UTC, AaronForinton commented
@jecfish Approved and ready to merge.

2023-02-06 09:26 UTC, jecfish commented on site/en/docs/extensions/reference/devtools_recorder/index.md
> +## Export plugin example
```suggestion
## Export plugin example 
```

2023-02-06 09:44 UTC, merged