Adds upcoming events to /meet-the-team
GoogleChrome/developer.chrome.com pull request #5189
Opened 2023-02-07 14:30 UTC by johnrich85

Changes proposed in this pull request:

Adds upcoming events to /meet-the-team

2023-02-10 10:43 UTC, rachelandrew requested changes
Just a bit of copyediting, also I know that An Event Apart is not happening as the event series has closed down. So we should remove this one.

2023-02-10 10:43 UTC, rachelandrew commented on site/en/meet-the-team/events/city-js-london-2023/index.md
> +  TypeScript, Testing, and more.
```suggestion
  A JavaScript festival focused on JavaScript frameworks, NodeJS,
  TypeScript, testing, and more.
```

2023-02-10 10:43 UTC, rachelandrew commented on site/en/meet-the-team/events/city-js-london-2023/index.md
> +      about the motivation of WebDriver BiDi – the upcoming browser automation protocol.
```suggestion
      about the motivation of WebDriver BiDi–the upcoming browser automation protocol.
```

2023-02-10 10:43 UTC, rachelandrew commented on site/en/meet-the-team/events/selenium-conf-2023/index.md
> +  SeleniumConf brings together Selenium and WebDriver ecosystem developers &
```suggestion
  SeleniumConf brings together Selenium and WebDriver ecosystem developers and
```

2023-02-10 10:43 UTC, rachelandrew commented on site/en/meet-the-team/events/smashingconf-freiburg-2023/index.md
> +  accessibility, CSS, JavaScript, web performance and cutting-edge techniques.
```suggestion
  The 11th SmashingConf Freiburg—all about front-end, UX and design—for
  front-end developers and designers. With adventures into design systems,
  accessibility, CSS, JavaScript, web performance and cutting-edge techniques.
```

2023-02-10 12:00 UTC, Bryan679 commented
Here are some times that work for me:


Friday, February 10, 2023



1:00 AM - 1:30 AM (GMT-8)



9:30 AM - 10:00 AM (GMT-8)




Made easy by Outlook<https://aka.ms/Dcupce>




Sent from my Boost Samsung Galaxy A03s
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Rachel Andrew ***@***.***>
Sent: Friday, February 10, 2023 2:44:00 AM
To: GoogleChrome/developer.chrome.com ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [GoogleChrome/developer.chrome.com] Adds upcoming events to /meet-the-team (PR #5189)


@rachelandrew requested changes on this pull request.

Just a bit of copyediting, also I know that An Event Apart is not happening as the event series has closed down. So we should remove this one.

________________________________

In site/en/meet-the-team/events/city-js-london-2023/index.md<https://github.com/GoogleChrome/developer.chrome.com/pull/5189#discussion_r1102590981>:

> +  A JavaScript festival focused on JS frameworks, NodeJS,

+  TypeScript, Testing, and more.



⬇️ Suggested change

-  A JavaScript festival focused on JS frameworks, NodeJS,

-  TypeScript, Testing, and more.

+  A JavaScript festival focused on JavaScript frameworks, NodeJS,

+  TypeScript, testing, and more.



________________________________

In site/en/meet-the-team/events/city-js-london-2023/index.md<https://github.com/GoogleChrome/developer.chrome.com/pull/5189#discussion_r1102591522>:

> +  TypeScript, Testing, and more.

+image: image/fuiz5I8Iv7bV8YbrK2PKiY3Vask2/6mj7t7rHxZ5Vs31fWoSs.jpg

+location: London, UK

+date: 2023-03-28

+externalUrl: https://cityjsconf.org/

+sessions:

+  - speaker: jecelynyeen

+    title: How browser automation works behind the scenes?

+    description: >-

+      If you have ever worked with browser automation, you know how overwhelming it can

+      be. Why is browser automation hard? How can the browser vendors improve the

+      fundamentals of browser automation?

+

+      In this talk, Jecelyn will walk you through the current state of cross-browser

+      automation, unfold how browser automation works behind the scenes, and share

+      about the motivation of WebDriver BiDi – the upcoming browser automation protocol.



⬇️ Suggested change

-      about the motivation of WebDriver BiDi – the upcoming browser automation protocol.

+      about the motivation of WebDriver BiDi–the upcoming browser automation protocol.



________________________________

In site/en/meet-the-team/events/selenium-conf-2023/index.md<https://github.com/GoogleChrome/developer.chrome.com/pull/5189#discussion_r1102591873>:

> @@ -0,0 +1,20 @@

+---

+title: Selenium Conference

+summary: >-

+  SeleniumConf brings together Selenium and WebDriver ecosystem developers &



⬇️ Suggested change

-  SeleniumConf brings together Selenium and WebDriver ecosystem developers &

+  SeleniumConf brings together Selenium and WebDriver ecosystem developers and



________________________________

In site/en/meet-the-team/events/smashingconf-freiburg-2023/index.md<https://github.com/GoogleChrome/developer.chrome.com/pull/5189#discussion_r1102592663>:

> +  The 11th SmashingConf Freiburg - all about front-end, UX and design - for

+  front-end developers and designers. With adventures into design systems,

+  accessibility, CSS, JavaScript, web performance and cutting-edge techniques.



⬇️ Suggested change

-  The 11th SmashingConf Freiburg - all about front-end, UX and design - for

-  front-end developers and designers. With adventures into design systems,

-  accessibility, CSS, JavaScript, web performance and cutting-edge techniques.

+  The 11th SmashingConf Freiburg—all about front-end, UX and design—for

+  front-end developers and designers. With adventures into design systems,

+  accessibility, CSS, JavaScript, web performance and cutting-edge techniques.



—
Reply to this email directly, view it on GitHub<https://github.com/GoogleChrome/developer.chrome.com/pull/5189#pullrequestreview-1292899431>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A5QQWSZ5YBLT4TWXCR5UMJLWWYLXBANCNFSM6AAAAAAUUBHZG4>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-02-15 18:31 UTC, rachelandrew approved these changes

2023-02-22 15:03 UTC, merged