Add chinese translation
GoogleChrome/developer.chrome.com pull request #5294
Opened 2023-02-15 11:16 UTC by louisyoong

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

2023-02-15 11:17 UTC, louisyoong commented
Add chinese translation

2023-02-15 13:09 UTC, jecfish requested changes

2023-02-15 13:09 UTC, jecfish commented on site/zh/blog/new-in-devtools-110/index.md
>  draft: true
```suggestion
```

2023-02-15 13:09 UTC, jecfish commented on site/zh/blog/new-in-devtools-110/index.md
Please translate the `site/zh/_partials/devtools/whats-new.md` file as well!

2023-03-11 09:08 UTC, jecfish approved these changes

2023-03-11 10:05 UTC, AaronForinton approved these changes

2023-03-11 10:28 UTC, merged