Update W.A.R. page
GoogleChrome/developer.chrome.com pull request #539
Opened 2021-03-18 17:52 UTC by awfuchs

Update [web accessible resources page](https://developer.chrome.com/docs/extensions/mv3/manifest/web_accessible_resources/) for MV3.

2021-03-23 06:14 UTC, dotproto requested changes

2021-03-23 14:22 UTC, awfuchs commented on site/en/docs/extensions/mv3/manifest/web_accessible_resources/index.md
> +{% endAside %}
I had considered and rejected that, but will keep thinking about this.

2021-03-23 16:50 UTC, solomonkinard approved these changes
lgtm % nit

2021-03-23 16:50 UTC, solomonkinard commented on site/en/docs/extensions/mv3/manifest/web_accessible_resources/index.md
> +      "use_dynamic_url": true
sg

2021-03-25 02:20 UTC, dotproto approved these changes
Nit suggestion. We'll need to come back to this page soon anyway.

LGTM!

2021-03-25 02:20 UTC, dotproto commented on site/en/docs/extensions/mv3/manifest/web_accessible_resources/index.md
> +  <dd>A list of extension IDs, specifying which extensions can access the resources.</dd>
```suggestion
  <dt><code>resources</code></dt>
  <dd>An array of resources to be exposed. Resources are specified as strings and may contain
  <code>*</code> for wildcard matches. For example, <code>"/images/*"</code> exposes everything in
  the extension's /images directory recursively while <code>"*.png"</code> exposes all PNG
  files.</dd>
  <dt><code>matches</code></dt>
  <dd>A list of URL match patterns specifying which pages can access the resources. Only the origin
  is used to match URLs; subdomains patterns (<code>*.google.com<code>) and paths are ignored.</dd>
  <dt><code>extensions</code></dt>
  <dd>A list of extension IDs, specifying which extensions can access the resources.</dd>
```

Replaces backticks with `<code>` tags, wraps at 100 characters, and clarifies wildcard behavior.

2021-03-25 02:27 UTC, merged