Add/update Offscreen Documents entries in What's New/Known Issues
GoogleChrome/developer.chrome.com pull request #5604
Opened 2023-03-09 13:39 UTC by oliverdunk

Fixes the Chrome version mentioned in Known Issues, and adds a What's New entry. I've intentionally back-dated the What's New since it's been out for a while, and I also wanted to line it up with the blog post.

2023-03-09 17:43 UTC, AmySteam approved these changes
LGTM! Thanks @oliverdunk 💯

2023-03-10 00:12 UTC, jpmedley requested changes

2023-03-10 00:12 UTC, jpmedley commented on site/en/docs/extensions/whatsnew/index.md
> +Offscreen documents are now available on the stable channel. These provide support for DOM-related features and APIs in Manifest V3. For more information, [read the blog post](/blog/Offscreen-Documen
```suggestion
Offscreen documents are now available in extensions. These provide support for DOM-related features and APIs in Manifest V3. For more information, [read the blog post](/blog/Offscreen-Documents-in-Manifest-v3/).
```

2023-03-10 00:12 UTC, jpmedley commented on site/en/docs/extensions/whatsnew/index.md
> +Offscreen documents are now available on the stable channel. These provide support for DOM-related features and APIs in Manifest V3. For more information, [read the blog post](/blog/Offscreen-Documen
Generally, we probably don't need to say channel unless we want to call out a specific channel earlier than stable.

Can you please add something about this helping transition from background pages to service workers, something like what the first line of Ian's article says.

2023-03-10 18:31 UTC, jpmedley approved these changes
@oliverdunk, Please forgive me. I'm going to merge this. I suddenly have more for 'What's New' than I know what to do with. I need to get the next item queued for Monday.

2023-03-10 18:31 UTC, merged