Update Chinese translation for chrome 112
GoogleChrome/developer.chrome.com pull request #5636
Opened 2023-03-12 05:39 UTC by aquaMAX

Fixes #5602 

Changes proposed in this pull request:

Updated files
- [site/zh/blog/new-in-devtools-112/index.md](https://github.com/GoogleChrome/developer.chrome.com/compare/main...aquaMAX:developer.chrome.com:main?diff=split#diff-50e8500849bfaa6415f083e38d6f1ec8ac79cb7c8bdfc0e8ab8c687913bd99da)
- [site/zh/blog/new-in-devtools-112/index.md](https://github.com/GoogleChrome/developer.chrome.com/compare/main...aquaMAX:developer.chrome.com:main?diff=split#diff-50e8500849bfaa6415f083e38d6f1ec8ac79cb7c8bdfc0e8ab8c687913bd99da)

@jecfish ready for review

2023-03-12 07:41 UTC, jecfish requested changes

2023-03-12 07:41 UTC, jecfish commented on site/zh/_partials/devtools/whats-new.md
> +* [样式面板中的 CSS 文档](/zh/blog/new-in-devtools-112/#css)
```suggestion
* [样式边栏中的 CSS 文档](/zh/blog/new-in-devtools-112/#css)
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/_partials/devtools/whats-new.md
> +* [JavaScript Profiler 开始弃用](/zh/blog/new-in-devtools-112/#js-profiler-deprecation)
```suggestion
* [JavaScript 性能剖析器开始弃用](/zh/blog/new-in-devtools-112/#js-profiler-deprecation)
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +要根据您的需要自定义 **记录器** 并将其与您的工具集成，请考虑开发您自己的扩展：探索 [chrome.devtools.recorder API](/docs/extensions/reference/devtools_recorder/) 并查看更多 [扩展示例](https://github.com/puppeteer/replay/tree/main/examples/)。
```suggestion
您可以开发自家的扩展，根据您的需要自定义 **记录器** 并将其与您的工具集成：搜索 [chrome.devtools.recorder API](/docs/extensions/reference/devtools_recorder/) 并查看更多 [扩展示例](https://github.com/puppeteer/replay/tree/main/examples/)。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +除了 [custom， CSS， ARIA， text 和 XPath 选择器](/docs/devtools/recorder/reference/#selector)，您现在还可以使用 [pierce 选择器](https://pptr.dev/guides/query-selectors#pierce-selectors-pierce)。 这些选择器的行为类似于 CSS 选择器，但也可以穿
```suggestion
除了 [custom， CSS， ARIA， text 和 XPath 选择器](/docs/devtools/recorder/reference/#selector)，您现在还可以使用 [pierce 选择器](https://pptr.dev/guides/query-selectors#pierce-selectors-pierce)。 Pierce 选择器类似于 CSS 选择器，但也可以穿透影子根。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +在页面上开始一个新的记录 [shadow DOM](https://web.dev/shadowdom-v1/) 并检查 {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/hmp8j3HiLMCcqPArD9yt.svg", alt="复选框.", width="22", height="22" %} **Pierce** 在 **Selector t
```suggestion
在含有 [shadow DOM](https://web.dev/shadowdom-v1/) 的页面上开始一个新的记录。在 {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/hmp8j3HiLMCcqPArD9yt.svg", alt="复选框.", width="22", height="22" %} **Selector types to record** 选择 **Pierce**，并开始记录您与子 DOM 中元素的交互并检查相应的步骤。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +### 导出为带有 Lighthouse 分析的 Puppeteer 脚本 {: #puppeteer-lighthouse }
```suggestion
### 导出带有 Lighthouse 分析的 Puppeteer 脚本 {: #puppeteer-lighthouse }
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/_partials/devtools/whats-new.md
> +* [导出为带有 Lighthouse 分析的 Puppeteer 脚本](/zh/blog/new-in-devtools-112/#puppeteer-lighthouse)
```suggestion
* [导出带有 Lighthouse 分析的 Puppeteer 脚本](/zh/blog/new-in-devtools-112/#puppeteer-lighthouse)
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +打开你的录影, 点击 {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/4dU9UXvsinS4zbgjd8rK.svg", alt="Export.", width="20", height="20" %} **Export**, 选择新选项 ，并保存 `.js` 文件。
```suggestion
打开你的录影, 点击 {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/4dU9UXvsinS4zbgjd8rK.svg", alt="Export.", width="20", height="20" %} **导出**, 选择新选项 ，并保存 `.js` 文件。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +探索自定义您的记录器体验的选项，例如，使用自定义导出选项。 在录影里， 通过单击 {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/4dU9UXvsinS4zbgjd8rK.svg", alt="Export.", width="20", height="20" %} **Export** > **Get extensions** 以获取 **Reco
```suggestion
探索自定义您的记录器体验的选项，例如，使用自定义导出选项。 在录影里， 通过单击 {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/4dU9UXvsinS4zbgjd8rK.svg", alt="导出。", width="20", height="20" %} **导出** > **Get extensions** 以获取 **Recorder** 的扩展。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
>  {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/vwgXoxR0FyArbCHvdvEY.png", alt="The Get extensions option in the Export drop-down menu.", width="800", height="649" %}
```suggestion
{% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/vwgXoxR0FyArbCHvdvEY.png", alt="在导出下拉菜单中的 Get extensions 选项。", width="800", height="649" %}
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +随意[添加您自己的扩展](https://github.com/GoogleChrome/developer.chrome.com/edit/main/site/en/docs/devtools/recorder/extensions/index.md) 到列表 [记录器扩展](/docs/devtools/recorder/extensions/). 我们期待在名单上看到您的扩展！
```suggestion
如果您有开发[记录器扩展]，欢迎添加(https://github.com/GoogleChrome/developer.chrome.com/edit/main/site/en/docs/devtools/recorder/extensions/index.md) 到我们的 [记录器扩展列表](/docs/devtools/recorder/extensions/). 我们期待在名单上看到您的扩展！
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +您一天查看多少次有关 CSS 属性的文档？ 当您将鼠标悬停在某个属性上时，**元素** > **样式** 窗格现在会向您显示简短描述。
```suggestion
您一天查看多少次有关 CSS 属性的文档？ 当您将鼠标悬停在某个属性上时，**元素** > **样式** 边栏现在会向您显示简短描述。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +**元素** > **样式** 窗格现在可以识别 [CSS 嵌套](/articles/css-nesting/) 语法并将嵌套样式应用于正确的元素。
```suggestion
**元素** > **样式** 边栏现在可以识别 [CSS 嵌套](/articles/css-nesting/) 语法并将嵌套样式应用于正确的元素。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +进一步改进 [enhanced breakpoint UX](/blog/new-in-devtools-111/#breakpoint-redesign)，**控制台**现在标记由断点触发的消息：
```suggestion
DevTools 进一步改进 [调试控制台中标记日志点和条件断点的用户体验](/blog/new-in-devtools-111/#breakpoint-redesign)。**控制台**现在标记由断点触发的消息：
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +- `console.*` 在 [conditional breakpoints](/docs/devtools/javascript/breakpoints/#conditional-loc) 中调用带有橙色问号 `?`
```suggestion
- `console.*` 在 [条件断点](/docs/devtools/javascript/breakpoints/#conditional-loc) 中调用带有橙色问号 `?`
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +为了帮助您专注于代码中最重要的部分，您现在可以直接从 **Sources** > **Page** 窗格的文件树中将不相关的脚本添加到 **Ignore List**。
```suggestion
为了帮助您专注于代码中最重要的部分，您现在可以直接从 **Sources** > **Page** 边栏的文件树中将不相关的脚本添加到 **Ignore List**。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +## JavaScript Profiler 开始弃用 {: #js-profiler-deprecation }
```suggestion
## JavaScript 性能剖析器开始弃用 {: #js-profiler-deprecation }
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +早在 [Chrome 58](/blog/devtools-javascript-cpu-profile-migration-2/) 中，DevTools 团队就计划最终弃用 **JavaScript Profiler**，并让 Node.js 和 Deno 开发人员使用 **Performance** 面板，用于分析 JavaScript CPU 性能。
```suggestion
早在 [Chrome 58](/blog/devtools-javascript-cpu-profile-migration-2/) 中，DevTools 团队就计划最终弃用 **JavaScript 性能剖析器**，并让 Node.js 和 Deno 开发人员使用**性能**面板，用于分析 JavaScript CPU 性能。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +此 DevTools 版本 (112) 开始 [四阶段 **JavaScript Profiler** 弃用](https://github.com/ChromeDevTools/rfcs/discussions/2#discussioncomment-5189668)。 **JavaScript Profiler** 面板现在显示相应的警告横幅。
```suggestion
此 DevTools 版本 (112) 开始 [四阶段 **JavaScript 性能剖析器** 弃用](https://github.com/ChromeDevTools/rfcs/discussions/2#discussioncomment-5189668)。 **JavaScript 性能剖析器** 面板现在显示相应的警告横幅。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +{% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/v4S5YWGdBV3nbc3OkGZ3.png", alt="Profiler 顶部的弃用横幅。", width="800", height="712" %}
```suggestion
{% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/v4S5YWGdBV3nbc3OkGZ3.png", alt="性能剖析器顶部的弃用横幅。", width="800", height="712" %}
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +代替 **Profiler**，使用 [**Performance**](/docs/devtools/performance/reference/#main) 面板来分析 CPU。
```suggestion
使用 [**Performance**](/docs/devtools/performance/reference/#main) 面板来代替 **性能剖析器**分析 CPU。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
>  {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/7qrlmuO7R47l5mytvoeQ.png", alt="The reduced contrast option on the Rendering > Emulate vision deficiencies.", width="800", height="574" %}
```suggestion
{% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/7qrlmuO7R47l5mytvoeQ.png", alt="在渲染 > 模拟视觉缺陷下拉菜单中的对比度降低选项。", width="800", height="574" %}
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +[**Rendering**](/docs/devtools/rendering/#open-rendering) 选项卡为 [Emulate vision deficiencies](/docs/devtools/rendering/apply-effects/#emulate-vision-deficiencies）列表—**对比度降低**。 使用此选项，您可以了解您的网站对对比敏感度较低的
```suggestion
[**渲染**](/docs/devtools/rendering/#open-rendering) 选项卡为[模拟视觉缺陷](/docs/devtools/rendering/apply-effects/#emulate-vision-deficiencies）列表—**对比度降低**。 使用此选项体验您网站是否对比敏感度较低的人友好呈现。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +使用 DevTools，您可以一次找到并修复所有对比度问题。 有关详细信息，请参阅 [使您的网站更具可读性](/docs/devtools/accessibility/contrast/)。
```suggestion
使用 DevTools，您可以一次找到并修复所有对比度问题。 有关详细信息，请参阅 [如何提升您的网站更具可读性](/docs/devtools/accessibility/contrast/)。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +**Lighthouse** > {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/9gzXiTYY0nZzBxGI6KrV.svg", alt="设置.", width="24", height="24" %} > {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/ZtDyFg7cjkxacORB3GQn.
```suggestion
**Lighthouse** > {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/9gzXiTYY0nZzBxGI6KrV.svg", alt="设置.", width="24", height="24" %} > {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/ZtDyFg7cjkxacORB3GQn.svg", alt="空复选框。", width="24", height="24" %} **旧版导航** 现在默认禁用。 此选项使用旧版 [Lighthouse configuration](https://github.com/GoogleChrome/lighthouse/blob/main/docs/configuration.md) 在导航模式下。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +Lighthouse 10 现在使用 Moto G Power 作为[默认仿真设备](https://github.com/GoogleChrome/lighthouse/pull/14674)。 DevTools 将此设备添加到 {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/9gzXiTYY0nZzBxGI6KrV.svg", alt="设置。"
```suggestion
Lighthouse 10 现在使用 Moto G Power 作为[默认模拟设备](https://github.com/GoogleChrome/lighthouse/pull/14674)。 DevTools 将此设备添加到 {% Img src="image/NJdAV9UgKuN8AhoaPBquL7giZQo1/9gzXiTYY0nZzBxGI6KrV.svg", alt="设置。", width="24", height="24" %} [**Settings** > **Devices**](/docs/devtools/settings/devices/)。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +- [**Sources** > **Breakpoints**](/docs/devtools/javascript/breakpoints/#manage-loc) 窗格现在在不明确的文件名旁边显示不同的文件路径 ([1403924](crbug.com/1403924 ))。
```suggestion
- [**Sources** > **Breakpoints**](/docs/devtools/javascript/breakpoints/#manage-loc) 边栏现在在不明确的文件名旁边显示不同的文件路径 ([1403924](crbug.com/1403924 ))。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +  - **Console**: `Arrow down` 选择第一个建议和 suggestions 得到 `Tab` 提示 ([1276960](https://crbug.com/1276960)).
```suggestion
  - **控制台**: `Arrow down` 选择第一个建议，而且建议含有 `Tab` 提示 ([1276960](https://crbug.com/1276960)).
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +  - **Sources**：任何单词的一致完成 ([1320204](https://crbug.com/1320204))。
```suggestion
  - **源代码**：任何单词的一致完成 ([1320204](https://crbug.com/1320204))。
```

2023-03-12 07:41 UTC, jecfish commented on site/zh/blog/new-in-devtools-112/index.md
> +- [**Console** setting](/docs/devtools/settings/preferences/#console) 有一个更好的名字：Automatically expand console.trace() messages。 （[1139616]（https://crbug.com/1139616））。
```suggestion
- [**控制台**设置](/docs/devtools/settings/preferences/#console) 有一个更好的名字：默认展开 console.trace() 消息。 （[1139616]（https://crbug.com/1139616））。
```

2023-03-12 07:42 UTC, jecfish commented
Thanks for translate Zui Yong, I added a few feedback. @xyugroup, @louisyoong, @liuliangsir please help to review as well.

2023-03-13 00:23 UTC, aquaMAX commented on site/zh/blog/new-in-devtools-112/index.md
> +除了 [custom， CSS， ARIA， text 和 XPath 选择器](/docs/devtools/recorder/reference/#selector)，您现在还可以使用 [pierce 选择器](https://pptr.dev/guides/query-selectors#pierce-selectors-pierce)。 这些选择器的行为类似于 CSS 选择器，但也可以穿
@jecfish updated

2023-03-13 02:25 UTC, aquaMAX reviewed
merged review by jecelyn

2023-03-14 08:10 UTC, jecfish approved these changes

2023-03-14 08:11 UTC, jecfish commented
Thanks @aquaMAX! Over to @AaronForinton for checking & merging

2023-03-14 10:44 UTC, sofiayem approved these changes

2023-03-14 10:44 UTC, merged