Update omahaproxy links
GoogleChrome/developer.chrome.com pull request #5640
Opened 2023-03-13 00:52 UTC by connerturner

CL to update links referencing omahaproxy to the chromiumdash. Due to it's [impending
deprecation.](https://groups.google.com/a/chromium.org/g/chromium-dev/c/uH-nFrOLWtE/m/PhUj_inyAQAJ)

Changes proposed in this pull request:

- Update chrome-release-channels web-platform docs to use new link
- Update old puppeteer faq to use new process of finding chromium commit positions
- Update mv3 FAQ's with new link and where to find the version history api

2023-03-23 22:08 UTC, jpmedley requested changes

2023-03-23 22:08 UTC, jpmedley commented on site/en/docs/puppeteer/faq/index.md
> +- Look for the `chromium` entry in [revisions.ts](https://github.com/puppeteer/puppeteer/blob/main/src/revisions.ts). To find the corresponding Chromium commit and version number, append the entry on
This link returns 404. I don't even know what this is, so I didn't have much luck finding a new link.

2023-03-23 22:08 UTC, jpmedley commented on site/en/docs/puppeteer/faq/index.md
> +`crrev.com/` for example [crrev.com/1095492](https://crrev.com/1095492). Then search the commit hash on [chromiumdash.appspot.com](https://chromiumdash.appspot.com/commits)
For items in Blink, you can also use https://storage.googleapis.com/chromium-find-releases-static/index.html

2023-11-04 05:44 UTC, rachelandrew commented
Closing as no response to requests for changes and file has now been changed in other PRs.

2023-11-04 05:44 UTC, closed without merging