DevTools Tips 23: Source maps doc refresh
GoogleChrome/developer.chrome.com pull request #5734
Opened 2023-03-20 17:10 UTC by sofiayem

Source map doc refresh. Relates to #5673 but doesn't fix it yet. Expect follow-ups.

No blockers, merging as soon as reviewed.

2023-03-21 08:00 UTC, rachelandrew approved these changes

2023-03-22 18:15 UTC, jecfish commented on site/en/docs/devtools/javascript/source-maps/index.md
>  - Minifiers ([UglifyJS][11])
```suggestion
- Minifiers ([UglifyJS][11])
```

UglifySJ is no longer maintain, use https://github.com/terser/terser

2023-03-22 18:18 UTC, jecfish requested changes

2023-03-22 18:18 UTC, jecfish commented on site/en/docs/devtools/javascript/source-maps/index.md
>  - Compilers ([Closure Compiler][7], [TypeScript][8], [CoffeeScript][9], [Dart][10])
```suggestion
- Compilers ([TypeScript][8], [Dart][10])
```
Closure Compiler is not maintain soon as well, remove it, Coffees cript is old so remove as well. Remove the reference URLs, Check if Dart URL updated.

2023-03-22 18:18 UTC, jecfish commented on site/en/docs/devtools/javascript/source-maps/index.md
```suggestion
```

Add bundlers: Webpack, Vite, esbuild

2023-03-23 13:32 UTC, jecfish commented on site/en/docs/devtools/javascript/source-maps/index.md
> +Common preprocessors used in combination with source maps include but aren't limited to:
@jarin, is this list and the categorization correct?

2023-03-24 09:26 UTC, jaro-sevcik reviewed
This is looking great. I am wondering if it makes sense to get into more details for some use cases or pitfalls.

For example, it is possible to attach source map manually from the context menu, but that workflow is not documented (as far as I know).

For an example of a recently reported pitfall, a developer correctly served the source map from their server, but did not serve their source code, so they got a [weird error message](https://stackoverflow.com/questions/75816192/cant-set-breakpoint-in-js-file-in-chrome-dev-tools-could-not-load-content-for). (Arguably, we should improve that error message.)

2023-03-24 09:26 UTC, jaro-sevcik commented on site/en/docs/devtools/javascript/source-maps/index.md
> +Notice that the **Editor** automatically pretty-printed the deployed file. In fact, it contains all the code in a single line, except for the `//# sourceMappingURL` comment.
"In fact" -> "In reality" ?

2023-03-24 12:09 UTC, merged