Update CRX known issues page
GoogleChrome/developer.chrome.com pull request #6242
Opened 2023-05-09 19:17 UTC by sebastianbenz

2023-05-09 22:36 UTC, rdcronin commented on site/en/docs/extensions/migrating/known-issues/index.md
> +Recently, we announced changes to the Manifest V2 deprecation timeline, and while we remain firmly committed to Manifest V3 we acknowledge there is more work to do on our part including:
```suggestion
Recently, we announced changes to the Manifest V2 (MV2) deprecation timeline, and while we remain firmly committed to Manifest V3 (MV3) we acknowledge there is more work to do on our part including: 
```

2023-05-09 22:36 UTC, rdcronin commented on site/en/docs/extensions/migrating/known-issues/index.md
> +    * Additional strong Service Worker keepalives for operations taking longer than 5 minutes.
```suggestion
    * Additional strong Service Worker keepalives for certain operations taking longer than 5 minutes.
```

2023-05-09 22:36 UTC, rdcronin commented on site/en/docs/extensions/migrating/known-issues/index.md
> +    * Additional strong Service Worker keepalives for operations taking longer than 5 minutes.
```suggestion
    * Additional strong Service Worker keepalives for certain operations taking longer than 5 minutes.
```

2023-05-09 22:36 UTC, rdcronin commented on site/en/docs/extensions/migrating/known-issues/index.md
> +1. Improving **support for the `chrome.tabCapture` API**:
```suggestion
1. Improving **support for the [`chrome.tabCapture`](https://developer.chrome.com/docs/extensions/reference/tabCapture/) API**:
```

2023-05-09 22:36 UTC, rdcronin commented on site/en/docs/extensions/migrating/known-issues/index.md
> +1. **Support File Handling API on ChromeOS** as a replacement for `chrome.fileBrowserHandler`.
```suggestion
1. **Support File Handling API on ChromeOS** as a replacement for [`chrome.fileBrowserHandler`](https://developer.chrome.com/docs/extensions/reference/fileBrowserHandler/).
```

2023-05-09 22:36 UTC, rdcronin commented on site/en/docs/extensions/whatsnew/index.md
> +We've updated the [know issues section of our MV3 migration guidance](/docs/extensions/migrating/known-issues/), with a updated list of extension platform gaps that we intent to close before announci
```suggestion
We've updated the [known issues section of our MV3 migration guidance](/docs/extensions/migrating/known-issues/) with a updated list of extension platform gaps that we intend to close before announcing a new MV2 deprecation timeline.
```

2023-05-10 13:33 UTC, rdcronin approved these changes
LGTM; thanks, Sebastian!

2023-05-10 13:33 UTC, rdcronin commented on site/en/docs/extensions/migrating/known-issues/index.md
> +Recently, we announced changes to the Manifest V2 (MV2) deprecation timeline, and while we remain firmly committed to Manifest V3 (MV3) we acknowledge there is more work to do on our part including:
```suggestion
Recently, we announced changes to the Manifest V2 (MV2) deprecation timeline, and while we remain firmly committed to Manifest V3 (MV3) we acknowledge there is more work to do on our part.
```

Optional, but the "including" followed by bullets for "we will do <x>" sounds a little awkward.

2023-05-10 13:33 UTC, rdcronin commented on site/en/docs/extensions/migrating/known-issues/index.md
> +*   We will give developers time to build, guaranteeing at least 6 months between a timeline announcement and any experiments deprecating MV2 features.
```suggestion
*   We will give developers time to build, guaranteeing at least 6 months between a timeline announcement and any experiments removing support for MV2.
```

I feel like this is a bit more accurate (we may _separately_ deprecate features as part of normal platform maintenance)

2023-05-10 16:05 UTC, jpmedley requested changes

2023-05-10 16:05 UTC, jpmedley commented on site/en/docs/extensions/whatsnew/index.md
> +We've updated the [known issues section of our MV3 migration guidance](/docs/extensions/migrating/known-issues/) with an updated list of extension platform gaps that we intend to close before announc
```suggestion
We've updated the [Known Issues](/docs/extensions/migrating/known-issues/) section of our [Manifest V3 migration guidance](/docs/extensions/migrating/) with an updated list of extension platform gaps that we intend to close before announcing a new Manifest V2 deprecation timeline.
```

2023-05-10 16:24 UTC, jpmedley approved these changes

2023-05-10 16:37 UTC, merged