[Blogpost] Migrate away from data URLs in SVG <use> element
GoogleChrome/developer.chrome.com pull request #6414
Opened 2023-05-24 21:57 UTC by shhnjk

This blogpost explains migration alternatives for the [removal of data: URLs in SVGUseElement](https://chromestatus.com/feature/5128825141198848).

See more details in the [deprecation plan](https://groups.google.com/a/chromium.org/g/blink-dev/c/Q9dLyBhtZTw/m/ZKp9X38PAAAJ).

2023-05-25 19:22 UTC, JackJey commented on site/en/blog/migrate-way-from-data-urls-in-svg-use/index.md
> +This improves security of the Web platform as well as compatibility between browsers as Webkit does not support `data:` URLs in SVG `<use>` element.
I'd be better to add "why to remove it" here. For example, share known incidents with summary, how to attack with data with poc code etc

2023-05-25 19:22 UTC, JackJey commented
Left single proposal comments.
And LGTM +1 for rest of it.

2023-05-25 20:45 UTC, shhnjk commented
> Left single proposal comments.

Thanks! I'll work on it.

@mikewest, could you PTAL or suggest someone who can review this blog post?

2023-05-25 21:33 UTC, mikewest commented
@agektmr is the first person who comes to mind.

2023-05-26 02:33 UTC, agektmr requested changes
@mihajlija or @anusmitaray could either of you review / edit this post?

2023-05-26 02:33 UTC, agektmr commented on site/en/blog/migrate-way-from-data-urls-in-svg-use/index.md
> +This improves security of the Web platform as well as compatibility between browsers as Webkit does not support `data:` URLs in SVG `<use>` element.
+1
I'm inclined to move the reasoning forefront.
Also, can you add the status in Firefox as well?

2023-05-27 00:49 UTC, shhnjk commented on site/en/blog/migrate-way-from-data-urls-in-svg-use/index.md
> +This improves security of the Web platform as well as compatibility between browsers as Webkit does not support `data:` URLs in SVG `<use>` element.
Done :)
Since I don't know the status of Firefox (i.e. they are waiting for our successfully removal), I've linked thier standard position issue.

2023-05-27 00:51 UTC, shhnjk commented
> @mihajlija or @anusmitaray could either of you review / edit this post?

+1 🙂 I'll be OOO on Monday due to a national holiday in US, so feel free to edit and/or publish the blog post!

2023-05-29 03:33 UTC, agektmr approved these changes
LGTM

2023-05-31 13:39 UTC, anusmitaray approved these changes

2023-05-31 16:30 UTC, merged