What's new in DevTools (115)
GoogleChrome/developer.chrome.com pull request #6469
Opened 2023-05-31 16:21 UTC by sofiayem

WNDT 115

2023-05-31 16:51 UTC, rachelandrew commented on site/en/_partials/devtools/whats-new.md
> +* [New CSS subgrid badge](/blog/new-in-devtools-115/#subgrid)
Can we remove this section? Subgrid actually isn't in Chrome yet so it's a bit odd to announce the DevTools functionality. Hang onto the copy and we'll use it when subgrid ships.

2023-06-05 12:23 UTC, rachelandrew requested changes
I've corrected the definition of subgrid, subgrid are nested grids but only those where either grid-template-columns or grid-template-rows have a value of subgrid. Regular nested grids aren't subgrids, and won't get this badge. Also made it clear the feature is experimental and not in the current release.

2023-06-05 12:23 UTC, rachelandrew commented on site/en/blog/new-in-devtools-115/index.md
> +The **Elements** panel gets a new `subgrid` badge for [nested grids](https://developer.mozilla.org/docs/Web/CSS/CSS_Grid_Layout/Subgrid).
```suggestion
The **Elements** panel gets a new `subgrid` badge for [subgrid](https://developer.mozilla.org/docs/Web/CSS/CSS_Grid_Layout/Subgrid). This feature is currently experimental in Chrome Canary.
```

2023-06-05 12:23 UTC, rachelandrew commented on site/en/blog/new-in-devtools-115/index.md
> +To inspect and debug a nested grid, click the badge. It toggles an overlay that shows columns, rows, and their numbers on top of the element in the viewport.
```suggestion
To inspect and debug a nested grid that is a subgrid, and therefore inheriting the number and size of tracks from its parent, click the badge. It toggles an overlay that shows columns, rows, and their numbers on top of the element in the viewport.
```

2023-06-05 13:21 UTC, rachelandrew approved these changes

2023-06-05 13:26 UTC, jecfish approved these changes
Added review comments on docs.

2023-06-05 15:10 UTC, merged