Remove reference to deprecated ChromeOS sample
GoogleChrome/developer.chrome.com pull request #6582
Opened 2023-06-11 20:31 UTC by IanStanion-google

This PR is in conjunction with implementing an mv3 notifications API sample

Fixes https://github.com/GoogleChromeLabs/Extension-Docs/issues/85

2023-06-12 11:21 UTC, oliverdunk approved these changes
LGTM 👍

2023-06-12 11:21 UTC, oliverdunk commented on site/en/docs/extensions/mv3/richNotifications/index.md
> -[Keep your users informed][6] all the time, even
Should we still keep this but just link to the chrome.gcm API?

2023-06-20 17:09 UTC, jpmedley requested changes
Your work looks good. I just want to do a little lateral cleanup while you're here.

2023-06-20 17:09 UTC, jpmedley commented on site/en/docs/extensions/mv3/richNotifications/index.md
> +**Platform difference:** The priority setting does not affect the order of notifications in Chrome version 59+ on macOS.
```suggestion
**Platform difference:** The `priority` setting does not affect the order of notifications in Chrome 59 or later on macOS.
```

2023-06-20 18:45 UTC, jpmedley approved these changes

2023-06-21 18:54 UTC, merged