Protect privacy mv3 update
GoogleChrome/developer.chrome.com pull request #6583
Opened 2023-06-11 20:33 UTC by IanStanion-google

Fixes [#SOME_ISSUE_NUMBER](https://github.com/GoogleChromeLabs/Extension-Docs/issues/85)

2023-06-12 11:18 UTC, oliverdunk requested changes
Nice simple one, looks good! Left one comment.

2023-06-12 11:18 UTC, oliverdunk commented on site/en/docs/extensions/mv3/user_privacy/index.md
> +      permissions: ["tabs", "scripting"],
Did we drop `origins` here intentionally?

2023-06-26 14:08 UTC, jpmedley commented
@oliverdunk Are you done with this?

2023-06-27 13:27 UTC, oliverdunk commented
> @oliverdunk Are you done with this?

Yep, this looks good to me. LGTM.

2023-06-27 13:27 UTC, oliverdunk approved these changes

2023-06-28 03:05 UTC, jpmedley requested changes

2023-06-28 03:05 UTC, jpmedley commented on site/en/docs/extensions/mv3/user_privacy/index.md
> +chrome.action.onClicked.addListener(function (event) {
```suggestion
chrome.action.onClicked.addListener((event) => {
```

2023-06-28 17:31 UTC, merged