Mv3 reference page sample links
GoogleChrome/developer.chrome.com pull request #6682
Opened 2023-06-26 09:27 UTC by IanStanion-google

Fixes: https://github.com/GoogleChromeLabs/Extension-Docs/issues/65

Changes proposed in this pull request:

- Adds links to MV3 samples on API reference pages.

2023-06-26 13:13 UTC, AmySteam approved these changes
Thanks @IanStanion-google 💯 

Some of the links are still pending, but I noticed that they will be fixed once some of the sample PR's land.

2023-06-26 14:18 UTC, jpmedley commented on site/en/docs/extensions/reference/bookmarks/index.md
> +To try this API, install the [Bookmarks API example][6] from the [chrome-extension-samples][5]
```suggestion
To try this API. Install the [Bookmarks API example][6] from the [chrome-extension-samples][5]
```

2023-06-26 14:18 UTC, jpmedley commented on site/en/docs/extensions/reference/bookmarks/index.md
> +To try this API, install the [Bookmarks API example][6] from the [chrome-extension-samples][5]
Please be careful of comma splices.

2023-06-28 03:03 UTC, jpmedley requested changes
I messed up one of the edits. Sorry about that.

2023-06-28 03:03 UTC, jpmedley commented on site/en/docs/extensions/reference/bookmarks/index.md
> +To try this API. Install the [Bookmarks API example][6] from the [chrome-extension-samples][5]
```suggestion
To try this API, install the [Bookmarks API example][6] from the [chrome-extension-samples][5]
```

2023-06-28 03:03 UTC, jpmedley commented on site/en/docs/extensions/reference/bookmarks/index.md
> +To try this API. Install the [Bookmarks API example][6] from the [chrome-extension-samples][5]
Big apology. I messed up on this edit.

2023-06-28 15:22 UTC, jpmedley approved these changes

2023-06-28 17:32 UTC, merged