DevTools 115: Elements > Subgrid badge
GoogleChrome/developer.chrome.com pull request #6695
Opened 2023-06-27 17:45 UTC by sofiayem

Documented https://developer.chrome.com/blog/new-in-devtools-115/#subgrid

Publish on Jul 18

2023-06-28 01:17 UTC, rachelandrew commented on site/en/docs/devtools/elements/badges/index.md
> +[Subgrid](https://developer.mozilla.org/docs/Web/CSS/CSS_grid_layout/Subgrid) is a kind of a "nested" grid but one that uses the same tracks as its "parent" grid. An element is a subgrid container if
```suggestion
A [subgrid](https://developer.mozilla.org/docs/Web/CSS/CSS_grid_layout/Subgrid) is a nested grid that uses the same tracks as its parent grid. An element is a subgrid container if one or both of its `grid-template-columns`, `grid-template-rows` properties are set to `subgrid`. Such elements have `subgrid` badges next to them that toggle the corresponding overlays.
```

2023-06-28 01:19 UTC, rachelandrew approved these changes
With a bit of wording fiddling.

2023-07-17 06:38 UTC, jecfish requested changes
Since it's relevant to Grid, add a line of mention in the Grid docs as well `/docs/devtools/css/grid/`

2023-07-17 10:22 UTC, jecfish approved these changes

2023-07-18 13:34 UTC, merged