Richer pwa install article
GoogleChrome/developer.chrome.com pull request #681
Opened 2021-04-22 14:09 UTC by mustafa-x

Adding new article regarding Richer Installs UI, explaining how to implement etc.

2021-04-22 18:24 UTC, jpmedley requested changes

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +`mobile-pwa-install-use-bottom-sheet`
This needs to include the flags path and the flag should have a # sign in it. Here's a common boilerplate: https://github.com/GoogleChrome/web.dev/blob/main/src/site/content/en/blog/multi-screen-window-placement/index.md

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +In order to enable Richer installs on your site you need to add at least one screenshot to your
```suggestion
To enable Richer installs on your site you need to add at least one screenshot to your 
```

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +defined.
Please rewrite without 'we' per the [handbook](https://web.dev/handbook/grammar/#instructions).

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +Now let's add the screenshots to the end of the manifest.json file;
```suggestion
Now add the screenshots to the end of the manifest.json file; 
```

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +defined.
please check this throughout.

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +To add screenshots we need to determine the size, source and type, following this
```suggestion
To add screenshots you need to determine the size, source and type, following this 
```

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +Only JPEG and PNG image formats are supported.
```suggestion
* Width and height must be at least 320px and at most 3840px.
* The maximum dimension can't be more than 2.3 times as long as the minimum dimension.
* Screenshots must have the same aspect ratio.
* Only JPEG and PNG image formats are supported.
```

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +Currently animated gifs are not supported. We need to include the size and type of the image so it
```suggestion
Currently animated gifs are not supported. Also, you need to include the size and type of the image so it 
```

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +Descriptions are not compulsory, so there is no minimum requirement. There however is a max which
```suggestion
Descriptions are not compulsory, so there is no minimum requirement. However, there is a maximum that 
```

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +([see example](https://glitch.com/edit/#!/richerinstall-longer-description)).
```suggestion
([for example](https://glitch.com/edit/#!/richerinstall-longer-description)). 
```

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +In the future we will consider adding other data such as categories and app rating, but this will
This 'we' is fine.

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +[See example code here](https://glitch.com/edit/#!/richerinstall-description?path=manifest.json%3A13%3A29).
```suggestion
[See the example code here](https://glitch.com/edit/#!/richerinstall-description?path=manifest.json%3A13%3A29).
```

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +Example;
```suggestion
```

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +"description": "Compress and compare images with different codecs,
```suggestion
"description": "Compress and compare images with different codecs
```

2021-04-22 18:24 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +alt="Longer description added that has been truncated.", width="342", height="684" %}
```suggestion
alt="A longer description that has been truncated.", width="342", height="684" %}
```

2021-04-26 12:22 UTC, mustafa-x commented on site/en/blog/richer-pwa-installation/index.md
> +description and screenshots to their manifest file and have it appear in a bottomsheet dialog
The image appears below it, with the example. Shall I add another image as well with just a bottomsheet?

2021-04-26 12:24 UTC, mustafa-x commented on site/en/blog/richer-pwa-installation/index.md
> +that better aligns to user expectations and better context that mimics their existing mental model
removed

2021-04-26 12:26 UTC, mustafa-x commented on site/en/blog/richer-pwa-installation/index.md
> +Websites that do not conform to the above will continue to receive the existing prompts. This may
I updated it to this
'Websites that do not include at least one screenshot to their manifest file will continue to receive the existing prompts.'

2021-04-27 13:44 UTC, jpmedley requested changes

2021-04-27 13:44 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +description and screenshots to their manifest file and have it appear in a bottomsheet dialog
Unless I'm missing something, I can't find that it's labeled as such. That means I have to look it up. Please make this clear.

2021-04-27 13:44 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +This UI works in Chrome Dev & Chrome Canary on Android, with the flag `#mobile-pwa-install-use-bottom-sheet` enabled in `chrome://flags`.
This is what I was commenting on at the top. Please use specific version numbers.

2021-04-27 13:44 UTC, jpmedley commented on site/en/blog/richer-pwa-installation/index.md
> +This UI works in Chrome Dev & Chrome Canary on Android, with the flag `#mobile-pwa-install-use-bottom-sheet` enabled in `chrome://flags`.
```suggestion
This UI works in Chrome Dev and Chrome Canary on Android, with the flag `#mobile-pwa-install-use-bottom-sheet` enabled in `chrome://flags`.
```

2021-04-28 17:26 UTC, mustafa-x commented on site/en/blog/richer-pwa-installation/index.md
> +description and screenshots to their manifest file and have it appear in a bottomsheet dialog
added an image with an example of bottomsheet UI to be clearer.

2021-04-28 17:26 UTC, mustafa-x commented on site/en/blog/richer-pwa-installation/index.md
> +title: Richer PWA installation UI
Updated with the milestone

2021-05-03 13:34 UTC, jpmedley commented
I'll handle it. 

Sorry about that.

2021-05-03 13:34 UTC, merged