Remove MV2 from Declare Permissions article
GoogleChrome/developer.chrome.com pull request #6865
Opened 2023-07-19 18:39 UTC by AmySteam

Related doc
https://docs.google.com/document/d/1vAK7LIGkyiQ72aO9my3cJfi0D-4coQQ6mWqV48jyXEE/edit

Changes proposed in this pull request:

- Removes MV2 mentions

2023-07-19 20:10 UTC, jpmedley requested changes

2023-07-19 20:10 UTC, jpmedley commented on site/en/docs/extensions/mv3/declare_permissions/index.md
> +      <td>Gives temporary access to the active tab through a user gesture. See <a href="/docs/extensions/mv3/manifest/activeTab">activeTab</a>
```suggestion
      <td>Gives temporary access to the active tab through a user gesture. See <a href="/docs/extensions/mv3/manifest/activeTab"><code>activeTab</code></a>
```

2023-07-19 20:10 UTC, jpmedley commented on site/en/docs/extensions/mv3/declare_permissions/index.md
> +        <p id="bg">Makes Chrome start-up early (as soon as the user logs into their computer—before the user launches Chrome), and shut down late (even after its last window is closed until the user
```suggestion
        <p id="bg">Makes Chrome start up early (as soon as the user logs into their computer—before the user launches Chrome), and shut down late (even after its last window is closed until the user explicitly quits Chrome).</p>
```

2023-07-20 13:08 UTC, AmySteam commented
@jpmedley PTAL

2023-07-20 14:07 UTC, jpmedley approved these changes

2023-07-20 14:08 UTC, merged