Remove unnecessary msg object from example
GoogleChrome/developer.chrome.com pull request #688
Opened 2021-04-25 06:34 UTC by QuentinGibson

In the persistent storage example, it referred to the type and name of a "msg" object that did not exist.

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

2021-04-26 20:54 UTC, kaycebasques commented
Thanks for the fix @QuentinGibson it looks like you'll need to sign the CLA before we can accept the PR

2021-04-26 22:33 UTC, dotproto approved these changes
Thanks for cleaning this up!

2021-04-26 22:36 UTC, dotproto requested changes
Oops, as @kaycebasques said this needs CLA signature before we can merge. That's the only change I'm requesting with this review.

2021-04-27 01:11 UTC, QuentinGibson commented
@googlebot I signed it!

2021-04-27 01:12 UTC, QuentinGibson commented
@kaycebasques I filled the form and replied, also thank you for the quick response.

2021-04-27 12:06 UTC, samthor approved these changes

2021-04-27 12:06 UTC, merged