Restructure CWS best practices
GoogleChrome/developer.chrome.com pull request #6992
Opened 2023-08-03 21:44 UTC by AmySteam

Slight restructure and update of the CWS best practices:

- Changed headers and subheaders
- Added descriptions to categories

That's about it :)

2023-08-04 18:07 UTC, AmySteam commented on site/en/docs/webstore/best_practices/index.md
> +When designing a [side panel][api-sidepanel] for your extension, make sure it enhances the user's browsing experience by providing relevant information and useful functionality. A side panel should h
The wording was requested by David/Alex to match the [quality guidelines](https://developer.chrome.com/docs/webstore/program-policies/quality-guidelines/#:~:text=If%20utilizing%20a%20persistent%20user%20interface%2C%20extensions%20should%20actively%20enhance%20the%20user%27s%20current%20task%20while%20causing%20minimal%20distractions.) 

I'm open to another suggestion... 🤷🏻‍♀️

2023-08-04 18:07 UTC, AmySteam commented on site/en/docs/webstore/best_practices/index.md
> +[user-data]: /docs/webstore/user_data/
😶‍🌫️

2023-08-04 19:25 UTC, sebastianbenz commented on site/en/docs/webstore/best_practices/index.md
> +When designing a [side panel][api-sidepanel] for your extension, make sure it enhances the user's browsing experience by providing relevant information and useful functionality. A side panel should h
```suggestion
Avoid distracting users when implementing a persistent UI. For example, when designing a [side panel][api-sidepanel] for your extension, make sure it enhances the user's browsing experience by providing relevant information and useful functionality. A side panel should help users accomplish tasks with as little distraction as possible.
```

2023-08-04 19:25 UTC, sebastianbenz approved these changes

2023-08-07 16:06 UTC, AmySteam commented on site/en/docs/webstore/best_practices/index.md
> +Your extension should be safe for your users. For example, transmit user data securely via HTTPS or WSS. Stored user data must be strongly encrypted using RSA or AES. Check that your extension does n
```suggestion
Your extension should be safe for your users. For example, send user data securely via HTTPS or WSS. Check that your extension does not pose security threats and does not use [deceptive installation tactics][deceptive-install]. See [Stay secure][stay-secure] for a more in-depth discussion.
```
Add in another iteration

2023-08-07 16:08 UTC, AmySteam commented
@jpmedley This is ready for an editorial review. Thanks! 🙏

2023-08-10 18:43 UTC, AmySteam commented
@jpmedley Can you take a quick look?

2023-08-10 20:15 UTC, jpmedley requested changes

2023-08-10 21:34 UTC, AmySteam commented on site/en/docs/webstore/best_practices/index.md
> +## Overview {: #design-a-high-quality-extension}
Totally get your point. However, I'm keeping the header-id to ensure any links to this section still work.

2023-08-11 13:54 UTC, jpmedley approved these changes

2023-08-11 14:10 UTC, merged