Make code sample an actual one-time initialization.
GoogleChrome/developer.chrome.com pull request #7055
Opened 2023-08-11 18:23 UTC by jpmedley

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

2023-08-11 18:26 UTC, 0569395312 commented
Important: SWEAT wallet backup code ❗Do not delete or share ❗

احصل على Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Joe Medley ***@***.***>
Sent: Friday, August 11, 2023 9:24:28 PM
To: GoogleChrome/developer.chrome.com ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [GoogleChrome/developer.chrome.com] Make code sample an actual one-time initialization. (PR #7055)


Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

  *
  *
  *

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/GoogleChrome/developer.chrome.com/pull/7055

Commit Summary

  *   3ce00ee<https://github.com/GoogleChrome/developer.chrome.com/pull/7055/commits/3ce00ee89fe5e2ae15c051dd0c11b176c7775753> Make code sample an actual one-time initialization.

File Changes

(1 file<https://github.com/GoogleChrome/developer.chrome.com/pull/7055/files>)

  *   M site/en/docs/extensions/mv3/service_workers/service-worker-lifecycle/index.md<https://github.com/GoogleChrome/developer.chrome.com/pull/7055/files#diff-94e9140869d8e73ca2c0d094c4f68707609a858e4c7dfb7d0a60ed50fb483fd9> (3)

Patch Links:

  *   https://github.com/GoogleChrome/developer.chrome.com/pull/7055.patch
  *   https://github.com/GoogleChrome/developer.chrome.com/pull/7055.diff

—
Reply to this email directly, view it on GitHub<https://github.com/GoogleChrome/developer.chrome.com/pull/7055>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BAFWUW4S4F5VDSWIWG2EPWTXUZ2FZANCNFSM6AAAAAA3NIIS5E>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

2023-08-11 18:35 UTC, AmySteam requested changes
Added a suggestion to the code

2023-08-11 18:35 UTC, AmySteam commented on site/en/docs/extensions/mv3/service_workers/service-worker-lifecycle/index.md
> +  if(details.reason !== "install"){ return: }
```suggestion
  if(details.reason !== "install") return;
```

2023-08-11 18:47 UTC, jpmedley commented
PTAL

2023-08-11 22:28 UTC, AmySteam approved these changes
LGTM 👍

2023-08-14 13:34 UTC, oliverdunk requested changes

2023-08-14 13:34 UTC, oliverdunk commented on site/en/docs/extensions/mv3/service_workers/service-worker-lifecycle/index.md
> +  if(details.reason !== "install") return;
Would you be ok with this? Context menus are cleared on update so we need to add them back there too.

```suggestion
  if(details.reason !== "install" && details.reason !== "update") return;
```

2023-08-15 15:23 UTC, jpmedley commented
@oliverdunk PTAL

2023-08-15 17:11 UTC, merged