Add theme categories to web store docs.
GoogleChrome/developer.chrome.com pull request #7177
Opened 2023-08-25 18:51 UTC by jpmedley

2023-08-31 11:07 UTC, oliverdunk requested changes

2023-08-31 11:07 UTC, oliverdunk commented on site/en/docs/webstore/best_practices/index.md
> +The developer console asks you specify a category for your extension. Choose the most appropriate category:
```suggestion
The developer console requires you to specify a category for your extension. Choose the most appropriate category:
```

2023-08-31 11:07 UTC, oliverdunk commented on site/en/docs/webstore/best_practices/index.md
> +: Themes featuring current and classic cars.
Did these come from some official, already-public definitions or is there scope to change them? Some of them feel a bit weird, e.g with this one - what if I want to feature future cars? Also what if I'm just using the color theme of a car brand but not actually featuring a specific car? They seem too limiting, and I think something like "Themes relating to cars, such as classic or current cars" would be better.

2023-09-01 10:22 UTC, oliverdunk requested changes

2023-09-01 10:22 UTC, oliverdunk commented on site/en/docs/webstore/best_practices/index.md
> +: Themes featuring your favorite animals.
```suggestion
: Themes inspired by animals.
```

2023-09-01 10:22 UTC, oliverdunk commented on site/en/docs/webstore/best_practices/index.md
> +: Themes featuring current and classic cars.
```suggestion
: Themes relating to cars, such as current and classic cars.
```

2023-09-01 10:22 UTC, oliverdunk commented on site/en/docs/webstore/best_practices/index.md
> +: Themes with images of popular television and film franchises.
```suggestion
: Themes inspired by popular entertainment, such as television and film franchises.
```

2023-09-01 10:22 UTC, oliverdunk commented on site/en/docs/webstore/best_practices/index.md
> +: Themes that show images of outer space.
```suggestion
: Themes inspired by space.
```

2023-09-01 10:22 UTC, oliverdunk commented on site/en/docs/webstore/best_practices/index.md
> +: Themes featuring current and classic cars.
Got it. I left some suggestions :)

2023-09-25 19:02 UTC, jpmedley commented on site/en/docs/extensions/mv3/themes/index.md
> +updated: 2023-08-28
```suggestion
updated: 2023-09-29
```

2023-09-25 19:02 UTC, jpmedley commented on site/en/docs/webstore/best_practices/index.md
> +updated: 2023-08-29
```suggestion
updated: 2023-09-29
```

2023-09-25 19:06 UTC, jpmedley commented
@oliverdunk PTAL

2023-09-26 11:00 UTC, oliverdunk approved these changes
Left one nit, otherwise LGTM. Thanks!

2023-10-16 16:45 UTC, AmySteam approved these changes
Thanks for this Joe.

I left one question. But otherwise LGTM.

2023-10-18 16:39 UTC, merged