Add isUrlFilterCaseSensitive change to What's New
GoogleChrome/developer.chrome.com pull request #7482
Opened 2023-10-09 14:57 UTC by oliverdunk

Adds the change to the default isUrlFilterCaseSensitive value to What's New.

Fixes https://github.com/GoogleChromeLabs/Extension-Docs/issues/137

2023-10-10 16:48 UTC, AmySteam requested changes
I'm helping out Joe with a couple of reviews. I made a suggestion to improve the flow

2023-10-10 16:48 UTC, AmySteam commented on site/en/docs/extensions/whatsnew/index.md
> +your declarativeNetRequest rules.
```suggestion
Starting in Chrome 118, the [`isUrlFilterCaseSensitive`](/docs/extensions/reference/declarativeNetRequest/#property-RuleCondition-isUrlFilterCaseSensitive)
property in the [chrome.declarativeNetRequest](/docs/extensions/reference/declarativeNetRequest/)
API has been changed to default to `false`. If you wish to keep the old behavior, you can explicitly set `isUrlFilterCaseSensitive` to `true` in
your declarativeNetRequest rules.

This follows [discussions](https://github.com/w3c/webextensions/issues/269) in the Web Extensions
Community Group. Firefox and Safari have already implemented a similar change.
```
I feel like this flows better. Right now, it's looking a bit chopped up:

![Screenshot 2023-10-10 at 11 46 43](https://github.com/GoogleChrome/developer.chrome.com/assets/37001393/0353ffb3-1f91-4d79-a625-faaf51725179)

2023-10-10 17:09 UTC, Mohammed71o commented
Ok,je vais la Petter cette ordi ok, bye

Le mar. 10 oct. 2023, 12 h 49, amysteamdev ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
>
> I'm helping out Joe with a couple of reviews. I made a suggestion to
> improve the flow
> ------------------------------
>
> In site/en/docs/extensions/whatsnew/index.md
> <https://github.com/GoogleChrome/developer.chrome.com/pull/7482#discussion_r1352918378>
> :
>
> > +Starting in Chrome 118, the [isUrlFilterCaseSensitive](/docs/extensions/reference/declarativeNetRequest/#property-RuleCondition-isUrlFilterCaseSensitive)
> +property in the [chrome.declarativeNetRequest](/docs/extensions/reference/declarativeNetRequest/)
> +API has been changed to default to false.
> +
> +This follows [discussions](https://github.com/w3c/webextensions/issues/269) in the Web Extensions
> +Community Group and a similar change already implemented by Firefox and Safari.
> +
> +If you wish to keep the old behavior, you can explicitly set isUrlFilterCaseSensitive to true in
> +your declarativeNetRequest rules.
>
> ⬇️ Suggested change
>
> -Starting in Chrome 118, the [isUrlFilterCaseSensitive](/docs/extensions/reference/declarativeNetRequest/#property-RuleCondition-isUrlFilterCaseSensitive)
> -property in the [chrome.declarativeNetRequest](/docs/extensions/reference/declarativeNetRequest/)
> -API has been changed to default to false.
> -
> -This follows [discussions](https://github.com/w3c/webextensions/issues/269) in the Web Extensions
> -Community Group and a similar change already implemented by Firefox and Safari.
> -
> -If you wish to keep the old behavior, you can explicitly set isUrlFilterCaseSensitive to true in
> -your declarativeNetRequest rules.
> +Starting in Chrome 118, the [`isUrlFilterCaseSensitive`](/docs/extensions/reference/declarativeNetRequest/#property-RuleCondition-isUrlFilterCaseSensitive)
> +property in the [chrome.declarativeNetRequest](/docs/extensions/reference/declarativeNetRequest/)
> +API has been changed to default to `false`. If you wish to keep the old behavior, you can explicitly set `isUrlFilterCaseSensitive` to `true` in
> +your declarativeNetRequest rules.
> +
> +This follows [discussions](https://github.com/w3c/webextensions/issues/269) in the Web Extensions
> +Community Group. Firefox and Safari have already implemented a similar change.
>
> I feel like this flows better. Right now, it's looking a bit chopped up:
>
> [image: Screenshot 2023-10-10 at 11 46 43]
> <https://user-images.githubusercontent.com/37001393/273995279-0353ffb3-1f91-4d79-a625-faaf51725179.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleChrome/developer.chrome.com/pull/7482#pullrequestreview-1668295133>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BDBWREOF2AD3PXHKDINA5Y3X6V377AVCNFSM6AAAAAA5Y6A2HOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNRYGI4TKMJTGM>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***
> com>
>

2023-10-11 13:26 UTC, AmySteam approved these changes
LGTM 👍

2023-10-11 13:30 UTC, oliverdunk commented on site/en/docs/extensions/whatsnew/index.md
> +<p class="color-secondary-text type--caption">Posted on <time>October 10, 2023</time></p>
```suggestion
<p class="color-secondary-text type--caption">Posted on <time>October 11, 2023</time></p>
```

2023-10-11 13:50 UTC, merged