Split CWS publish article
GoogleChrome/developer.chrome.com pull request #7559
Opened 2023-10-16 23:29 UTC by AmySteam

Fixes #https://github.com/GoogleChromeLabs/Extension-Docs/issues/219

Changes proposed in this pull request:

-
-
-

2023-10-16 23:43 UTC, jpmedley requested changes
Aside from the broken link I already noted, the [next step items on register](https://developer.chrome.com/docs/extensions/mv3/user_interface/#localize) don't match the actual next steps.

2023-10-16 23:43 UTC, jpmedley commented on site/en/docs/webstore/set-up-account/index.md
> +- [Publish your extension][publish].
This link is broken.

2023-10-17 01:28 UTC, AmySteam commented on site/en/docs/webstore/set-up-account/index.md
> +- [Publish your extension][publish].
Good catch! Fixed links 👍

2023-10-17 23:58 UTC, AmySteam commented
@jpmedley PTAL

2023-10-18 16:45 UTC, jpmedley approved these changes

2023-10-18 18:33 UTC, merged