`new post` CSS text-wrap: pretty
GoogleChrome/developer.chrome.com pull request #7581
Opened 2023-10-18 16:50 UTC by argyleink

ToDo:
- [ ] get final review
- [ ] update date

2023-10-21 06:57 UTC, rachelandrew requested changes
Just a couple of things to fix.

2023-10-21 06:57 UTC, rachelandrew commented on site/en/blog/css-text-wrap-pretty/index.md
> +Set to release in Chrome 117 is a new text wrapping feature—`text-wrap: pretty`
```suggestion
From Chrome 117 you can use a new text wrapping feature—`text-wrap: pretty`
```

2023-10-21 06:57 UTC, rachelandrew commented on site/en/blog/css-text-wrap-pretty/index.md
> +    Image sourced from <a href="https://fonts.google.com/knowledge/glossary/widows_orphans">Google Fonts - Widows & Orphans</a>
```suggestion
    Image sourced from <a href="https://fonts.google.com/knowledge/glossary/widows_orphans">Google Fonts—Widows & Orphans</a>
```

2023-10-21 06:57 UTC, rachelandrew commented on site/en/blog/css-text-wrap-pretty/index.md
> +    Image sourced from <a href="https://uxmovement.com/content/why-you-should-remove-orphans-from-your-body-text/">Why you should remove orphans from your body text</a>
```suggestion
    Image sourced from <a href="https://uxmovement.com/content/why-you-should-remove-orphans-from-your-body-text/">Why you should remove orphans from your body text.</a>
```

2023-10-21 06:57 UTC, rachelandrew commented on site/en/blog/css-text-wrap-pretty/index.md
> +If you have other line breaking improvements or suggestions, we'd love to hear
Add a link to the tracker.

2023-10-23 15:04 UTC, argyleink commented on site/en/blog/css-text-wrap-pretty/index.md
> +them! File an issue in the Chromium bug tracker with the details, examples of
```suggestion
them! File an issue in the [Chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/entry) with the details, examples of
```

2023-10-23 15:05 UTC, argyleink commented on site/en/blog/css-text-wrap-pretty/index.md
> +date: 2023-10-18
```suggestion
date: 2023-10-23
```

2023-10-23 15:08 UTC, argyleink commented
> Just a couple of things to fix.

ty! fixes are in 👍🏻

2023-10-23 15:09 UTC, rachelandrew approved these changes

2023-10-23 15:24 UTC, merged