Offline-First TWA doc
GoogleChrome/developer.chrome.com pull request #762
Opened 2021-05-11 22:49 UTC by demianrenzulli

Fixes #693

Offline-First TWA doc. Companion article for [demo](https://github.com/GoogleChrome/android-browser-helper/tree/main/demos/twa-offline-first) in [android-browser-helper repo](https://github.com/GoogleChrome/android-browser-helper).

cc // @jpmedley @kaycebasques @andreban

2021-05-12 14:21 UTC, jpmedley commented
@demianrenzulli Are all technical and content reviews finished? Copy edits are best done after text has stablized.

2021-05-12 14:28 UTC, demianrenzulli commented
Hi @jpmedley! 

So far, I received your comments and a review by @andreban. The [demo](https://github.com/GoogleChrome/android-browser-helper/tree/main/demos/twa-offline-first) this article is based on was reviewed by @PEConn.

From the thread with @kaycebasques, it doesn't seem we need any additional reviewers.

2021-05-12 19:30 UTC, jpmedley commented
Kayce was probably reviewing for content appropriateness and structure. There's always a final review for typos and grammar mistakes.

@kaycebasques What type of review did you do?

2021-05-12 19:34 UTC, demianrenzulli commented
I don't think @kaycebasques did a review yet, he just connected us with you for next steps. If Kayce can take another look, that would be great! I just don't want to give you guys so much work.

Thanks for the help!

2021-05-12 20:29 UTC, jpmedley commented
@demianrenzulli Before we edit this, can you please break the lines at 80 characters. You'll notice that all of our article sources are broken. It has certain advantages during the editing process.

Thanks.

2021-05-12 21:03 UTC, demianrenzulli commented
@jpmedley I just ran [rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) to break each line at the 80 chars. I hope it helps!

2021-05-12 21:21 UTC, jpmedley commented
Thank you very much.
Joe Medley | Technical Writer, Chrome DevRel | ***@***.*** |
 816-678-7195
*If an API's not documented it doesn't exist.*


On Wed, May 12, 2021 at 2:03 PM Demian Renzulli ***@***.***>
wrote:

> @jpmedley <https://github.com/jpmedley> I just ran rewrap
> <https://marketplace.visualstudio.com/items?itemName=stkb.rewrap> to
> break each line at the 80 chars. I hope it helps!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleChrome/developer.chrome.com/pull/762#issuecomment-840094924>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB6S7C7H6M34T5P7CZD6RB3TNLUKVANCNFSM44XFYYJA>
> .
>

2021-05-13 13:44 UTC, jpmedley requested changes

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +the app there's no connectivity.
```suggestion
The first step is to create a custom launcher activity. This `Activity`
that will contain the offline screen to show if there's no connectivity
the first time a user opens the app.
```

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +Activity and defines [https://airhorner.com](https://airhorner.com) as the URL
```suggestion
activity and defines [https://airhorner.com](https://airhorner.com) as the URL
```

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +First, inside the Activity, override the method `shouldLaunchImmediately()` and
```suggestion
First, inside the Activity, override the `shouldLaunchImmediately()` method and
```

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +immediately, and you can add some extra checks before the initial launch:
```suggestion
immediately. You can also add extra checks before the initial launch:
```

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +- If the TWA has launched previously, this means that the service worker has
```suggestion
- If the TWA has launched previously, the service worker has
```

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +  call the method `launchTwa()` defined in the parent class to launch the
```suggestion
  call `launchTwa()`, defined in the parent class, to launch the
```

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +Here's how the code to check of offline state `isOnline()` looks like:
```suggestion
Here's the code for checking offline state `isOnline()`:
```

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +Next, implement `hasTwaLaunchedSuccessfully()` used to check if the TWA has
```suggestion
Next, implement `hasTwaLaunchedSuccessfully()`, which checks if the TWA has
```

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +`twa_launched_successfully` flag in shared preferences, to indicate that the TWA
```suggestion
`twa_launched_successfully` flag in shared preferences, to indicate that the TWA
```
```suggestion
`twa_launched_successfully` flag in shared preferences. This indeicates that the TWA
```

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +The remaining helper method: `renderOfflineFallback()` renders an Android
```suggestion
The remaining helper method, `renderOfflineFallback()` renders an Android
```

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +`firstTimeLaunchTwa()` after checking connection:
```suggestion
`firstTimeLaunchTwa()` after checking the connection.
```

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +`firstTimeLaunchTwa()` after checking connection:
Colons aren't used to introduce images. If you feel that the image needs to be referenced in text, add something like, 'see the image below'.

2021-05-13 13:44 UTC, jpmedley commented on site/en/docs/android/trusted-web-activity/offline-first/index.md
> +  [here](https://github.com/GoogleChrome/android-browser-helper/tree/main/demos/twa-offline-first).
```suggestion
  interested in checking the code we used throughout this guide, you can find
  the complete solution in the [Offline First TWA
  Demo](https://github.com/GoogleChrome/android-browser-helper/tree/main/demos/twa-offline-first).
```

2021-05-13 17:37 UTC, demianrenzulli commented
Hi @jpmedley! Thanks again for leaving your suggestions. I just went through all of them and committed the changes.

Please, let me know if you need anything else from me.

2021-05-13 19:40 UTC, jpmedley approved these changes

2021-05-13 19:41 UTC, jpmedley commented
@demianrenzulli DevRel members merge their own articles after approval. I don't believe you have the authority. Let me know if you need me to merge this.

2021-05-13 20:22 UTC, demianrenzulli commented
@jpmedley I remember Kayce asked to merge some posts myself in Web.dev, but I never wrote something for developer.chrome.com, so I would appreciate if you can marge on my behalf.

2021-05-14 13:06 UTC, merged