[WasmGC article] Add Flutter demo
GoogleChrome/developer.chrome.com pull request #7704
Opened 2023-10-31 23:09 UTC by tomayac

Changes proposed in this pull request:

- Add Flutter demo.

2023-10-31 23:10 UTC, tomayac commented on site/en/blog/wasmgc/index.md
> +The Dart and Flutter teams at Google are also preparing support for WasmGC support. The Dart-to-Wasm compilation work is almost complete and the team is working on tooling support for delivering Flut
```suggestion
The Dart and Flutter teams at Google are also preparing support for WasmGC. The Dart-to-Wasm compilation work is almost complete, and the team is working on tooling support for delivering Flutter web applications compiled to WebAssembly. You can read about the current state of the work in the [Flutter documentation](https://flutter.dev/wasm). A demo showcasing the Flutter WasmGC Preview is embedded below.
```

2023-10-31 23:29 UTC, tomayac commented
@rachelandrew or whoever ends up reviewing this: please merge it from your end immediately, as tomorrow’s a public holiday here. Thank you !

2023-11-01 07:57 UTC, rachelandrew commented on site/en/blog/wasmgc/index.md
> +### Kotlin/Wasm
```suggestion
### Kotlin and Wasm
```

2023-11-01 07:59 UTC, rachelandrew commented on site/en/blog/wasmgc/index.md
> +The Dart and Flutter teams at Google are also preparing support for WasmGC. The Dart-to-Wasm compilation work is almost complete, and the team is working on tooling support for delivering Flutter web
```suggestion
The Dart and Flutter teams at Google are also preparing support for WasmGC. The Dart-to-Wasm compilation work is almost complete, and the team is working on tooling support for delivering Flutter web applications compiled to WebAssembly. You can read about the current state of the work in the [Flutter documentation](https://flutter.dev/wasm). The following demo is the [Flutter WasmGC Preview](https://flutterweb-wasm.web.app/).
```

2023-11-01 08:01 UTC, rachelandrew requested changes
See changes inline.

2023-11-01 10:43 UTC, tomayac commented
It's actually officially Kotlin/,Wasm, with slash.

2023-11-01 10:45 UTC, rachelandrew commented
> It's actually officially Kotlin/,Wasm, with slash.

You appeared to have just ignored the suggestion, rather than comment on it. Our style guide suggests not using the slash like that so unless I'm told specifically I'm going to change it.

2023-11-01 12:35 UTC, mraleph commented
@rachelandrew `Kotlin/Wasm` refers to [this](https://kotlinlang.org/docs/wasm-overview.html). It the official name of the compilation target. They also have `Kotlin/Native` and `Kotlin/JS`.

2023-11-01 12:38 UTC, rachelandrew commented
> @rachelandrew `Kotlin/Wasm` refers to [this](https://kotlinlang.org/docs/wasm-overview.html). It is the official name of the compilation target. They also have `Kotlin/Native` and `Kotlin/JS`.

yes that's not a problem, I was just explaining why I merged the suggestion as Thomas didn't respond to it to explain, and I was trying not to block.

2023-11-01 12:41 UTC, rachelandrew commented
I also note that the page you sent me to has a title "Kotlin Wasm" and not "Kotlin/Wasm", the former would definitely be less confusing as what it looks like to anyone who doesn't know is "Kotlin and Wasm" or "Kotlin or Wasm". So I would suggest we use what the project is using on their site?

2023-11-01 12:42 UTC, rachelandrew commented on site/en/blog/wasmgc/index.md
> +### Kotlin and Wasm
```suggestion
### Kotlin Wasm
```

2023-11-01 12:42 UTC, rachelandrew commented on site/en/blog/wasmgc/index.md
> +### Kotlin and Wasm
Changed to match https://kotlinlang.org/docs/wasm-overview.html

2023-11-01 12:50 UTC, mraleph commented
> I also note that the page you sent me to has a title "Kotlin Wasm" and not "Kotlin/Wasm", the former would definitely be less confusing as what it looks like to anyone who doesn't know is "Kotlin and Wasm" or "Kotlin or Wasm". So I would suggest we use what the project is using on their site?

FWIW it has 12 unique occurrences of "Kotlin/Wasm" and 3 unique occurrences of "Kotlin Wasm". 

I am fairly sure most of their own documentation refers to it as Kotlin/Wasm.

2023-11-01 13:22 UTC, rachelandrew commented
> > I also note that the page you sent me to has a title "Kotlin Wasm" and not "Kotlin/Wasm", the former would definitely be less confusing as what it looks like to anyone who doesn't know is "Kotlin and Wasm" or "Kotlin or Wasm". So I would suggest we use what the project is using on their site?
> 
> FWIW it has 12 unique occurrences of "Kotlin/Wasm" and 3 unique occurrences of "Kotlin Wasm".
> 
> I am fairly sure most of their own documentation refers to it as Kotlin/Wasm.

The page referenced uses the space, which is clearer for our audience, and given there is already use of that, that's what we'll use. I've added it as a suggestion inline.

2023-11-01 13:26 UTC, mraleph commented
@rachelandrew it only uses "Kotlin Wasm" in the title and 2 other places. It uses Kotlin/Wasm in many more places. 
![Screenshot 2023-11-01 at 14 25 00](https://github.com/GoogleChrome/developer.chrome.com/assets/131846/7686158b-9759-4e1e-8fbd-091931626c72) (cc @bashorov).

Though to be honest it is not the hill I would die on. It's not even what this PR is about.

2023-11-02 10:30 UTC, mit-mit commented
Yeah, let's get this PR merged, and then we can clean up the Kotlin/Wasm stuff (if deemed needed) in a second PR.

2023-11-02 10:30 UTC, mit-mit commented
@rachelandrew can we please merge this? I believe Tom is OOO.

2023-11-02 10:33 UTC, rachelandrew commented
Happy to merge it with the space, as I feel it's less confusing. If the docs are changed so they never use it with the space, fine. But to anyone who doesn't know the project (including me, as it was my confusion that started this) the slash is confusing, so if there's an option to avoid it, I'm going to use it.

2023-11-02 11:04 UTC, mraleph commented
I am fine with the space. We can address this later.

2023-11-02 11:13 UTC, tomayac commented
@rachelandrew We seem to have it in a mergeable state now… PTAL. Thanks!

2023-11-02 11:28 UTC, rachelandrew approved these changes

2023-11-02 11:35 UTC, merged