Add deprecations and removals for Chrome 92.
GoogleChrome/developer.chrome.com pull request #850
Opened 2021-06-03 18:07 UTC by jpmedley

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

2021-07-07 13:38 UTC, jpmedley commented
@robdodson I didn't realize this was still open. What I need is a copy edit from @rachelandrew or @mihajlija.

2021-07-07 15:01 UTC, myakura commented
> What I need is a copy edit

Is that the same reason that deps-rems-91 post is holding off? I see there is a branch but there hasn't been a PR yet.
https://github.com/GoogleChrome/developer.chrome.com/issues/833#issuecomment-850822367

2021-07-23 06:40 UTC, rachelandrew requested changes

2021-07-23 06:40 UTC, rachelandrew commented on site/en/blog/deps-rems-92/index.md
> +date: 2021-06-03
```suggestion
date: 2021-07-23
```

2021-07-23 06:40 UTC, rachelandrew commented on site/en/blog/deps-rems-92/index.md
> +removed](https://www.chromestatus.com/feature/5407573287108608).
```suggestion
removed](https://www.chromestatus.com/feature/5717324021628928).
```

2021-07-23 06:40 UTC, rachelandrew commented on site/en/blog/deps-rems-92/index.md
> +removed](https://www.chromestatus.com/feature/5407573287108608).
I think this is the correct URL.

2021-07-23 06:40 UTC, rachelandrew commented on site/en/blog/deps-rems-92/index.md
> +This feature, which enabled web-based payment handlers to receive paymentrequest
```suggestion
This feature, which enabled web-based payment handlers to receive `paymentrequest`
```

2021-07-29 14:28 UTC, jpmedley commented
@rachelandrew PTAL

2021-08-17 00:56 UTC, samthor commented
Can we get this in? I'm happy with it, although not a writer.

2021-08-17 03:43 UTC, rachelandrew approved these changes

2021-08-17 03:45 UTC, rachelandrew commented on site/en/blog/deps-rems-92/index.md
> +date: 2021-07-23
```suggestion
date: 2021-08-16
```

2021-08-17 04:15 UTC, merged