Update policy and FAQ docs for Apollo launch
GoogleChrome/developer.chrome.com pull request #916
Opened 2021-06-23 00:40 UTC by awfuchs

Update the spam FAQ doc

2021-06-24 00:14 UTC, dotproto requested changes
Looks like the doc to markdown tool may have introduced a number of unexpected changes.

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
> +<h2>Keyword spam</h2>
```suggestion
## Keyword spam {: #keyword-spam }
```

There doesn't seem to be a benefit to using an H2 over the Markdown equivalent.

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
> +### How many sites/keywords/brands can be listed in the metadata?
```suggestion
### How many sites/keywords/brands can be listed in the metadata? {: #keyword-repetition }
```

Re-add the ID tag. Unfortunately there was a typo in the previous tag name. The original motivation for adding these tags was to make the final URL more human readable and consistent across title changes. Compare the following:

* Explicit: https://developer.chrome.com/docs/webstore/spam-faq/#keyword-repetition
* Auto-generated: https://developer.chrome.com/docs/webstore/spam-faq/#how-many-siteskeywordsbrands-can-be-listed-in-the-metadata

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
> +### Can the extension description contain information about additional topics related to the extension?
```suggestion
### Can the extension description contain information about additional topics related to the extension? {: #unrelated-information }
```

Remove extra newline and re-add the ID tag. Removing the ID end may break existing links.

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
```suggestion
```

Remove extra newline.

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
> +### What is the maximum number of times the extension's primary purpose can be mentioned in the description?
```suggestion
### What is the maximum number of times the extension's primary purpose can be mentioned in the description? {: #purpose-repetition }
```

Re-add the ID tag. Unfortunately there was a typo in the previous tag name.

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
> +### Can the extension's short description be repeated in the extension's description?
```suggestion
### Can the extension's short description be repeated in the extension's description? {: #short-description-repetition }
```

Remove extra newline and re-add the ID tag.

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
```suggestion
```

Remove extra newline.

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
> +### What does it mean to manipulate placement?
```suggestion
## User ratings, reviews, and installs {: #ratings-and-reviews }

### What does it mean to manipulate placement? {: #manipulate-placement }
```

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
> +### Can I provide incentives for users to download my extension?
```suggestion
### Can I provide incentives for users to download my extension? {: #download-incentives }
```

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
> +### Can I review or rate my own extension?
```suggestion
### Can I review or rate my own extension? {: #self-review }
```

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
```suggestion
```

Remove extra newline.

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
> +### Can I publish an extension that directs users to my app?
```suggestion
## Extension functionality {: #functionality }

### Can I publish an extension that directs users to my app? {: #app-promotion }
```

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
> +### How can developers consolidate their user base?
```suggestion
### How can developers consolidate their user base? {: #consolidation }
```

2021-06-24 00:14 UTC, dotproto commented on site/en/docs/webstore/spam-faq/index.md
> +
```suggestion
```

Remove extra newline.

2021-06-25 21:14 UTC, awfuchs commented on site/en/docs/webstore/spam-faq/index.md
> +specific) be considered a violation of repetitive content policy? For example:
Done.

2021-06-25 23:31 UTC, dotproto approved these changes
LGTM

2021-06-25 23:32 UTC, dotproto commented
@googlebot I consent

2021-06-29 18:03 UTC, merged