Update index.md
GoogleChrome/developer.chrome.com pull request #958
Opened 2021-07-03 18:46 UTC by factoidforrest

mentioning the manifest pane and having an image of it was irrelevant and distracting.  We just want to know where to head, and that leads the reader to believe that they should be in the manifest pane before they continue reading.  It's like telling someone "You see a fork in the road, and you will want to head not left".

Fixes #SOME_ISSUE_NUMBER

Changes proposed in this pull request:

-
-
-

2021-07-03 18:47 UTC, factoidforrest commented
@googlebot I signed it!

2021-07-05 05:49 UTC, rachelandrew requested changes
I agree with this suggestion, having just worked through the steps in the original article, it really doesn't matter which pane opens up, the reader just needs to know to select storage.

However, the figure numbering will need to be corrected throughout the document, are you able to make that change?

2021-08-03 22:48 UTC, samthor commented
@factoidforrest we're happy to accept the PR but can you make the suggested change?

2021-08-19 05:26 UTC, samthor commented
Took this over in #1235.

2021-08-19 05:26 UTC, closed without merging